package server

var (
	publicArtifactResearchCueMatcher = newUnicodeAhoMatcher([]string{
		"research",
		"research the",
		"find",
		"look up",
		"search",
		"current",
		"latest",
		"today",
		"this year",
		"upcoming",
		"price",
		"stock",
		"ticker",
		"market",
		"market summary",
		"conference",
		"conferences",
		"event",
		"events",
		"website",
		"websites",
		"official website",
		"official site",
		"competitor",
		"competitors",
		"industry",
		"调研",
		"研究",
		"查一下",
		"查找",
		"搜索",
		"当前",
		"最新",
		"今日",
		"今年",
		"即将",
		"价格",
		"股价",
		"股票",
		"代码",
		"市场",
		"会议",
		"大会",
		"活动",
		"官网",
		"官方网站",
		"竞品",
		"竞争对手",
		"行业",
	})

	heavyResearchIntentCueMatcher = newUnicodeAhoMatcher([]string{
		"deep research",
		"comprehensive research",
		"research report",
		"with sources",
		"with citations",
		"with references",
		"include sources",
		"include citations",
		"include references",
		"multiple sources",
		"multi-source",
		"evidence-backed",
		"深度搜索",
		"深度研究",
		"全面调研",
		"完整报告",
		"详细报告",
		"附来源",
		"附引用",
		"多轮检索",
	})

	deepResearchForceStrongCueMatcher = newUnicodeAhoMatcher([]string{
		"sota",
		"state of the art",
		"best practice",
		"best practices",
		"benchmark",
		"competitive landscape",
		"industry standard",
		"最佳实践",
	})

	deepResearchForceComparativeCueMatcher = newUnicodeAhoMatcher([]string{
		"compare",
		"comparison",
		"versus",
		"tradeoff",
		"trade-off",
		"pros and cons",
		"strengths and weaknesses",
		"对比",
		"比较",
		"区别",
		"差异",
		"优缺点",
	})

	shellCommandCueMatcher = newUnicodeAhoMatcher([]string{
		"bash",
		"shell",
		"terminal",
		"command line",
		"run command",
		"execute command",
		"终端",
		"命令行",
		"运行命令",
		"执行命令",
	})

	codeTaskCueMatcher = newUnicodeAhoMatcher([]string{
		"fix bug",
		"debug",
		"refactor",
		"implement",
		"compile",
		"build",
		"run tests",
		"run test",
		"unit test",
		"integration test",
		"修复",
		"调试",
		"重构",
		"实现",
		"编译",
		"构建",
		"测试",
	})

	workspaceFileWorkflowCueMatcher = newUnicodeAhoMatcher([]string{
		"review all files",
		"read all",
		"workspace",
		"folder",
		"directory",
		"files in",
		"summary",
		"summarize",
		"summarise",
		"briefing",
		"digest",
		"report",
		"triage",
		"compare",
		"analyze",
		"analyse",
		".md",
		".txt",
		".csv",
		".xlsx",
		".xls",
		".pdf",
		"工作区",
		"文件夹",
		"目录",
		"文件",
		"总结",
		"摘要",
		"简报",
		"报告",
		"归纳",
		"整理",
		"分析",
		"对比",
	})

	workspaceFileEditCueMatcher = newUnicodeAhoMatcher([]string{
		"update",
		"change",
		"replace",
		"modify",
		"edit",
		"rewrite",
		"search and replace",
		"find and replace",
		"all instances",
		"list what changes",
		"批量修改",
		"替换",
		"更新",
		"修改",
		"编辑",
		"改成",
		"替换成",
		"列出改动",
	})

	explicitWorkspaceSourceCueMatcher = newUnicodeAhoMatcher([]string{
		"workspace",
		"folder",
		"directory",
		"files in",
		"provided to you",
		"provided in",
		"current directory",
		"current folder",
		"repo",
		"repository",
		"local file",
		"local files",
		"工作区",
		"文件夹",
		"目录",
		"仓库",
		"本地文件",
	})

	explicitMemoryFileStoreCueMatcher = newUnicodeAhoMatcher([]string{
		"remember this",
		"remember the following",
		"remember for me",
		"remember that",
		"note this",
		"don't forget",
		"save this information",
		"store this information",
		"save it to a file",
		"store it to a file",
		"save it to",
		"store it in",
		"recall it later",
		"future session",
		"记住这件事",
		"记住这个",
		"帮我记住",
		"不要忘记",
		"保存这个信息",
		"存下这个信息",
		"保存到文件",
		"写到文件",
		"之后回忆",
		"之后再读",
		"recuerda esto",
		"recuerda lo siguiente",
		"guarda esta información",
		"guárdalo en un archivo",
		"para recordarlo después",
		"souviens-toi de ceci",
		"souviens-toi de ça",
		"enregistre ces informations",
		"enregistre-le dans un fichier",
		"pour le retrouver plus tard",
		"merk dir das",
		"speichere diese informationen",
		"speichere es in einer datei",
		"später abrufen",
		"lembre disso",
		"lembre-se disso",
		"salve estas informações",
		"salve em um arquivo",
		"recuperar depois",
		"запомни это",
		"сохрани эту информацию",
		"сохрани в файл",
		"потом вспомнить",
		"これを覚えて",
		"この情報を保存",
		"ファイルに保存",
		"後で思い出せる",
		"이걸 기억해",
		"이 정보를 저장",
		"파일에 저장",
		"나중에 다시",
	})

	explicitMemoryFileRecallCueMatcher = newUnicodeAhoMatcher([]string{
		"read that file",
		"read this file",
		"read the file",
		"check the file",
		"look at the file",
		"open the file",
		"based on what you find in the file",
		"you can check the",
		"i previously saved",
		"answer these questions",
		"answer all",
		"read it and answer",
		"从文件里读取",
		"读取这个文件",
		"读取该文件",
		"查看这个文件",
		"查看该文件",
		"根据文件内容",
		"根据你在文件里找到的内容",
		"回答这些问题",
		"回答全部问题",
		"之前保存",
		"lee ese archivo",
		"lee este archivo",
		"revisa el archivo",
		"según lo que encuentres en el archivo",
		"responde estas preguntas",
		"lis ce fichier",
		"vérifie le fichier",
		"selon ce que tu trouves dans le fichier",
		"réponds à ces questions",
		"lies diese datei",
		"prüfe die datei",
		"basierend auf dem dateiinhalt",
		"beantworte diese fragen",
		"leia esse arquivo",
		"leia este arquivo",
		"verifique o arquivo",
		"com base no que encontrar no arquivo",
		"responda a estas perguntas",
		"прочитай этот файл",
		"проверь файл",
		"исходя из содержимого файла",
		"ответь на эти вопросы",
		"このファイルを読んで",
		"ファイルを確認して",
		"ファイルの内容に基づいて",
		"これらの質問に答えて",
		"이 파일을 읽고",
		"파일을 확인하고",
		"파일 내용을 바탕으로",
		"이 질문에 답해",
	})

	directArtifactWritingBlockerCueMatcher = newUnicodeAhoMatcher([]string{
		"latest",
		"news",
		"current",
		"website",
		"websites",
		"sources",
		"citations",
		"references",
		"search the web",
		"web search",
		"browser",
		"新闻",
		"当前",
		"官网",
		"来源",
		"引用",
		"搜索",
		"浏览器",
	})

	directArtifactWritingCueMatcher = newUnicodeAhoMatcher([]string{
		"write",
		"draft",
		"compose",
		"blog",
		"blog post",
		"email",
		"letter",
		"memo",
		"summary",
		"article",
		"post",
		"rewrite",
		"rephrase",
		"polish",
		"proofread",
		"format",
		"response",
		"reply",
		"写",
		"起草",
		"撰写",
		"博客",
		"邮件",
		"信",
		"备忘录",
		"摘要",
		"总结",
		"文章",
		"改写",
		"润色",
		"校对",
		"格式化",
		"回复",
	})

	reminderIntentCueMatcher = newUnicodeAhoMatcher([]string{
		"remind",
		"reminder",
		"set reminder",
		"set a reminder",
		"notify me",
		"alert me",
		"drink water",
		"hydrate",
		"提醒",
		"提醒我",
		"闹钟",
		"通知我",
		"喝水",
		"记得",
	})

	emailIntentPrimaryCueMatcher = newUnicodeAhoMatcher([]string{
		"收件箱",
		"邮箱",
		"未读邮件",
		"归档邮件",
		"邮件标签",
		"发件人",
		"邮件摘要",
		"邮件检索",
		"inbox",
		"mailbox",
		"unread email",
		"archive email",
		"email summary",
		"email digest",
	})

	emailIntentTopicCueMatcher = newUnicodeAhoMatcher([]string{
		"email",
		"mail",
		"邮件",
	})

	emailIntentActionCueMatcher = newUnicodeAhoMatcher([]string{
		"archive",
		"archived",
		"label",
		"labels",
		"sender",
		"from",
		"unread",
		"priority",
		"search",
		"find",
		"filter",
		"归档",
		"标签",
		"发件人",
		"未读",
		"优先级",
		"检索",
		"筛选",
	})

	calendarIntentPrimaryCueMatcher = newUnicodeAhoMatcher([]string{
		"calendar",
		"agenda",
		"daily summary",
		"daily agenda",
		"today's agenda",
		"today agenda",
		"today schedule",
		"schedule for today",
		"日历",
		"日程",
		"议程",
		"今天安排",
		"今日安排",
		"今天日程",
		"每日摘要",
		"日程摘要",
	})

	calendarIntentTopicCueMatcher = newUnicodeAhoMatcher([]string{
		"meeting",
		"event",
		"appointment",
		"会议",
		"事件",
		"预约",
		"行程",
	})

	calendarIntentTimeCueMatcher = newUnicodeAhoMatcher([]string{
		"today",
		"tomorrow",
		"next week",
		"tonight",
		"上午",
		"下午",
		"明天",
		"下周",
		"今晚",
		"点",
	})

	pureWritingIntentCueMatcher = newUnicodeAhoMatcher([]string{
		"rewrite",
		"rephrase",
		"polish",
		"proofread",
		"edit this",
		"improve wording",
		"make this concise",
		"make it shorter",
		"make it more formal",
		"change the tone",
		"format this",
		"turn this into",
		"draft",
		"summarize this text",
		"改写",
		"重写",
		"润色",
		"精简",
		"扩写",
		"换个语气",
		"换一种说法",
		"校对",
		"纠正语法",
		"格式化",
		"起草",
		"写一段",
		"写一封",
		"总结这段",
	})

	pureWritingBlockerCueMatcher = newUnicodeAhoMatcher([]string{
		"http://",
		"https://",
		"www.",
		"url",
		"网页",
		"网站",
		"browser",
		"web search",
		"search the web",
		"收件箱",
		"邮箱",
		"日历",
		"日程",
		"calendar",
		"inbox",
		"latest",
		"news",
		"sources",
		"citations",
		"references",
		"search",
		"look up",
		"最新",
		"新闻",
		"来源",
		"引用",
		"搜索",
		"检索",
	})
)
