package tools

import (
	"fmt"
	"io"
	"math"
	"strconv"
	"strings"
)

type officePPTXSlide struct {
	Title      string
	Lines      []string
	Table      *officeTableSpec
	Chart      *officeChartSpec
	chartRelID string
}

type officePPTXChartWorkbookPackage struct {
	SheetName          string
	RelationshipID     string
	RelationshipTarget string
	EntryName          string
	Data               []byte
}

type officePPTXChartPackage struct {
	ChartXML     string
	ChartRelsXML string
	Workbook     *officePPTXChartWorkbookPackage
}

func buildOfficePPTX(spec officeDocSpec) ([]byte, officeBuildInfo, error) {
	slides := officeBuildPresentationSlides(spec)
	if len(slides) == 0 {
		return nil, officeBuildInfo{}, fmt.Errorf("pptx output requires at least one slide")
	}

	chartCount := 0
	embeddedWorkbookCount := 0
	for idx := range slides {
		if slides[idx].Chart != nil {
			chartCount++
			slides[idx].chartRelID = "rId2"
		}
	}

	entries := []officeZipEntry{
		{Name: "[Content_Types].xml", Content: officePPTXContentTypesXML(len(slides), chartCount, embeddedWorkbookCount)},
		{Name: "_rels/.rels", Content: officePackageRelsXML("ppt/presentation.xml")},
		{Name: "docProps/core.xml", Content: officeCorePropsXML(spec.Title, "Presentation generated by ZimaOS Blue")},
		{Name: "docProps/app.xml", Content: officePPTXAppPropsXML(slides)},
		{Name: "ppt/presentation.xml", Content: officePPTXPresentationXML(len(slides))},
		{Name: "ppt/_rels/presentation.xml.rels", Content: officePPTXPresentationRelsXML(len(slides))},
		{Name: "ppt/slideMasters/slideMaster1.xml", Content: officePPTXSlideMasterXML()},
		{Name: "ppt/slideMasters/_rels/slideMaster1.xml.rels", Content: officePPTXSlideMasterRelsXML()},
		{Name: "ppt/slideLayouts/slideLayout1.xml", Content: officePPTXSlideLayoutXML()},
		{Name: "ppt/slideLayouts/_rels/slideLayout1.xml.rels", Content: officePPTXSlideLayoutRelsXML()},
		{Name: "ppt/theme/theme1.xml", Content: officePPTXThemeXML()},
	}
	nextChartIndex := 1
	for idx, slide := range slides {
		chartIndex := 0
		if slide.Chart != nil {
			chartIndex = nextChartIndex
			chartPackage, err := officeBuildPPTXChartPackage(*slide.Chart, chartIndex)
			if err != nil {
				return nil, officeBuildInfo{}, err
			}
			entries = append(entries, officeZipEntry{
				Name:    fmt.Sprintf("ppt/charts/chart%d.xml", chartIndex),
				Content: chartPackage.ChartXML,
			})
			if chartPackage.ChartRelsXML != "" {
				entries = append(entries, officeZipEntry{
					Name:    fmt.Sprintf("ppt/charts/_rels/chart%d.xml.rels", chartIndex),
					Content: chartPackage.ChartRelsXML,
				})
			}
			if chartPackage.Workbook != nil {
				embeddedWorkbookCount++
				workbookData := append([]byte(nil), chartPackage.Workbook.Data...)
				entries = append(entries, officeZipEntry{
					Name:     chartPackage.Workbook.EntryName,
					SizeHint: len(workbookData),
					WriteTo: func(w io.Writer) error {
						_, err := w.Write(workbookData)
						return err
					},
				})
			}
			nextChartIndex++
		}
		entries = append(entries,
			officeZipEntry{Name: fmt.Sprintf("ppt/slides/slide%d.xml", idx+1), Content: officePPTXSlideXML(slide)},
			officeZipEntry{Name: fmt.Sprintf("ppt/slides/_rels/slide%d.xml.rels", idx+1), Content: officePPTXSlideRelsXML(chartIndex)},
		)
	}
	entries[0].Content = officePPTXContentTypesXML(len(slides), chartCount, embeddedWorkbookCount)

	data, err := officeBuildZip(entries)
	if err != nil {
		return nil, officeBuildInfo{}, err
	}

	paragraphCount := 0
	for _, slide := range slides {
		paragraphCount += slide.paragraphCount()
	}
	return data, officeBuildInfo{
		Format:         "pptx",
		SectionCount:   len(slides),
		ParagraphCount: paragraphCount,
	}, nil
}

func officeBuildPresentationSlides(spec officeDocSpec) []officePPTXSlide {
	slides := make([]officePPTXSlide, 0, len(spec.Sections)+4)

	title := strings.TrimSpace(spec.Title)
	subtitle := strings.TrimSpace(spec.Subtitle)
	sectionTitles := officePPTXSectionTitles(spec.Sections)
	if title != "" || subtitle != "" {
		lines := []string(nil)
		if subtitle != "" {
			lines = append(lines, subtitle)
		}
		slides = append(slides, officePPTXSlide{
			Title: firstNonEmptyOfficeString(title, "Presentation"),
			Lines: lines,
		})
	}

	if len(sectionTitles) > 0 {
		tocLines := make([]string, 0, len(sectionTitles))
		for idx, sectionTitle := range sectionTitles {
			tocLines = append(tocLines, fmt.Sprintf("%d. %s", idx+1, sectionTitle))
		}
		slides = append(slides, officePPTXSlide{Title: "Table of Contents", Lines: tocLines})
	}
	if len(spec.Paragraphs) > 0 {
		slides = append(slides, officePPTXSlide{Title: "Content", Lines: officePPTXNormalizeLines(spec.Paragraphs...)})
	}

	for idx, section := range spec.Sections {
		lines := make([]string, 0, len(section.Paragraphs)+len(section.Bullets)+4)
		lines = append(lines, officePPTXNormalizeLines(section.Paragraphs...)...)
		for _, bullet := range officePPTXNormalizeLines(section.Bullets...) {
			lines = append(lines, "- "+bullet)
		}
		if len(lines) == 0 && officePPTXTableRowCount(section.Table) == 0 && section.Chart == nil {
			continue
		}
		title := strings.TrimSpace(section.Heading)
		if title == "" && section.Chart != nil {
			title = strings.TrimSpace(section.Chart.Title)
		}
		if title == "" {
			title = fmt.Sprintf("Slide %d", idx+1)
		}
		slides = append(slides, officePPTXSlide{Title: title, Lines: lines, Table: section.Table, Chart: section.Chart})
	}

	if summaryLines := officePPTXSummaryLines(spec); len(summaryLines) > 0 {
		slides = append(slides, officePPTXSlide{Title: "Summary", Lines: summaryLines})
	}

	if len(slides) == 0 {
		slides = append(slides, officePPTXSlide{
			Title: firstNonEmptyOfficeString(title, "Presentation"),
			Lines: officePPTXNormalizeLines(subtitle),
		})
	}
	return slides
}

func officePPTXSectionTitles(sections []officeDocSection) []string {
	titles := make([]string, 0, len(sections))
	for idx, section := range sections {
		title := strings.TrimSpace(section.Heading)
		if title == "" {
			title = fmt.Sprintf("Section %d", idx+1)
		}
		titles = append(titles, title)
	}
	return titles
}

func officePPTXSummaryLines(spec officeDocSpec) []string {
	lines := officePPTXNormalizeLines(spec.Summary)
	for _, note := range officePPTXNormalizeLines(spec.Notes...) {
		lines = append(lines, "- "+note)
	}
	return lines
}

func officePPTXNormalizeLines(values ...string) []string {
	lines := make([]string, 0, len(values))
	for _, value := range values {
		for _, line := range strings.Split(value, "\n") {
			line = strings.TrimSpace(line)
			if line == "" {
				continue
			}
			lines = append(lines, line)
		}
	}
	return lines
}

func officePPTXTableLines(table *officeTableSpec) []string {
	if table == nil {
		return nil
	}
	lines := make([]string, 0, len(table.Rows)+1)
	if len(table.Headers) > 0 {
		lines = append(lines, strings.Join(table.Headers, " | "))
	}
	for _, row := range table.Rows {
		cells := make([]string, 0, len(row))
		for _, cell := range row {
			cells = append(cells, anyToStringForLLM(cell))
		}
		lines = append(lines, strings.Join(cells, " | "))
	}
	return officePPTXNormalizeLines(lines...)
}

func (slide officePPTXSlide) paragraphCount() int {
	count := len(slide.Lines)
	count += officePPTXTableRowCount(slide.Table)
	return count
}

func officePPTXTableRowCount(table *officeTableSpec) int {
	if table == nil {
		return 0
	}
	count := len(table.Rows)
	if len(table.Headers) > 0 {
		count++
	}
	return count
}

func officeBuildPPTXChartPackage(chart officeChartSpec, chartIndex int) (officePPTXChartPackage, error) {
	chart = officeNormalizePPTXChart(chart)
	var workbook *officePPTXChartWorkbookPackage
	var err error
	if officePPTXChartShouldEmbedWorkbook(chart) {
		workbook, err = officePPTXChartWorkbookPackageForChart(chart, chartIndex)
		if err != nil {
			return officePPTXChartPackage{}, err
		}
	}
	return officePPTXChartPackage{
		ChartXML:     officePPTXChartXMLWithWorkbook(chart, workbook),
		ChartRelsXML: officePPTXChartRelsXML(workbook),
		Workbook:     workbook,
	}, nil
}

func officePPTXChartShouldEmbedWorkbook(chart officeChartSpec) bool {
	if !officePPTXChartUsesDateAxis(chart.CategoryAxisType) {
		return false
	}
	withTime := officePPTXChartDateAxisIncludesTime(chart.CategoryAxisType)
	for _, category := range chart.Categories {
		if _, ok := officeExcelDateSerial(category, withTime); !ok {
			return false
		}
	}
	return len(chart.Categories) > 0 && len(chart.Series) > 0
}

func officePPTXChartWorkbookPackageForChart(chart officeChartSpec, chartIndex int) (*officePPTXChartWorkbookPackage, error) {
	categoryFormat := officePPTXChartWorkbookCategoryKind(chart.CategoryAxisType)
	rows := make([][]interface{}, 0, len(chart.Categories))
	for rowIndex, category := range chart.Categories {
		row := make([]interface{}, 0, len(chart.Series)+1)
		categoryCell := interface{}(category)
		switch categoryFormat {
		case "date", "datetime":
			categoryCell = map[string]interface{}{
				"value":  category,
				"format": categoryFormat,
			}
		}
		row = append(row, categoryCell)
		for _, series := range chart.Series {
			value := 0.0
			if rowIndex < len(series.Values) {
				value = series.Values[rowIndex]
			}
			row = append(row, value)
		}
		rows = append(rows, row)
	}

	columns := make([]officeColumnSpec, 0, len(chart.Series)+1)
	columns = append(columns, officeColumnSpec{
		Header: firstNonEmptyOfficeString(strings.TrimSpace(chart.CategoryAxisTitle), "Category"),
		Key:    "category",
		Kind:   categoryFormat,
	})
	for idx, series := range chart.Series {
		columns = append(columns, officeColumnSpec{
			Header: firstNonEmptyOfficeString(strings.TrimSpace(series.Name), fmt.Sprintf("Series %d", idx+1)),
			Key:    fmt.Sprintf("series_%d", idx+1),
			Kind:   "decimal",
		})
	}

	workbookData, _, err := buildOfficeXLSX(officeWorkbookSpec{
		Theme: resolveOfficeTheme("analysis", ""),
		Sheets: []officeSheetSpec{
			{
				Name:    "Data",
				Columns: columns,
				Rows:    rows,
			},
		},
	})
	if err != nil {
		return nil, err
	}

	workbookName := fmt.Sprintf("Microsoft_Excel_Worksheet%d.xlsx", chartIndex)
	return &officePPTXChartWorkbookPackage{
		SheetName:          "Data",
		RelationshipID:     "rId1",
		RelationshipTarget: "../embeddings/" + workbookName,
		EntryName:          "ppt/embeddings/" + workbookName,
		Data:               workbookData,
	}, nil
}

func officePPTXChartWorkbookCategoryKind(categoryAxisType string) string {
	if officePPTXChartDateAxisIncludesTime(categoryAxisType) {
		return "datetime"
	}
	if officePPTXChartUsesDateAxis(categoryAxisType) {
		return "date"
	}
	return "text"
}

func officePPTXContentTypesXML(slideCount, chartCount, embeddedWorkbookCount int) string {
	var overrides strings.Builder
	for idx := 1; idx <= slideCount; idx++ {
		overrides.WriteString(fmt.Sprintf(`<Override PartName="/ppt/slides/slide%d.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`, idx))
	}
	for idx := 1; idx <= chartCount; idx++ {
		overrides.WriteString(fmt.Sprintf(`<Override PartName="/ppt/charts/chart%d.xml" ContentType="application/vnd.openxmlformats-officedocument.drawingml.chart+xml"/>`, idx))
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
		`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
		`<Default Extension="xml" ContentType="application/xml"/>` +
		func() string {
			if embeddedWorkbookCount > 0 {
				return `<Default Extension="xlsx" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>`
			}
			return ``
		}() +
		`<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>` +
		`<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>` +
		`<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>` +
		`<Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/>` +
		`<Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>` +
		`<Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>` +
		overrides.String() +
		`</Types>`
}

func officePPTXAppPropsXML(slides []officePPTXSlide) string {
	var parts strings.Builder
	for _, slide := range slides {
		parts.WriteString("<vt:lpstr>")
		parts.WriteString(officeXMLText(firstNonEmptyOfficeString(slide.Title, "Slide")))
		parts.WriteString("</vt:lpstr>")
	}
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>ZimaOS Blue</Application>
  <PresentationFormat>Custom</PresentationFormat>
  <Slides>%d</Slides>
  <Notes>0</Notes>
  <HiddenSlides>0</HiddenSlides>
  <MMClips>0</MMClips>
  <ScaleCrop>false</ScaleCrop>
  <HeadingPairs>
    <vt:vector size="2" baseType="variant">
      <vt:variant><vt:lpstr>Slides</vt:lpstr></vt:variant>
      <vt:variant><vt:i4>%d</vt:i4></vt:variant>
    </vt:vector>
  </HeadingPairs>
  <TitlesOfParts>
    <vt:vector size="%d" baseType="lpstr">%s</vt:vector>
  </TitlesOfParts>
</Properties>`, len(slides), len(slides), len(slides), parts.String())
}

func officePPTXPresentationXML(slideCount int) string {
	var slideIDs strings.Builder
	for idx := 1; idx <= slideCount; idx++ {
		slideIDs.WriteString(fmt.Sprintf(`<p:sldId id="%d" r:id="rId%d"/>`, 255+idx, idx+1))
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">` +
		`<p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst>` +
		`<p:sldIdLst>` + slideIDs.String() + `</p:sldIdLst>` +
		`<p:sldSz cx="12192000" cy="6858000"/>` +
		`<p:notesSz cx="6858000" cy="9144000"/>` +
		`</p:presentation>`
}

func officePPTXPresentationRelsXML(slideCount int) string {
	var rels strings.Builder
	rels.WriteString(`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>`)
	for idx := 1; idx <= slideCount; idx++ {
		rels.WriteString(fmt.Sprintf(`<Relationship Id="rId%d" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide%d.xml"/>`, idx+1, idx))
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		rels.String() +
		`</Relationships>`
}

func officePPTXSlideMasterXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">` +
		`<p:cSld name="Blue Master"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld>` +
		`<p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/>` +
		`<p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst>` +
		`</p:sldMaster>`
}

func officePPTXSlideMasterRelsXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>` +
		`<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/>` +
		`</Relationships>`
}

func officePPTXSlideLayoutXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank" preserve="1">` +
		`<p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`
}

func officePPTXSlideLayoutRelsXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>`
}

func officePPTXThemeXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Blue Theme">` +
		`<a:themeElements><a:clrScheme name="Blue"><a:dk1><a:srgbClr val="111827"/></a:dk1><a:lt1><a:srgbClr val="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="1F2937"/></a:dk2><a:lt2><a:srgbClr val="F3F4F6"/></a:lt2><a:accent1><a:srgbClr val="2563EB"/></a:accent1><a:accent2><a:srgbClr val="0F766E"/></a:accent2><a:accent3><a:srgbClr val="EA580C"/></a:accent3><a:accent4><a:srgbClr val="7C3AED"/></a:accent4><a:accent5><a:srgbClr val="DC2626"/></a:accent5><a:accent6><a:srgbClr val="059669"/></a:accent6><a:hlink><a:srgbClr val="2563EB"/></a:hlink><a:folHlink><a:srgbClr val="7C3AED"/></a:folHlink></a:clrScheme><a:fontScheme name="Blue"><a:majorFont><a:latin typeface="Aptos Display"/></a:majorFont><a:minorFont><a:latin typeface="Aptos"/></a:minorFont></a:fontScheme><a:fmtScheme name="Blue"><a:fillStyleLst><a:solidFill><a:schemeClr val="lt1"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="9525"><a:solidFill><a:schemeClr val="accent1"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle/></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="lt1"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements>` +
		`</a:theme>`
}

func officePPTXSlideXML(slide officePPTXSlide) string {
	var body strings.Builder
	for _, line := range slide.Lines {
		body.WriteString(`<a:p><a:r><a:rPr lang="en-US" sz="2200"/><a:t>`)
		body.WriteString(officeXMLText(line))
		body.WriteString(`</a:t></a:r></a:p>`)
	}
	if body.Len() == 0 {
		body.WriteString(`<a:p/>`)
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">` +
		`<p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>` +
		`<p:sp><p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" b="1" sz="2800"/><a:t>` + officeXMLText(firstNonEmptyOfficeString(slide.Title, "Slide")) + `</a:t></a:r></a:p></p:txBody></p:sp>` +
		`<p:sp><p:nvSpPr><p:cNvPr id="3" name="Content"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr wrap="square"/><a:lstStyle/>` + body.String() + `</p:txBody></p:sp>` +
		officePPTXChartGraphicFrameXML(slide.Chart, slide.chartRelID, len(slide.Lines) > 0, slide.Table != nil) +
		officePPTXTableGraphicFrameXML(slide.Table, len(slide.Lines) > 0, slide.Chart != nil) +
		`</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`
}

func officePPTXChartGraphicFrameXML(chart *officeChartSpec, relID string, hasBodyText bool, hasTable bool) string {
	if chart == nil {
		return ""
	}
	if relID == "" {
		relID = "rId2"
	}
	const (
		chartX         = 685800
		chartWidth     = 10858500
		chartHeight    = 3429000
		chartHeightFit = 2286000
		chartTopWith   = 2743200
		chartTopPlain  = 1600200
		defaultChartID = 4
	)
	chartY := chartTopPlain
	height := chartHeight
	if hasBodyText {
		chartY = chartTopWith
	}
	if hasTable {
		height = chartHeightFit
	}
	return fmt.Sprintf(
		`<p:graphicFrame><p:nvGraphicFramePr><p:cNvPr id="%d" name="Chart 1"/><p:cNvGraphicFramePr><a:graphicFrameLocks noGrp="1"/></p:cNvGraphicFramePr><p:nvPr/></p:nvGraphicFramePr><p:xfrm><a:off x="%d" y="%d"/><a:ext cx="%d" cy="%d"/></p:xfrm><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart r:id="%s"/></a:graphicData></a:graphic></p:graphicFrame>`,
		defaultChartID,
		chartX,
		chartY,
		chartWidth,
		height,
		officeXMLText(relID),
	)
}

func officePPTXTableGraphicFrameXML(table *officeTableSpec, hasBodyText bool, hasChart bool) string {
	if table == nil || officePPTXTableColumnCount(table) == 0 || officePPTXTableRowCount(table) == 0 {
		return ""
	}

	const (
		tableX            = 685800
		tableWidth        = 10858500
		tableTopWith      = 2743200
		tableTopPlain     = 1600200
		tableTopWithChart = 5257800
		rowHeight         = 370840
	)

	tableY := tableTopPlain
	if hasBodyText {
		tableY = tableTopWith
	}
	if hasChart {
		tableY = tableTopWithChart
	}
	rowCount := officePPTXTableRowCount(table)
	tableHeight := rowCount * rowHeight
	if tableHeight < rowHeight {
		tableHeight = rowHeight
	}

	return fmt.Sprintf(
		`<p:graphicFrame><p:nvGraphicFramePr><p:cNvPr id="%d" name="Table 1"/><p:cNvGraphicFramePr/><p:nvPr/></p:nvGraphicFramePr><p:xfrm><a:off x="%d" y="%d"/><a:ext cx="%d" cy="%d"/></p:xfrm><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/table">%s</a:graphicData></a:graphic></p:graphicFrame>`,
		5,
		tableX,
		tableY,
		tableWidth,
		tableHeight,
		officePPTXTableXML(table, tableWidth),
	)
}

func officePPTXChartXML(chart officeChartSpec) string {
	return officePPTXChartXMLWithWorkbook(officeNormalizePPTXChart(chart), nil)
}

func officePPTXChartXMLWithWorkbook(chart officeChartSpec, workbook *officePPTXChartWorkbookPackage) string {
	if chart.Type == "" || len(chart.Series) == 0 || len(chart.Categories) == 0 {
		return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart"/>`
	}
	mode := officePPTXChartModeForType(chart.Type)
	if mode.plotKind == "" {
		return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart"/>`
	}

	const (
		primaryCatAxisID   = 48650112
		primaryValAxisID   = 48672768
		secondaryCatAxisID = 48695392
		secondaryValAxisID = 48718016
	)
	includeSecondaryAxis := officePPTXChartHasSecondaryAxis(chart)

	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<c:chartSpace xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
		`<c:lang val="en-US"/>` +
		`<c:roundedCorners val="0"/>` +
		`<c:chart>` +
		officePPTXChartTitleXML(chart.Title) +
		`<c:autoTitleDeleted val="` + officePPTXBoolVal(chart.Title == "") + `"/>` +
		`<c:plotArea><c:layout/>` +
		officePPTXChartPlotXML(chart, mode, primaryCatAxisID, primaryValAxisID, secondaryCatAxisID, secondaryValAxisID, workbook) +
		officePPTXChartPrimaryCategoryAxisXML(mode, chart, primaryCatAxisID, primaryValAxisID) +
		officePPTXChartValueAxisXML(mode, chart.ValueAxisTitle, chart.ValueAxisFormat, chart.ValueAxisMin, chart.ValueAxisMax, chart.ValueAxisReverseOrder, chart.ValueAxisMajorUnit, chart.ValueAxisMinorUnit, chart.ValueAxisMajorGridlines, chart.ValueAxisMinorGridlines, chart.ValueAxisCrosses, chart.ValueAxisCrossBetween, chart.ValueAxisLabelPosition, chart.ValueAxisMajorTickMark, chart.ValueAxisMinorTickMark, primaryValAxisID, primaryCatAxisID) +
		officePPTXChartSecondaryRenderedCategoryAxisXML(mode, chart, secondaryCatAxisID, secondaryValAxisID, includeSecondaryAxis) +
		officePPTXChartSecondaryValueAxisXML(mode, chart.SecondaryValueAxisTitle, chart.SecondaryValueAxisFormat, chart.SecondaryValueAxisMin, chart.SecondaryValueAxisMax, chart.SecondaryValueAxisReverseOrder, chart.SecondaryValueAxisMajorUnit, chart.SecondaryValueAxisMinorUnit, chart.SecondaryValueAxisMajorGridlines, chart.SecondaryValueAxisMinorGridlines, chart.SecondaryValueAxisCrosses, chart.SecondaryValueAxisCrossBetween, chart.SecondaryValueAxisLabelPosition, chart.SecondaryValueAxisMajorTickMark, chart.SecondaryValueAxisMinorTickMark, secondaryValAxisID, secondaryCatAxisID, includeSecondaryAxis) +
		`</c:plotArea>` +
		officePPTXChartLegendXML(officePPTXChartShouldShowLegend(chart, mode), officePPTXChartLegendPosition(chart)) +
		`<c:plotVisOnly val="1"/><c:dispBlanksAs val="gap"/><c:showDLblsOverMax val="0"/>` +
		`</c:chart>` +
		officePPTXChartExternalDataXML(workbook) +
		`</c:chartSpace>`
}

func officeNormalizePPTXChart(chart officeChartSpec) officeChartSpec {
	chart.Type = officeNormalizeChartType(chart.Type)
	normalized := officeChartSpec{
		Type:                                  chart.Type,
		Title:                                 strings.TrimSpace(chart.Title),
		CategoryAxisTitle:                     strings.TrimSpace(chart.CategoryAxisTitle),
		SecondaryCategoryAxisTitle:            strings.TrimSpace(chart.SecondaryCategoryAxisTitle),
		CategoryAxisType:                      officeNormalizeChartCategoryAxisType(chart.CategoryAxisType),
		CategoryAxisLabelPosition:             officeNormalizeChartAxisLabelPosition(chart.CategoryAxisLabelPosition),
		SecondaryCategoryAxisLabelPosition:    officeNormalizeChartAxisLabelPosition(chart.SecondaryCategoryAxisLabelPosition),
		CategoryAxisReverseOrder:              officeNormalizeChartAxisReverseOrder(chart.CategoryAxisReverseOrder),
		SecondaryCategoryAxisReverseOrder:     officeNormalizeChartAxisReverseOrder(chart.SecondaryCategoryAxisReverseOrder),
		CategoryAxisCrosses:                   officeNormalizeChartAxisCrosses(chart.CategoryAxisCrosses),
		SecondaryCategoryAxisCrosses:          officeNormalizeChartAxisCrosses(chart.SecondaryCategoryAxisCrosses),
		CategoryAxisMajorTickMark:             officeNormalizeChartTickMark(chart.CategoryAxisMajorTickMark),
		CategoryAxisMinorTickMark:             officeNormalizeChartTickMark(chart.CategoryAxisMinorTickMark),
		SecondaryCategoryAxisMajorTickMark:    officeNormalizeChartTickMark(chart.SecondaryCategoryAxisMajorTickMark),
		SecondaryCategoryAxisMinorTickMark:    officeNormalizeChartTickMark(chart.SecondaryCategoryAxisMinorTickMark),
		CategoryAxisLabelAlignment:            officeNormalizeChartAxisLabelAlignment(chart.CategoryAxisLabelAlignment),
		SecondaryCategoryAxisLabelAlignment:   officeNormalizeChartAxisLabelAlignment(chart.SecondaryCategoryAxisLabelAlignment),
		CategoryAxisLabelOffset:               officeNormalizeChartAxisLabelOffset(chart.CategoryAxisLabelOffset),
		SecondaryCategoryAxisLabelOffset:      officeNormalizeChartAxisLabelOffset(chart.SecondaryCategoryAxisLabelOffset),
		CategoryAxisMultiLevelLabels:          officeNormalizeChartLabels(chart.CategoryAxisMultiLevelLabels),
		SecondaryCategoryAxisMultiLevelLabels: officeNormalizeChartLabels(chart.SecondaryCategoryAxisMultiLevelLabels),
		CategoryAxisVisible:                   officeNormalizeChartLabels(chart.CategoryAxisVisible),
		SecondaryCategoryAxisVisible:          officeNormalizeChartLabels(chart.SecondaryCategoryAxisVisible),
		CategoryAxisAuto:                      officeNormalizeChartLabels(chart.CategoryAxisAuto),
		SecondaryCategoryAxisAuto:             officeNormalizeChartLabels(chart.SecondaryCategoryAxisAuto),
		CategoryAxisFormat:                    officeNormalizeChartAxisFormat(chart.CategoryAxisFormat),
		SecondaryCategoryAxisFormat:           officeNormalizeChartAxisFormat(chart.SecondaryCategoryAxisFormat),
		CategoryAxisMin:                       officeNormalizeChartAxisBound(chart.CategoryAxisMin),
		CategoryAxisMax:                       officeNormalizeChartAxisBound(chart.CategoryAxisMax),
		CategoryAxisBaseTimeUnit:              officeNormalizeChartDateAxisTimeUnit(chart.CategoryAxisBaseTimeUnit),
		CategoryAxisMajorUnit:                 officeNormalizeChartAxisUnit(chart.CategoryAxisMajorUnit),
		CategoryAxisMinorUnit:                 officeNormalizeChartAxisUnit(chart.CategoryAxisMinorUnit),
		CategoryAxisMajorTimeUnit:             officeNormalizeChartDateAxisTimeUnit(chart.CategoryAxisMajorTimeUnit),
		CategoryAxisMinorTimeUnit:             officeNormalizeChartDateAxisTimeUnit(chart.CategoryAxisMinorTimeUnit),
		ValueAxisTitle:                        strings.TrimSpace(chart.ValueAxisTitle),
		SecondaryValueAxisTitle:               strings.TrimSpace(chart.SecondaryValueAxisTitle),
		ValueAxisFormat:                       officeNormalizeChartAxisFormat(chart.ValueAxisFormat),
		SecondaryValueAxisFormat:              officeNormalizeChartAxisFormat(chart.SecondaryValueAxisFormat),
		ValueAxisMin:                          officeNormalizeChartAxisBound(chart.ValueAxisMin),
		ValueAxisMax:                          officeNormalizeChartAxisBound(chart.ValueAxisMax),
		SecondaryValueAxisMin:                 officeNormalizeChartAxisBound(chart.SecondaryValueAxisMin),
		SecondaryValueAxisMax:                 officeNormalizeChartAxisBound(chart.SecondaryValueAxisMax),
		ValueAxisMajorUnit:                    officeNormalizeChartAxisUnit(chart.ValueAxisMajorUnit),
		ValueAxisMinorUnit:                    officeNormalizeChartAxisUnit(chart.ValueAxisMinorUnit),
		SecondaryValueAxisMajorUnit:           officeNormalizeChartAxisUnit(chart.SecondaryValueAxisMajorUnit),
		SecondaryValueAxisMinorUnit:           officeNormalizeChartAxisUnit(chart.SecondaryValueAxisMinorUnit),
		ValueAxisMajorGridlines:               officeNormalizeChartLabels(chart.ValueAxisMajorGridlines),
		ValueAxisMinorGridlines:               officeNormalizeChartLabels(chart.ValueAxisMinorGridlines),
		SecondaryValueAxisMajorGridlines:      officeNormalizeChartLabels(chart.SecondaryValueAxisMajorGridlines),
		SecondaryValueAxisMinorGridlines:      officeNormalizeChartLabels(chart.SecondaryValueAxisMinorGridlines),
		ValueAxisCrosses:                      officeNormalizeChartAxisCrosses(chart.ValueAxisCrosses),
		SecondaryValueAxisCrosses:             officeNormalizeChartAxisCrosses(chart.SecondaryValueAxisCrosses),
		ValueAxisCrossBetween:                 officeNormalizeChartAxisCrossBetween(chart.ValueAxisCrossBetween),
		SecondaryValueAxisCrossBetween:        officeNormalizeChartAxisCrossBetween(chart.SecondaryValueAxisCrossBetween),
		ValueAxisReverseOrder:                 officeNormalizeChartAxisReverseOrder(chart.ValueAxisReverseOrder),
		SecondaryValueAxisReverseOrder:        officeNormalizeChartAxisReverseOrder(chart.SecondaryValueAxisReverseOrder),
		ValueAxisLabelPosition:                officeNormalizeChartAxisLabelPosition(chart.ValueAxisLabelPosition),
		SecondaryValueAxisLabelPosition:       officeNormalizeChartAxisLabelPosition(chart.SecondaryValueAxisLabelPosition),
		ValueAxisMajorTickMark:                officeNormalizeChartTickMark(chart.ValueAxisMajorTickMark),
		ValueAxisMinorTickMark:                officeNormalizeChartTickMark(chart.ValueAxisMinorTickMark),
		SecondaryValueAxisMajorTickMark:       officeNormalizeChartTickMark(chart.SecondaryValueAxisMajorTickMark),
		SecondaryValueAxisMinorTickMark:       officeNormalizeChartTickMark(chart.SecondaryValueAxisMinorTickMark),
		ShowLegend:                            officeNormalizeChartLabels(chart.ShowLegend),
		LegendPosition:                        officeNormalizeChartLegendPosition(chart.LegendPosition),
		VaryColors:                            officeNormalizeChartLabels(chart.VaryColors),
		StartAngle:                            officeNormalizeChartStartAngle(chart.StartAngle),
		HoleSize:                              officeNormalizeChartHoleSize(chart.HoleSize),
		Smooth:                                officeNormalizeChartLabels(chart.Smooth),
		GapWidth:                              officeNormalizeChartGapWidth(chart.GapWidth),
		Overlap:                               officeNormalizeChartOverlap(chart.Overlap),
		Labels:                                officeNormalizeChartLabels(chart.Labels),
		LabelPosition:                         officeNormalizeChartLabelPosition(chart.LabelPosition),
		LabelFormat:                           officeNormalizeChartLabelFormat(chart.LabelFormat),
		ShowValue:                             officeNormalizeChartLabels(chart.ShowValue),
		ShowCategory:                          officeNormalizeChartLabels(chart.ShowCategory),
		ShowSeriesName:                        officeNormalizeChartLabels(chart.ShowSeriesName),
		ShowPercent:                           officeNormalizeChartLabels(chart.ShowPercent),
		ShowLegendKey:                         officeNormalizeChartLabels(chart.ShowLegendKey),
		ShowBubbleSize:                        officeNormalizeChartLabels(chart.ShowBubbleSize),
		Categories:                            append([]string(nil), chart.Categories...),
		Series:                                make([]officeChartSeries, 0, len(chart.Series)),
	}
	maxLen := len(normalized.Categories)
	for idx, series := range chart.Series {
		name := strings.TrimSpace(series.Name)
		if name == "" {
			name = fmt.Sprintf("Series %d", idx+1)
		}
		seriesType := officeNormalizeChartSeriesType(chart.Type, series.Type, idx)
		values := append([]float64(nil), series.Values...)
		if len(values) == 0 {
			continue
		}
		if len(values) > maxLen {
			maxLen = len(values)
		}
		normalized.Series = append(normalized.Series, officeChartSeries{
			Name:            name,
			WorkbookIndex:   idx,
			Type:            seriesType,
			Axis:            officeNormalizeChartSeriesAxis(chart.Type, seriesType, series.Axis),
			Labels:          officeNormalizeChartLabels(series.Labels),
			LabelPosition:   officeNormalizeChartLabelPosition(series.LabelPosition),
			LabelFormat:     officeNormalizeChartLabelFormat(series.LabelFormat),
			ShowValue:       officeNormalizeChartLabels(series.ShowValue),
			ShowCategory:    officeNormalizeChartLabels(series.ShowCategory),
			ShowSeriesName:  officeNormalizeChartLabels(series.ShowSeriesName),
			ShowPercent:     officeNormalizeChartLabels(series.ShowPercent),
			ShowLegendKey:   officeNormalizeChartLabels(series.ShowLegendKey),
			ShowBubbleSize:  officeNormalizeChartLabels(series.ShowBubbleSize),
			PointColors:     officeNormalizeChartPointColors(series.PointColors),
			PointExplosions: officeNormalizeChartPointExplosions(series.PointExplosions),
			Smooth:          officeNormalizeChartLabels(series.Smooth),
			Color:           officeNormalizeChartSeriesColor(series.Color),
			LineWidth:       officeNormalizeChartSeriesLineWidth(series.LineWidth),
			Dash:            officeNormalizeChartSeriesDash(series.Dash),
			Marker:          officeNormalizeChartSeriesMarker(series.Marker),
			Values:          values,
		})
	}
	for len(normalized.Categories) < maxLen {
		normalized.Categories = append(normalized.Categories, fmt.Sprintf("Category %d", len(normalized.Categories)+1))
	}
	for idx := range normalized.Series {
		for len(normalized.Series[idx].Values) < len(normalized.Categories) {
			normalized.Series[idx].Values = append(normalized.Series[idx].Values, 0)
		}
	}
	return normalized
}

func officePPTXChartHasSecondaryAxis(chart officeChartSpec) bool {
	if chart.Type != "combo" {
		return false
	}
	for _, series := range chart.Series {
		if series.Axis == "secondary" {
			return true
		}
	}
	return false
}

type officePPTXChartMode struct {
	plotKind      string
	barDir        string
	grouping      string
	includeAxes   bool
	includeInvert bool
	catAxisPos    string
	valAxisPos    string
	singleSeries  bool
	showLegend    bool
}

type officePPTXChartLabelConfig struct {
	Labels         string
	Position       string
	Format         string
	ShowValue      string
	ShowCategory   string
	ShowSeriesName string
	ShowPercent    string
	ShowLegendKey  string
	ShowBubbleSize string
}

type officePPTXDataLabelOptions struct {
	Show           bool
	Position       string
	Format         string
	ShowValue      bool
	ShowCategory   bool
	ShowSeriesName bool
	ShowPercent    bool
	ShowLegendKey  bool
	ShowBubbleSize bool
}

func officePPTXChartModeForType(chartType string) officePPTXChartMode {
	switch chartType {
	case "pie":
		return officePPTXChartMode{
			plotKind:      "pie",
			includeAxes:   false,
			includeInvert: false,
			singleSeries:  true,
			showLegend:    true,
		}
	case "donut":
		return officePPTXChartMode{
			plotKind:      "donut",
			includeAxes:   false,
			includeInvert: false,
			singleSeries:  true,
			showLegend:    true,
		}
	case "combo":
		return officePPTXChartMode{
			plotKind:      "combo",
			includeAxes:   true,
			includeInvert: true,
			catAxisPos:    "b",
			valAxisPos:    "l",
			showLegend:    true,
		}
	case "line":
		return officePPTXChartMode{
			plotKind:      "line",
			includeAxes:   true,
			includeInvert: false,
			catAxisPos:    "b",
			valAxisPos:    "l",
			showLegend:    false,
		}
	case "stacked_bar":
		return officePPTXChartMode{
			plotKind:      "bar",
			barDir:        "bar",
			grouping:      "stacked",
			includeAxes:   true,
			includeInvert: true,
			catAxisPos:    "l",
			valAxisPos:    "b",
			showLegend:    true,
		}
	case "percent_stacked_bar":
		return officePPTXChartMode{
			plotKind:      "bar",
			barDir:        "bar",
			grouping:      "percentStacked",
			includeAxes:   true,
			includeInvert: true,
			catAxisPos:    "l",
			valAxisPos:    "b",
			showLegend:    true,
		}
	case "stacked_column":
		return officePPTXChartMode{
			plotKind:      "bar",
			barDir:        "col",
			grouping:      "stacked",
			includeAxes:   true,
			includeInvert: true,
			catAxisPos:    "b",
			valAxisPos:    "l",
			showLegend:    true,
		}
	case "percent_stacked_column":
		return officePPTXChartMode{
			plotKind:      "bar",
			barDir:        "col",
			grouping:      "percentStacked",
			includeAxes:   true,
			includeInvert: true,
			catAxisPos:    "b",
			valAxisPos:    "l",
			showLegend:    true,
		}
	default:
		return officePPTXChartMode{
			plotKind:      "bar",
			barDir:        "col",
			grouping:      "clustered",
			includeAxes:   true,
			includeInvert: true,
			catAxisPos:    "b",
			valAxisPos:    "l",
			showLegend:    true,
		}
	}
}

func officePPTXChartPlotXML(chart officeChartSpec, mode officePPTXChartMode, primaryCatAxisID, primaryValAxisID, secondaryCatAxisID, secondaryValAxisID int, workbook *officePPTXChartWorkbookPackage) string {
	labelConfig := officePPTXChartLabelConfigFromChart(chart)
	switch mode.plotKind {
	case "pie":
		return `<c:pieChart><c:varyColors val="` + officePPTXBoolVal(officePPTXChartVaryColors(chart, true)) + `"/>` +
			officePPTXChartCircularSeriesXML(chart) +
			officePPTXChartDataLabelsXML("pie", labelConfig, chart.Series) +
			`<c:firstSliceAng val="` + strconv.Itoa(officePPTXChartStartAngle(chart)) + `"/></c:pieChart>`
	case "donut":
		return `<c:doughnutChart><c:varyColors val="` + officePPTXBoolVal(officePPTXChartVaryColors(chart, true)) + `"/>` +
			officePPTXChartCircularSeriesXML(chart) +
			officePPTXChartDataLabelsXML("donut", labelConfig, chart.Series) +
			`<c:firstSliceAng val="` + strconv.Itoa(officePPTXChartStartAngle(chart)) + `"/><c:holeSize val="` + strconv.Itoa(officePPTXChartHoleSize(chart)) + `"/></c:doughnutChart>`
	case "combo":
		return officePPTXComboChartPlotXML(chart, primaryCatAxisID, primaryValAxisID, secondaryCatAxisID, secondaryValAxisID, workbook)
	case "line":
		return officePPTXLineChartGroupXML("line", labelConfig, chart.Categories, chart.Series, chart.Smooth, officePPTXChartVaryColors(chart, false), chart.CategoryAxisType, chart.CategoryAxisFormat, primaryCatAxisID, primaryValAxisID, workbook)
	default:
		return officePPTXBarChartGroupXML(chart.Type, labelConfig, chart.Categories, chart.Series, chart.GapWidth, chart.Overlap, officePPTXChartVaryColors(chart, false), mode.barDir, mode.grouping, mode.includeInvert, chart.CategoryAxisType, chart.CategoryAxisFormat, primaryCatAxisID, primaryValAxisID, workbook)
	}
}

func officePPTXComboChartPlotXML(chart officeChartSpec, primaryCatAxisID, primaryValAxisID, secondaryCatAxisID, secondaryValAxisID int, workbook *officePPTXChartWorkbookPackage) string {
	labelConfig := officePPTXChartLabelConfigFromChart(chart)
	barPrimary := make([]officeChartSeries, 0, len(chart.Series))
	barSecondary := make([]officeChartSeries, 0, len(chart.Series))
	linePrimary := make([]officeChartSeries, 0, len(chart.Series))
	lineSecondary := make([]officeChartSeries, 0, len(chart.Series))
	for idx, series := range chart.Series {
		normalized := series
		normalized.Type = officeNormalizeChartSeriesType("combo", series.Type, idx)
		normalized.Axis = officeNormalizeChartSeriesAxis("combo", normalized.Type, series.Axis)
		switch normalized.Type {
		case "line":
			if normalized.Axis == "secondary" {
				lineSecondary = append(lineSecondary, normalized)
			} else {
				linePrimary = append(linePrimary, normalized)
			}
		default:
			if normalized.Axis == "secondary" {
				barSecondary = append(barSecondary, normalized)
			} else {
				barPrimary = append(barPrimary, normalized)
			}
		}
	}

	var plot strings.Builder
	plot.WriteString(officePPTXBarChartGroupXML("bar", labelConfig, chart.Categories, barPrimary, chart.GapWidth, chart.Overlap, officePPTXChartVaryColors(chart, false), "col", "clustered", true, chart.CategoryAxisType, chart.CategoryAxisFormat, primaryCatAxisID, primaryValAxisID, workbook))
	plot.WriteString(officePPTXLineChartGroupXML("line", labelConfig, chart.Categories, linePrimary, chart.Smooth, officePPTXChartVaryColors(chart, false), chart.CategoryAxisType, chart.CategoryAxisFormat, primaryCatAxisID, primaryValAxisID, workbook))
	plot.WriteString(officePPTXBarChartGroupXML("bar", labelConfig, chart.Categories, barSecondary, chart.GapWidth, chart.Overlap, officePPTXChartVaryColors(chart, false), "col", "clustered", true, chart.CategoryAxisType, chart.SecondaryCategoryAxisFormat, secondaryCatAxisID, secondaryValAxisID, workbook))
	plot.WriteString(officePPTXLineChartGroupXML("line", labelConfig, chart.Categories, lineSecondary, chart.Smooth, officePPTXChartVaryColors(chart, false), chart.CategoryAxisType, chart.SecondaryCategoryAxisFormat, secondaryCatAxisID, secondaryValAxisID, workbook))
	return plot.String()
}

func officePPTXBarChartGroupXML(chartType string, labelConfig officePPTXChartLabelConfig, categories []string, seriesList []officeChartSeries, gapWidth, overlap *int, varyColors bool, barDir, grouping string, includeInvert bool, categoryAxisType, categoryAxisFormat string, catAxisID, valAxisID int, workbook *officePPTXChartWorkbookPackage) string {
	if len(seriesList) == 0 {
		return ``
	}
	return `<c:barChart><c:barDir val="` + officeXMLText(barDir) + `"/><c:grouping val="` + officeXMLText(grouping) + `"/><c:varyColors val="` + officePPTXBoolVal(varyColors) + `"/>` +
		officePPTXChartSeriesListXML(categories, categoryAxisType, categoryAxisFormat, seriesList, includeInvert, "", workbook) +
		officePPTXChartDataLabelsXML(chartType, labelConfig, seriesList) +
		officePPTXChartBarLayoutXML(gapWidth, overlap) +
		fmt.Sprintf(`<c:axId val="%d"/><c:axId val="%d"/></c:barChart>`, catAxisID, valAxisID)
}

func officePPTXLineChartGroupXML(chartType string, labelConfig officePPTXChartLabelConfig, categories []string, seriesList []officeChartSeries, chartSmooth string, varyColors bool, categoryAxisType, categoryAxisFormat string, catAxisID, valAxisID int, workbook *officePPTXChartWorkbookPackage) string {
	if len(seriesList) == 0 {
		return ``
	}
	return `<c:lineChart><c:grouping val="standard"/><c:varyColors val="` + officePPTXBoolVal(varyColors) + `"/>` +
		officePPTXChartSeriesListXML(categories, categoryAxisType, categoryAxisFormat, seriesList, false, chartSmooth, workbook) +
		officePPTXChartDataLabelsXML(chartType, labelConfig, seriesList) +
		fmt.Sprintf(`<c:axId val="%d"/><c:axId val="%d"/></c:lineChart>`, catAxisID, valAxisID)
}

func officePPTXChartCircularSeriesXML(chart officeChartSpec) string {
	if len(chart.Series) == 0 {
		return ``
	}
	series := chart.Series[0]
	var seriesXML strings.Builder
	seriesXML.WriteString(`<c:ser>`)
	seriesXML.WriteString(`<c:idx val="0"/><c:order val="0"/>`)
	seriesXML.WriteString(`<c:tx><c:v>`)
	seriesXML.WriteString(officeXMLText(series.Name))
	seriesXML.WriteString(`</c:v></c:tx>`)
	seriesXML.WriteString(officePPTXChartSeriesStyleXML(series))
	seriesXML.WriteString(officePPTXChartDataPointStylesXML(series.PointColors, series.PointExplosions, true))
	seriesXML.WriteString(`<c:cat><c:strLit><c:ptCount val="`)
	seriesXML.WriteString(fmt.Sprintf("%d", len(chart.Categories)))
	seriesXML.WriteString(`"/>`)
	for catIndex, category := range chart.Categories {
		seriesXML.WriteString(fmt.Sprintf(`<c:pt idx="%d"><c:v>%s</c:v></c:pt>`, catIndex, officeXMLText(category)))
	}
	seriesXML.WriteString(`</c:strLit></c:cat>`)
	seriesXML.WriteString(`<c:val><c:numLit><c:formatCode>General</c:formatCode><c:ptCount val="`)
	seriesXML.WriteString(fmt.Sprintf("%d", len(series.Values)))
	seriesXML.WriteString(`"/>`)
	for valueIndex, value := range series.Values {
		seriesXML.WriteString(fmt.Sprintf(`<c:pt idx="%d"><c:v>%s</c:v></c:pt>`, valueIndex, officePPTXChartNumber(value)))
	}
	seriesXML.WriteString(`</c:numLit></c:val>`)
	seriesXML.WriteString(`</c:ser>`)
	return seriesXML.String()
}

func officePPTXChartSeriesXML(chart officeChartSpec, includeInvert bool) string {
	return officePPTXChartSeriesListXML(chart.Categories, chart.CategoryAxisType, chart.CategoryAxisFormat, chart.Series, includeInvert, chart.Smooth, nil)
}

func officePPTXChartCategoryDataXML(categories []string, categoryAxisType, categoryAxisFormat string, workbook *officePPTXChartWorkbookPackage) string {
	if workbook != nil && officePPTXChartUsesDateAxis(categoryAxisType) {
		return officePPTXChartDateCategoryRefXML(categories, categoryAxisFormat, officePPTXChartDateAxisIncludesTime(categoryAxisType), workbook)
	}
	if officePPTXChartUsesDateAxis(categoryAxisType) {
		return officePPTXChartDateCategoryDataXML(categories, categoryAxisFormat, officePPTXChartDateAxisIncludesTime(categoryAxisType))
	}
	return officePPTXChartStringCategoryDataXML(categories)
}

func officePPTXChartUsesDateAxis(categoryAxisType string) bool {
	switch officeNormalizeChartCategoryAxisType(categoryAxisType) {
	case "date", "datetime":
		return true
	default:
		return false
	}
}

func officePPTXChartDateAxisIncludesTime(categoryAxisType string) bool {
	return officeNormalizeChartCategoryAxisType(categoryAxisType) == "datetime"
}

func officePPTXChartStringCategoryDataXML(categories []string) string {
	var xml strings.Builder
	xml.WriteString(`<c:cat><c:strLit><c:ptCount val="`)
	xml.WriteString(fmt.Sprintf("%d", len(categories)))
	xml.WriteString(`"/>`)
	for catIndex, category := range categories {
		xml.WriteString(fmt.Sprintf(`<c:pt idx="%d"><c:v>%s</c:v></c:pt>`, catIndex, officeXMLText(category)))
	}
	xml.WriteString(`</c:strLit></c:cat>`)
	return xml.String()
}

func officePPTXChartDateCategoryDataXML(categories []string, format string, withTime bool) string {
	format = officePPTXChartDateAxisFormatCode(format, withTime)
	var xml strings.Builder
	xml.WriteString(`<c:cat><c:numLit><c:formatCode>`)
	xml.WriteString(officeXMLText(format))
	xml.WriteString(`</c:formatCode><c:ptCount val="`)
	xml.WriteString(fmt.Sprintf("%d", len(categories)))
	xml.WriteString(`"/>`)
	for catIndex, category := range categories {
		serial, ok := officeExcelDateSerial(category, withTime)
		if !ok {
			return officePPTXChartStringCategoryDataXML(categories)
		}
		xml.WriteString(fmt.Sprintf(`<c:pt idx="%d"><c:v>%s</c:v></c:pt>`, catIndex, serial))
	}
	xml.WriteString(`</c:numLit></c:cat>`)
	return xml.String()
}

func officePPTXChartDateCategoryRefXML(categories []string, format string, withTime bool, workbook *officePPTXChartWorkbookPackage) string {
	if workbook == nil {
		return officePPTXChartDateCategoryDataXML(categories, format, withTime)
	}
	format = officePPTXChartDateAxisFormatCode(format, withTime)
	var xml strings.Builder
	xml.WriteString(`<c:cat><c:numRef><c:f>`)
	xml.WriteString(officeXMLText(officePPTXChartWorkbookCategoryFormula(workbook, len(categories))))
	xml.WriteString(`</c:f><c:numCache><c:formatCode>`)
	xml.WriteString(officeXMLText(format))
	xml.WriteString(`</c:formatCode><c:ptCount val="`)
	xml.WriteString(fmt.Sprintf("%d", len(categories)))
	xml.WriteString(`"/>`)
	for catIndex, category := range categories {
		serial, ok := officeExcelDateSerial(category, withTime)
		if !ok {
			return officePPTXChartDateCategoryDataXML(categories, format, withTime)
		}
		xml.WriteString(fmt.Sprintf(`<c:pt idx="%d"><c:v>%s</c:v></c:pt>`, catIndex, serial))
	}
	xml.WriteString(`</c:numCache></c:numRef></c:cat>`)
	return xml.String()
}

func officePPTXChartSeriesListXML(categories []string, categoryAxisType, categoryAxisFormat string, seriesList []officeChartSeries, includeInvert bool, chartSmooth string, workbook *officePPTXChartWorkbookPackage) string {
	var seriesXML strings.Builder
	for idx, series := range seriesList {
		seriesXML.WriteString(`<c:ser>`)
		seriesXML.WriteString(fmt.Sprintf(`<c:idx val="%d"/><c:order val="%d"/>`, idx, idx))
		seriesXML.WriteString(`<c:tx><c:v>`)
		seriesXML.WriteString(officeXMLText(series.Name))
		seriesXML.WriteString(`</c:v></c:tx>`)
		seriesXML.WriteString(officePPTXChartSeriesStyleXML(series))
		if includeInvert {
			seriesXML.WriteString(`<c:invertIfNegative val="0"/>`)
		} else {
			seriesXML.WriteString(officePPTXChartMarkerXML(series))
		}
		seriesXML.WriteString(officePPTXChartDataPointStylesXML(series.PointColors, series.PointExplosions, false))
		seriesXML.WriteString(officePPTXChartCategoryDataXML(categories, categoryAxisType, categoryAxisFormat, workbook))
		workbookSeriesIndex := idx
		if workbook != nil {
			workbookSeriesIndex = series.WorkbookIndex
		}
		seriesXML.WriteString(officePPTXChartValueDataXML(series.Values, workbookSeriesIndex, workbook))
		if !includeInvert {
			seriesXML.WriteString(`<c:smooth val="` + officePPTXBoolVal(officePPTXChartSeriesSmooth(chartSmooth, series)) + `"/>`)
		}
		seriesXML.WriteString(`</c:ser>`)
	}
	return seriesXML.String()
}

func officePPTXChartValueDataXML(values []float64, seriesIndex int, workbook *officePPTXChartWorkbookPackage) string {
	var xml strings.Builder
	if workbook != nil {
		xml.WriteString(`<c:val><c:numRef><c:f>`)
		xml.WriteString(officeXMLText(officePPTXChartWorkbookSeriesFormula(workbook, seriesIndex, len(values))))
		xml.WriteString(`</c:f><c:numCache><c:formatCode>General</c:formatCode><c:ptCount val="`)
	} else {
		xml.WriteString(`<c:val><c:numLit><c:formatCode>General</c:formatCode><c:ptCount val="`)
	}
	xml.WriteString(fmt.Sprintf("%d", len(values)))
	xml.WriteString(`"/>`)
	for valueIndex, value := range values {
		xml.WriteString(fmt.Sprintf(`<c:pt idx="%d"><c:v>%s</c:v></c:pt>`, valueIndex, officePPTXChartNumber(value)))
	}
	if workbook != nil {
		xml.WriteString(`</c:numCache></c:numRef></c:val>`)
	} else {
		xml.WriteString(`</c:numLit></c:val>`)
	}
	return xml.String()
}

func officePPTXChartExternalDataXML(workbook *officePPTXChartWorkbookPackage) string {
	if workbook == nil || strings.TrimSpace(workbook.RelationshipID) == "" {
		return ``
	}
	return `<c:externalData r:id="` + officeXMLText(workbook.RelationshipID) + `"><c:autoUpdate val="0"/></c:externalData>`
}

func officePPTXChartRelsXML(workbook *officePPTXChartWorkbookPackage) string {
	if workbook == nil || strings.TrimSpace(workbook.RelationshipTarget) == "" {
		return ``
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		`<Relationship Id="` + officeXMLText(workbook.RelationshipID) + `" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/package" Target="` + officeXMLText(workbook.RelationshipTarget) + `"/>` +
		`</Relationships>`
}

func officePPTXChartWorkbookCategoryFormula(workbook *officePPTXChartWorkbookPackage, categoryCount int) string {
	return officePPTXChartWorkbookRangeFormula(workbook, 0, categoryCount)
}

func officePPTXChartWorkbookSeriesFormula(workbook *officePPTXChartWorkbookPackage, seriesIndex, valueCount int) string {
	return officePPTXChartWorkbookRangeFormula(workbook, seriesIndex+1, valueCount)
}

func officePPTXChartWorkbookRangeFormula(workbook *officePPTXChartWorkbookPackage, colIndex, valueCount int) string {
	if workbook == nil || valueCount <= 0 {
		return ""
	}
	column := officeXLSXColumnName(colIndex)
	sheetName := officePPTXChartWorkbookSheetRef(workbook.SheetName)
	return fmt.Sprintf("%s!$%s$2:$%s$%d", sheetName, column, column, valueCount+1)
}

func officePPTXChartWorkbookSheetRef(sheetName string) string {
	sheetName = strings.TrimSpace(sheetName)
	if sheetName == "" {
		return "Sheet1"
	}
	if strings.ContainsAny(sheetName, " '") {
		return "'" + strings.ReplaceAll(sheetName, "'", "''") + "'"
	}
	return sheetName
}

func officePPTXChartPrimaryCategoryAxisXML(mode officePPTXChartMode, chart officeChartSpec, catAxisID, valAxisID int) string {
	if officePPTXChartUsesDateAxis(chart.CategoryAxisType) {
		return officePPTXChartDateAxisXML(mode, chart.CategoryAxisTitle, chart.CategoryAxisFormat, officePPTXChartDateAxisIncludesTime(chart.CategoryAxisType), chart.CategoryAxisMin, chart.CategoryAxisMax, chart.CategoryAxisBaseTimeUnit, chart.CategoryAxisMajorUnit, chart.CategoryAxisMinorUnit, chart.CategoryAxisMajorTimeUnit, chart.CategoryAxisMinorTimeUnit, chart.CategoryAxisLabelPosition, chart.CategoryAxisReverseOrder, chart.CategoryAxisCrosses, chart.CategoryAxisMajorTickMark, chart.CategoryAxisMinorTickMark, chart.CategoryAxisLabelOffset, chart.CategoryAxisVisible, chart.CategoryAxisAuto, catAxisID, valAxisID)
	}
	return officePPTXChartCategoryAxisXML(mode, chart.CategoryAxisTitle, chart.CategoryAxisFormat, chart.CategoryAxisLabelPosition, chart.CategoryAxisReverseOrder, chart.CategoryAxisCrosses, chart.CategoryAxisMajorTickMark, chart.CategoryAxisMinorTickMark, chart.CategoryAxisLabelAlignment, chart.CategoryAxisLabelOffset, chart.CategoryAxisMultiLevelLabels, chart.CategoryAxisVisible, chart.CategoryAxisAuto, catAxisID, valAxisID)
}

func officePPTXChartSecondaryRenderedCategoryAxisXML(mode officePPTXChartMode, chart officeChartSpec, catAxisID, valAxisID int, include bool) string {
	if officePPTXChartUsesDateAxis(chart.CategoryAxisType) {
		return officePPTXChartSecondaryDateAxisXML(mode, chart.SecondaryCategoryAxisTitle, chart.SecondaryCategoryAxisFormat, officePPTXChartDateAxisIncludesTime(chart.CategoryAxisType), chart.CategoryAxisMin, chart.CategoryAxisMax, chart.CategoryAxisBaseTimeUnit, chart.CategoryAxisMajorUnit, chart.CategoryAxisMinorUnit, chart.CategoryAxisMajorTimeUnit, chart.CategoryAxisMinorTimeUnit, chart.SecondaryCategoryAxisLabelPosition, chart.SecondaryCategoryAxisReverseOrder, chart.SecondaryCategoryAxisCrosses, chart.SecondaryCategoryAxisMajorTickMark, chart.SecondaryCategoryAxisMinorTickMark, chart.SecondaryCategoryAxisLabelOffset, chart.SecondaryCategoryAxisVisible, chart.SecondaryCategoryAxisAuto, catAxisID, valAxisID, include)
	}
	return officePPTXChartSecondaryCategoryAxisXML(mode, chart.SecondaryCategoryAxisTitle, chart.SecondaryCategoryAxisFormat, chart.SecondaryCategoryAxisLabelPosition, chart.SecondaryCategoryAxisReverseOrder, chart.SecondaryCategoryAxisCrosses, chart.SecondaryCategoryAxisMajorTickMark, chart.SecondaryCategoryAxisMinorTickMark, chart.SecondaryCategoryAxisLabelAlignment, chart.SecondaryCategoryAxisLabelOffset, chart.SecondaryCategoryAxisMultiLevelLabels, chart.SecondaryCategoryAxisVisible, chart.SecondaryCategoryAxisAuto, catAxisID, valAxisID, include)
}

func officePPTXChartSeriesStyleXML(series officeChartSeries) string {
	if series.Color == "" && series.LineWidth == 0 && series.Dash == "" {
		return ``
	}
	var style strings.Builder
	style.WriteString(`<c:spPr>`)
	if series.Color != "" {
		color := officeXMLText(series.Color)
		style.WriteString(`<a:solidFill><a:srgbClr val="` + color + `"/></a:solidFill>`)
	}
	if series.Color != "" || series.LineWidth > 0 || series.Dash != "" {
		lineWidth := officePPTXChartLineWidth(series.LineWidth)
		style.WriteString(fmt.Sprintf(`<a:ln w="%d">`, lineWidth))
		if series.Color != "" {
			color := officeXMLText(series.Color)
			style.WriteString(`<a:solidFill><a:srgbClr val="` + color + `"/></a:solidFill>`)
		}
		if series.Dash != "" {
			style.WriteString(`<a:prstDash val="` + officeXMLText(series.Dash) + `"/>`)
		}
		style.WriteString(`</a:ln>`)
	}
	style.WriteString(`</c:spPr>`)
	return style.String()
}

func officePPTXChartDataPointStylesXML(pointColors []string, pointExplosions []int, allowExplosion bool) string {
	pointCount := len(pointColors)
	if len(pointExplosions) > pointCount {
		pointCount = len(pointExplosions)
	}
	if pointCount == 0 {
		return ``
	}
	var xml strings.Builder
	for idx := 0; idx < pointCount; idx++ {
		color := ``
		if idx < len(pointColors) {
			color = pointColors[idx]
		}
		explosion := 0
		if allowExplosion && idx < len(pointExplosions) {
			explosion = pointExplosions[idx]
		}
		if color == "" && explosion <= 0 {
			continue
		}
		xml.WriteString(`<c:dPt><c:idx val="`)
		xml.WriteString(fmt.Sprintf("%d", idx))
		xml.WriteString(`"/>`)
		if explosion > 0 {
			xml.WriteString(`<c:explosion val="`)
			xml.WriteString(fmt.Sprintf("%d", explosion))
			xml.WriteString(`"/>`)
		}
		xml.WriteString(officePPTXChartPointStyleXML(color))
		xml.WriteString(`</c:dPt>`)
	}
	return xml.String()
}

func officePPTXChartPointStyleXML(color string) string {
	if color == "" {
		return ``
	}
	color = officeXMLText(color)
	return `<c:spPr><a:solidFill><a:srgbClr val="` + color + `"/></a:solidFill><a:ln><a:solidFill><a:srgbClr val="` + color + `"/></a:solidFill></a:ln></c:spPr>`
}

func officePPTXChartMarkerXML(series officeChartSeries) string {
	marker := series.Marker
	if marker == "" {
		marker = "circle"
	}
	return `<c:marker><c:symbol val="` + officeXMLText(marker) + `"/></c:marker>`
}

func officePPTXChartLineWidth(width float64) int {
	if width <= 0 {
		return 28575
	}
	return int(math.Round(width * 12700))
}

func officePPTXChartLabelConfigFromChart(chart officeChartSpec) officePPTXChartLabelConfig {
	return officePPTXChartLabelConfig{
		Labels:         chart.Labels,
		Position:       chart.LabelPosition,
		Format:         chart.LabelFormat,
		ShowValue:      chart.ShowValue,
		ShowCategory:   chart.ShowCategory,
		ShowSeriesName: chart.ShowSeriesName,
		ShowPercent:    chart.ShowPercent,
		ShowLegendKey:  chart.ShowLegendKey,
		ShowBubbleSize: chart.ShowBubbleSize,
	}
}

func officePPTXChartDataLabelsXML(chartType string, labelConfig officePPTXChartLabelConfig, seriesList []officeChartSeries) string {
	options := officePPTXChartDataLabelOptions(chartType, labelConfig, seriesList)
	if !options.Show {
		return ``
	}
	var labels strings.Builder
	labels.WriteString(`<c:dLbls>`)
	if options.Format != "" {
		labels.WriteString(`<c:numFmt formatCode="` + officeXMLText(options.Format) + `" sourceLinked="0"/>`)
	}
	if options.Position != "" {
		labels.WriteString(`<c:dLblPos val="` + officeXMLText(options.Position) + `"/>`)
	}
	labels.WriteString(
		`<c:showLegendKey val="` + officePPTXBoolVal(options.ShowLegendKey) + `"/>` +
			`<c:showVal val="` + officePPTXBoolVal(options.ShowValue) + `"/>` +
			`<c:showCatName val="` + officePPTXBoolVal(options.ShowCategory) + `"/>` +
			`<c:showSerName val="` + officePPTXBoolVal(options.ShowSeriesName) + `"/>` +
			`<c:showPercent val="` + officePPTXBoolVal(options.ShowPercent) + `"/>` +
			`<c:showBubbleSize val="` + officePPTXBoolVal(options.ShowBubbleSize) + `"/>`,
	)
	labels.WriteString(`</c:dLbls>`)
	return labels.String()
}

func officePPTXChartShowsDataLabels(chartLabels string, seriesList []officeChartSeries) bool {
	if chartLabels == "show" {
		return true
	}
	for _, series := range seriesList {
		if series.Labels == "show" {
			return true
		}
	}
	return false
}

func officePPTXChartDataLabelOptions(chartType string, labelConfig officePPTXChartLabelConfig, seriesList []officeChartSeries) officePPTXDataLabelOptions {
	show := officePPTXChartShowsDataLabels(labelConfig.Labels, seriesList)
	if !show {
		return officePPTXDataLabelOptions{}
	}
	options := officePPTXDataLabelOptions{
		Show:           true,
		Position:       labelConfig.Position,
		Format:         labelConfig.Format,
		ShowValue:      true,
		ShowCategory:   chartType == "pie" || chartType == "donut",
		ShowSeriesName: false,
		ShowPercent:    false,
		ShowLegendKey:  false,
		ShowBubbleSize: false,
	}
	if labelConfig.ShowValue != "" {
		options.ShowValue = labelConfig.ShowValue == "show"
	}
	if labelConfig.ShowCategory != "" {
		options.ShowCategory = labelConfig.ShowCategory == "show"
	}
	if labelConfig.ShowSeriesName != "" {
		options.ShowSeriesName = labelConfig.ShowSeriesName == "show"
	}
	if labelConfig.ShowPercent != "" {
		options.ShowPercent = labelConfig.ShowPercent == "show"
	}
	if labelConfig.ShowLegendKey != "" {
		options.ShowLegendKey = labelConfig.ShowLegendKey == "show"
	}
	if labelConfig.ShowBubbleSize != "" {
		options.ShowBubbleSize = labelConfig.ShowBubbleSize == "show"
	}
	for _, series := range seriesList {
		if labelConfig.Labels != "show" && series.Labels != "show" {
			continue
		}
		if series.LabelPosition != "" {
			options.Position = series.LabelPosition
		}
		if series.LabelFormat != "" {
			options.Format = series.LabelFormat
		}
		if series.ShowValue != "" {
			options.ShowValue = series.ShowValue == "show"
		}
		if series.ShowCategory != "" {
			options.ShowCategory = series.ShowCategory == "show"
		}
		if series.ShowSeriesName != "" {
			options.ShowSeriesName = series.ShowSeriesName == "show"
		}
		if series.ShowPercent != "" {
			options.ShowPercent = series.ShowPercent == "show"
		}
		if series.ShowLegendKey != "" {
			options.ShowLegendKey = series.ShowLegendKey == "show"
		}
		if series.ShowBubbleSize != "" {
			options.ShowBubbleSize = series.ShowBubbleSize == "show"
		}
	}
	return options
}

func officePPTXChartCategoryAxisXML(mode officePPTXChartMode, title, format, labelPosition, reverseOrder, crosses, majorTickMark, minorTickMark, labelAlignment string, labelOffset *int, multiLevelLabels, visible, auto string, catAxisID, valAxisID int) string {
	if !mode.includeAxes {
		return ``
	}
	axPos := firstNonEmptyOfficeString(mode.catAxisPos, "b")
	return fmt.Sprintf(`<c:catAx><c:axId val="%d"/><c:scaling><c:orientation val="%s"/></c:scaling>%s<c:axPos val="%s"/>%s%s%s%s<c:crossAx val="%d"/>%s%s%s%s</c:catAx>`, catAxisID, officeXMLText(officePPTXChartValueAxisOrientation(reverseOrder)), officePPTXChartAxisDeleteXML(visible, true), officeXMLText(axPos), officePPTXChartTitleXML(title), officePPTXChartValueAxisFormatXML(format), officePPTXChartAxisTicksXML(majorTickMark, minorTickMark, "out", "none"), officePPTXChartAxisLabelPositionXML(labelPosition, "nextTo"), valAxisID, officePPTXChartValueAxisCrossesXML(crosses, "autoZero"), officePPTXChartAxisAutoXML(auto, true), officePPTXChartCategoryAxisLabelLayoutXML(labelAlignment, labelOffset), officePPTXChartCategoryAxisMultiLevelLabelsXML(multiLevelLabels))
}

func officePPTXChartDateAxisXML(mode officePPTXChartMode, title, format string, withTime bool, minValue, maxValue *float64, baseTimeUnit string, majorUnit, minorUnit *float64, majorTimeUnit, minorTimeUnit, labelPosition, reverseOrder, crosses, majorTickMark, minorTickMark string, labelOffset *int, visible, auto string, catAxisID, valAxisID int) string {
	if !mode.includeAxes {
		return ``
	}
	axPos := firstNonEmptyOfficeString(mode.catAxisPos, "b")
	return fmt.Sprintf(`<c:dateAx><c:axId val="%d"/>%s%s<c:axPos val="%s"/>%s%s%s%s<c:crossAx val="%d"/>%s%s%s%s%s%s%s</c:dateAx>`, catAxisID, officePPTXChartValueAxisScalingXML(minValue, maxValue, reverseOrder), officePPTXChartAxisDeleteXML(visible, true), officeXMLText(axPos), officePPTXChartTitleXML(title), officePPTXChartDateAxisFormatXML(format, withTime), officePPTXChartAxisTicksXML(majorTickMark, minorTickMark, "out", "none"), officePPTXChartAxisLabelPositionXML(labelPosition, "nextTo"), valAxisID, officePPTXChartValueAxisCrossesXML(crosses, "autoZero"), officePPTXChartAxisAutoXML(auto, true), officePPTXChartDateAxisLabelOffsetXML(labelOffset), officePPTXChartDateAxisBaseTimeUnitXML(baseTimeUnit), officePPTXChartValueAxisUnitsXML(majorUnit, minorUnit), officePPTXChartDateAxisOptionalTimeUnitXML("majorTimeUnit", majorTimeUnit), officePPTXChartDateAxisOptionalTimeUnitXML("minorTimeUnit", minorTimeUnit))
}

func officePPTXChartValueAxisXML(mode officePPTXChartMode, title, format string, minValue, maxValue *float64, reverseOrder string, majorUnit, minorUnit *float64, majorGridlines, minorGridlines, crosses, crossBetween, labelPosition, majorTickMark, minorTickMark string, valAxisID, catAxisID int) string {
	if !mode.includeAxes {
		return ``
	}
	axPos := firstNonEmptyOfficeString(mode.valAxisPos, "l")
	return fmt.Sprintf(`<c:valAx><c:axId val="%d"/>%s<c:delete val="0"/><c:axPos val="%s"/>%s%s%s%s%s%s<c:crossAx val="%d"/>%s%s</c:valAx>`, valAxisID, officePPTXChartValueAxisScalingXML(minValue, maxValue, reverseOrder), officeXMLText(axPos), officePPTXChartTitleXML(title), officePPTXChartValueAxisGridlinesXML(majorGridlines, minorGridlines, true), officePPTXChartValueAxisFormatXML(format), officePPTXChartValueAxisUnitsXML(majorUnit, minorUnit), officePPTXChartValueAxisTicksXML(majorTickMark, minorTickMark), officePPTXChartValueAxisLabelPositionXML(labelPosition), catAxisID, officePPTXChartValueAxisCrossesXML(crosses, "autoZero"), officePPTXChartValueAxisCrossBetweenXML(crossBetween))
}

func officePPTXChartSecondaryCategoryAxisXML(mode officePPTXChartMode, title, format, labelPosition, reverseOrder, crosses, majorTickMark, minorTickMark, labelAlignment string, labelOffset *int, multiLevelLabels, visible, auto string, catAxisID, valAxisID int, include bool) string {
	if !mode.includeAxes || !include {
		return ``
	}
	return fmt.Sprintf(`<c:catAx><c:axId val="%d"/><c:scaling><c:orientation val="%s"/></c:scaling>%s<c:axPos val="t"/>%s%s%s%s<c:crossAx val="%d"/>%s%s%s%s</c:catAx>`, catAxisID, officeXMLText(officePPTXChartValueAxisOrientation(reverseOrder)), officePPTXChartAxisDeleteXML(visible, false), officePPTXChartTitleXML(title), officePPTXChartValueAxisFormatXML(format), officePPTXChartAxisTicksXML(majorTickMark, minorTickMark, "none", "none"), officePPTXChartAxisLabelPositionXML(labelPosition, "none"), valAxisID, officePPTXChartValueAxisCrossesXML(crosses, "max"), officePPTXChartAxisAutoXML(auto, true), officePPTXChartCategoryAxisLabelLayoutXML(labelAlignment, labelOffset), officePPTXChartCategoryAxisMultiLevelLabelsXML(multiLevelLabels))
}

func officePPTXChartSecondaryDateAxisXML(mode officePPTXChartMode, title, format string, withTime bool, minValue, maxValue *float64, baseTimeUnit string, majorUnit, minorUnit *float64, majorTimeUnit, minorTimeUnit, labelPosition, reverseOrder, crosses, majorTickMark, minorTickMark string, labelOffset *int, visible, auto string, catAxisID, valAxisID int, include bool) string {
	if !mode.includeAxes || !include {
		return ``
	}
	return fmt.Sprintf(`<c:dateAx><c:axId val="%d"/>%s%s<c:axPos val="t"/>%s%s%s%s<c:crossAx val="%d"/>%s%s%s%s%s%s%s</c:dateAx>`, catAxisID, officePPTXChartValueAxisScalingXML(minValue, maxValue, reverseOrder), officePPTXChartAxisDeleteXML(visible, false), officePPTXChartTitleXML(title), officePPTXChartDateAxisFormatXML(format, withTime), officePPTXChartAxisTicksXML(majorTickMark, minorTickMark, "none", "none"), officePPTXChartAxisLabelPositionXML(labelPosition, "none"), valAxisID, officePPTXChartValueAxisCrossesXML(crosses, "max"), officePPTXChartAxisAutoXML(auto, true), officePPTXChartDateAxisLabelOffsetXML(labelOffset), officePPTXChartDateAxisBaseTimeUnitXML(baseTimeUnit), officePPTXChartValueAxisUnitsXML(majorUnit, minorUnit), officePPTXChartDateAxisOptionalTimeUnitXML("majorTimeUnit", majorTimeUnit), officePPTXChartDateAxisOptionalTimeUnitXML("minorTimeUnit", minorTimeUnit))
}

func officePPTXChartSecondaryValueAxisXML(mode officePPTXChartMode, title, format string, minValue, maxValue *float64, reverseOrder string, majorUnit, minorUnit *float64, majorGridlines, minorGridlines, crosses, crossBetween, labelPosition, majorTickMark, minorTickMark string, valAxisID, catAxisID int, include bool) string {
	if !mode.includeAxes || !include {
		return ``
	}
	return fmt.Sprintf(`<c:valAx><c:axId val="%d"/>%s<c:delete val="0"/><c:axPos val="r"/>%s%s%s%s%s%s<c:crossAx val="%d"/>%s%s</c:valAx>`, valAxisID, officePPTXChartValueAxisScalingXML(minValue, maxValue, reverseOrder), officePPTXChartTitleXML(title), officePPTXChartValueAxisGridlinesXML(majorGridlines, minorGridlines, false), officePPTXChartValueAxisFormatXML(format), officePPTXChartValueAxisUnitsXML(majorUnit, minorUnit), officePPTXChartValueAxisTicksXML(majorTickMark, minorTickMark), officePPTXChartValueAxisLabelPositionXML(labelPosition), catAxisID, officePPTXChartValueAxisCrossesXML(crosses, "max"), officePPTXChartValueAxisCrossBetweenXML(crossBetween))
}

func officePPTXChartValueAxisFormatXML(format string) string {
	format = officeNormalizeChartAxisFormat(format)
	if format == "" {
		return `<c:numFmt formatCode="General" sourceLinked="1"/>`
	}
	return `<c:numFmt formatCode="` + officeXMLText(format) + `" sourceLinked="0"/>`
}

func officePPTXChartDateAxisFormatCode(format string, withTime bool) string {
	format = officeNormalizeChartAxisFormat(format)
	if format == "" {
		if withTime {
			return "yyyy-mm-dd hh:mm"
		}
		return "yyyy-mm-dd"
	}
	return format
}

func officePPTXChartDateAxisFormatXML(format string, withTime bool) string {
	format = officePPTXChartDateAxisFormatCode(format, withTime)
	return `<c:numFmt formatCode="` + officeXMLText(format) + `" sourceLinked="0"/>`
}

func officePPTXChartDateAxisBaseTimeUnitXML(baseTimeUnit string) string {
	return `<c:baseTimeUnit val="` + officeXMLText(firstNonEmptyOfficeString(officeNormalizeChartDateAxisTimeUnit(baseTimeUnit), "days")) + `"/>`
}

func officePPTXChartDateAxisOptionalTimeUnitXML(tagName, timeUnit string) string {
	timeUnit = officeNormalizeChartDateAxisTimeUnit(timeUnit)
	if timeUnit == "" {
		return ``
	}
	return `<c:` + officeXMLText(tagName) + ` val="` + officeXMLText(timeUnit) + `"/>`
}

func officePPTXChartValueAxisScalingXML(minValue, maxValue *float64, reverseOrder string) string {
	var xml strings.Builder
	xml.WriteString(`<c:scaling><c:orientation val="`)
	xml.WriteString(officeXMLText(officePPTXChartValueAxisOrientation(reverseOrder)))
	xml.WriteString(`"/>`)
	if minValue != nil {
		xml.WriteString(`<c:min val="`)
		xml.WriteString(officePPTXChartNumber(*minValue))
		xml.WriteString(`"/>`)
	}
	if maxValue != nil {
		xml.WriteString(`<c:max val="`)
		xml.WriteString(officePPTXChartNumber(*maxValue))
		xml.WriteString(`"/>`)
	}
	xml.WriteString(`</c:scaling>`)
	return xml.String()
}

func officePPTXChartValueAxisOrientation(reverseOrder string) string {
	reverseOrder = officeNormalizeChartAxisReverseOrder(reverseOrder)
	if reverseOrder == "" {
		return "minMax"
	}
	return reverseOrder
}

func officePPTXChartValueAxisUnitsXML(majorUnit, minorUnit *float64) string {
	var xml strings.Builder
	if majorUnit != nil {
		xml.WriteString(`<c:majorUnit val="`)
		xml.WriteString(officePPTXChartNumber(*majorUnit))
		xml.WriteString(`"/>`)
	}
	if minorUnit != nil {
		xml.WriteString(`<c:minorUnit val="`)
		xml.WriteString(officePPTXChartNumber(*minorUnit))
		xml.WriteString(`"/>`)
	}
	return xml.String()
}

func officePPTXChartValueAxisGridlinesXML(majorSetting, minorSetting string, defaultMajor bool) string {
	var xml strings.Builder
	switch majorSetting {
	case "show":
		xml.WriteString(`<c:majorGridlines/>`)
	case "hide":
	default:
		if defaultMajor {
			xml.WriteString(`<c:majorGridlines/>`)
		}
	}
	if officeNormalizeChartLabels(minorSetting) == "show" {
		xml.WriteString(`<c:minorGridlines/>`)
	}
	return xml.String()
}

func officePPTXChartAxisTicksXML(majorTickMark, minorTickMark, defaultMajorTickMark, defaultMinorTickMark string) string {
	majorTickMark = officeNormalizeChartTickMark(majorTickMark)
	if majorTickMark == "" {
		majorTickMark = defaultMajorTickMark
	}
	minorTickMark = officeNormalizeChartTickMark(minorTickMark)
	if minorTickMark == "" {
		minorTickMark = defaultMinorTickMark
	}
	return `<c:majorTickMark val="` + officeXMLText(majorTickMark) + `"/><c:minorTickMark val="` + officeXMLText(minorTickMark) + `"/>`
}

func officePPTXChartValueAxisTicksXML(majorTickMark, minorTickMark string) string {
	return officePPTXChartAxisTicksXML(majorTickMark, minorTickMark, "out", "none")
}

func officePPTXChartAxisLabelPositionXML(position, defaultValue string) string {
	position = officeNormalizeChartAxisLabelPosition(position)
	if position == "" {
		position = defaultValue
	}
	return `<c:tickLblPos val="` + officeXMLText(position) + `"/>`
}

func officePPTXChartValueAxisLabelPositionXML(position string) string {
	return officePPTXChartAxisLabelPositionXML(position, "nextTo")
}

func officePPTXChartCategoryAxisLabelLayoutXML(alignment string, offset *int) string {
	alignment = officeNormalizeChartAxisLabelAlignment(alignment)
	if alignment == "" {
		alignment = "ctr"
	}
	offset = officeNormalizeChartAxisLabelOffset(offset)
	if offset == nil {
		defaultOffset := 100
		offset = &defaultOffset
	}
	return `<c:lblAlgn val="` + officeXMLText(alignment) + `"/><c:lblOffset val="` + strconv.Itoa(*offset) + `"/>`
}

func officePPTXChartDateAxisLabelOffsetXML(offset *int) string {
	offset = officeNormalizeChartAxisLabelOffset(offset)
	if offset == nil {
		defaultOffset := 100
		offset = &defaultOffset
	}
	return `<c:lblOffset val="` + strconv.Itoa(*offset) + `"/>`
}

func officePPTXChartCategoryAxisMultiLevelLabelsXML(setting string) string {
	switch officeNormalizeChartLabels(setting) {
	case "hide":
		return `<c:noMultiLvlLbl val="1"/>`
	default:
		return `<c:noMultiLvlLbl val="0"/>`
	}
}

func officePPTXChartAxisDeleteXML(visible string, defaultVisible bool) string {
	switch officeNormalizeChartLabels(visible) {
	case "show":
		return `<c:delete val="0"/>`
	case "hide":
		return `<c:delete val="1"/>`
	default:
		if defaultVisible {
			return `<c:delete val="0"/>`
		}
		return `<c:delete val="1"/>`
	}
}

func officePPTXChartAxisAutoXML(auto string, defaultAuto bool) string {
	switch officeNormalizeChartLabels(auto) {
	case "show":
		return `<c:auto val="1"/>`
	case "hide":
		return `<c:auto val="0"/>`
	default:
		return `<c:auto val="` + officePPTXBoolVal(defaultAuto) + `"/>`
	}
}

func officePPTXChartValueAxisCrossesXML(crosses, defaultValue string) string {
	crosses = officeNormalizeChartAxisCrosses(crosses)
	if crosses == "" {
		crosses = defaultValue
	}
	return `<c:crosses val="` + officeXMLText(crosses) + `"/>`
}

func officePPTXChartValueAxisCrossBetweenXML(crossBetween string) string {
	crossBetween = officeNormalizeChartAxisCrossBetween(crossBetween)
	if crossBetween == "" {
		crossBetween = "between"
	}
	return `<c:crossBetween val="` + officeXMLText(crossBetween) + `"/>`
}

func officePPTXChartLegendXML(show bool, position string) string {
	if !show {
		return ``
	}
	if position == "" {
		position = "r"
	}
	return `<c:legend><c:legendPos val="` + officeXMLText(position) + `"/><c:layout/></c:legend>`
}

func officePPTXChartShouldShowLegend(chart officeChartSpec, mode officePPTXChartMode) bool {
	if chart.ShowLegend != "" {
		return chart.ShowLegend == "show"
	}
	if mode.showLegend {
		if mode.singleSeries {
			return len(chart.Categories) > 1
		}
		return len(chart.Series) > 0
	}
	return len(chart.Series) > 1
}

func officePPTXChartLegendPosition(chart officeChartSpec) string {
	return officeNormalizeChartLegendPosition(chart.LegendPosition)
}

func officePPTXChartVaryColors(chart officeChartSpec, defaultValue bool) bool {
	if chart.VaryColors != "" {
		return chart.VaryColors == "show"
	}
	return defaultValue
}

func officePPTXChartStartAngle(chart officeChartSpec) int {
	return officeNormalizeChartStartAngle(chart.StartAngle)
}

func officePPTXChartHoleSize(chart officeChartSpec) int {
	holeSize := officeNormalizeChartHoleSize(chart.HoleSize)
	if holeSize == 0 {
		return 50
	}
	return holeSize
}

func officePPTXChartSeriesSmooth(chartSmooth string, series officeChartSeries) bool {
	if series.Smooth != "" {
		return series.Smooth == "show"
	}
	return chartSmooth == "show"
}

func officePPTXChartBarLayoutXML(gapWidth, overlap *int) string {
	var xml strings.Builder
	if gapWidth != nil {
		xml.WriteString(`<c:gapWidth val="`)
		xml.WriteString(strconv.Itoa(*gapWidth))
		xml.WriteString(`"/>`)
	}
	if overlap != nil {
		xml.WriteString(`<c:overlap val="`)
		xml.WriteString(strconv.Itoa(*overlap))
		xml.WriteString(`"/>`)
	}
	return xml.String()
}

func officePPTXChartTitleXML(title string) string {
	title = strings.TrimSpace(title)
	if title == "" {
		return ``
	}
	return `<c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US"/><a:t>` +
		officeXMLText(title) +
		`</a:t></a:r></a:p></c:rich></c:tx><c:layout/></c:title>`
}

func officePPTXChartNumber(value float64) string {
	return strconv.FormatFloat(value, 'f', -1, 64)
}

func officePPTXBoolVal(value bool) string {
	if value {
		return "1"
	}
	return "0"
}

func officePPTXTableXML(table *officeTableSpec, tableWidth int) string {
	columnCount := officePPTXTableColumnCount(table)
	if columnCount == 0 {
		return ""
	}
	return `<a:tbl>` +
		`<a:tblPr firstRow="1" bandRow="1"><a:tableStyleId>{5C22544A-7EE6-4342-B048-85BDC9FD1C3A}</a:tableStyleId></a:tblPr>` +
		officePPTXTableGridXML(columnCount, tableWidth) +
		officePPTXTableRowsXML(table, columnCount) +
		`</a:tbl>`
}

func officePPTXTableGridXML(columnCount, tableWidth int) string {
	if columnCount <= 0 {
		return `<a:tblGrid/>`
	}
	widths := make([]int, columnCount)
	baseWidth := tableWidth / columnCount
	remainder := tableWidth % columnCount
	for idx := range widths {
		widths[idx] = baseWidth
		if idx == columnCount-1 {
			widths[idx] += remainder
		}
	}

	var grid strings.Builder
	grid.WriteString(`<a:tblGrid>`)
	for _, width := range widths {
		grid.WriteString(fmt.Sprintf(`<a:gridCol w="%d"/>`, width))
	}
	grid.WriteString(`</a:tblGrid>`)
	return grid.String()
}

func officePPTXTableRowsXML(table *officeTableSpec, columnCount int) string {
	var rows strings.Builder
	if len(table.Headers) > 0 {
		rows.WriteString(officePPTXTableRowXML(table.Headers, columnCount, true))
	}
	for _, row := range table.Rows {
		rows.WriteString(officePPTXTableRowXML(row, columnCount, false))
	}
	return rows.String()
}

func officePPTXTableRowXML(values []string, columnCount int, header bool) string {
	const rowHeight = 370840

	var row strings.Builder
	row.WriteString(fmt.Sprintf(`<a:tr h="%d">`, rowHeight))
	for idx := 0; idx < columnCount; idx++ {
		value := ""
		if idx < len(values) {
			value = values[idx]
		}
		row.WriteString(officePPTXTableCellXML(value, header))
	}
	row.WriteString(`</a:tr>`)
	return row.String()
}

func officePPTXTableCellXML(value string, header bool) string {
	runStyle := `lang="en-US" sz="1800"`
	if header {
		runStyle = `lang="en-US" b="1" sz="1800"`
	}
	return `<a:tc><a:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr ` + runStyle + `/><a:t>` +
		officeXMLText(value) +
		`</a:t></a:r></a:p></a:txBody><a:tcPr marL="91440" marR="91440" marT="45720" marB="45720" anchor="ctr"/></a:tc>`
}

func officePPTXTableColumnCount(table *officeTableSpec) int {
	if table == nil {
		return 0
	}
	count := len(table.Headers)
	for _, row := range table.Rows {
		if len(row) > count {
			count = len(row)
		}
	}
	return count
}

func officePPTXSlideRelsXML(chartIndex int) string {
	rels := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>`
	if chartIndex > 0 {
		rels += fmt.Sprintf(`<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart" Target="../charts/chart%d.xml"/>`, chartIndex)
	}
	rels += `</Relationships>`
	return rels
}
