package tools

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

type officeXLSXCell struct {
	Value       interface{}
	Style       int
	ForceString bool
}

type officeXLSXRow struct {
	Height float64
	Cells  []officeXLSXCell
}

type officeXLSXSheetBuild struct {
	Name       string
	Rows       []officeXLSXRow
	ColWidths  []float64
	Freeze     string
	AutoFilter string
	Merges     []string
	TabColor   string
}

type officeXLSXXF struct {
	FontID     int
	FillID     int
	BorderID   int
	Horizontal string
	Vertical   string
	Wrap       bool
}

func buildOfficeXLSX(spec officeWorkbookSpec) ([]byte, officeBuildInfo, error) {
	sheets := officeBuildWorkbookSheets(spec)
	if len(sheets) == 0 {
		return nil, officeBuildInfo{}, fmt.Errorf("xlsx output requires at least one worksheet")
	}

	entries := []officeZipEntry{
		{Name: "[Content_Types].xml", Content: officeXLSXContentTypesXML(len(sheets))},
		{Name: "_rels/.rels", Content: officePackageRelsXML("xl/workbook.xml")},
		{Name: "docProps/core.xml", Content: officeCorePropsXML(spec.Title, "Styled workbook generated by ZimaOS Blue")},
		{Name: "docProps/app.xml", Content: officeXLSXAppPropsXML(sheets)},
		{Name: "xl/workbook.xml", Content: officeXLSXWorkbookXML(sheets)},
		{Name: "xl/_rels/workbook.xml.rels", Content: officeXLSXWorkbookRelsXML(len(sheets))},
		{Name: "xl/styles.xml", Content: officeXLSXStylesXML(spec.Theme)},
	}
	for idx, sheet := range sheets {
		entries = append(entries, officeZipEntry{
			Name:    fmt.Sprintf("xl/worksheets/sheet%d.xml", idx+1),
			Content: officeXLSXWorksheetXML(sheet),
		})
	}

	data, err := officeBuildZip(entries)
	if err != nil {
		return nil, officeBuildInfo{}, err
	}

	rowCount := 0
	for _, sheet := range spec.Sheets {
		rowCount += len(sheet.Rows)
	}
	return data, officeBuildInfo{
		Format:     "xlsx",
		SheetCount: len(sheets),
		RowCount:   rowCount,
	}, nil
}

func officeBuildWorkbookSheets(spec officeWorkbookSpec) []officeXLSXSheetBuild {
	used := make(map[string]int)
	out := make([]officeXLSXSheetBuild, 0, len(spec.Sheets)+1)
	if officeWorkbookNeedsOverview(spec) {
		out = append(out, officeBuildOverviewSheet(spec, used))
	}
	for _, sheet := range spec.Sheets {
		out = append(out, officeBuildDataSheet(spec.Theme, sheet, used))
	}
	return out
}

func officeWorkbookNeedsOverview(spec officeWorkbookSpec) bool {
	return strings.TrimSpace(spec.Title) != "" ||
		strings.TrimSpace(spec.Subtitle) != "" ||
		len(spec.Stats) > 0 ||
		len(spec.Notes) > 0 ||
		len(spec.Sheets) > 1
}

func officeBuildOverviewSheet(spec officeWorkbookSpec, used map[string]int) officeXLSXSheetBuild {
	const overviewCols = 6

	sheet := officeXLSXSheetBuild{
		Name:      officeUniqueSheetName("Overview", used),
		ColWidths: []float64{18, 18, 18, 18, 18, 18},
		TabColor:  spec.Theme.Accent,
	}

	makeRow := func(height float64) officeXLSXRow {
		return officeXLSXRow{
			Height: height,
			Cells:  make([]officeXLSXCell, overviewCols),
		}
	}
	addMergedValue := func(row *officeXLSXRow, startCol, endCol int, value interface{}, style int) {
		if row == nil || startCol < 0 || endCol < startCol || startCol >= len(row.Cells) {
			return
		}
		row.Cells[startCol] = officeXLSXCell{
			Value:       value,
			Style:       style,
			ForceString: true,
		}
		rowIndex := len(sheet.Rows) + 1
		sheet.Merges = append(sheet.Merges, officeXLSXRangeRef(startCol, rowIndex, endCol, rowIndex))
	}
	addSection := func(title string) {
		row := makeRow(22)
		addMergedValue(&row, 0, overviewCols-1, title, 3)
		sheet.Rows = append(sheet.Rows, row)
	}

	title := strings.TrimSpace(spec.Title)
	if title == "" {
		title = "Workbook Overview"
	}
	titleRow := makeRow(30)
	addMergedValue(&titleRow, 0, overviewCols-1, title, 1)
	sheet.Rows = append(sheet.Rows, titleRow)

	subtitleParts := make([]string, 0, 3)
	if subtitle := strings.TrimSpace(spec.Subtitle); subtitle != "" {
		subtitleParts = append(subtitleParts, subtitle)
	}
	subtitleParts = append(subtitleParts, "Generated "+time.Now().Format("2006-01-02"))
	subtitleParts = append(subtitleParts, "Theme "+spec.Theme.Name)
	subtitleRow := makeRow(20)
	addMergedValue(&subtitleRow, 0, overviewCols-1, strings.Join(subtitleParts, "  •  "), 2)
	sheet.Rows = append(sheet.Rows, subtitleRow, makeRow(10))

	if len(spec.Stats) > 0 {
		addSection("Snapshot")
		for start := 0; start < len(spec.Stats); start += 3 {
			labelRow := makeRow(18)
			valueRow := makeRow(28)
			for offset := 0; offset < 3 && start+offset < len(spec.Stats); offset++ {
				stat := spec.Stats[start+offset]
				tone := officeNormalizeToneName(stat.Tone)
				if tone == "" {
					tone = officeClassifyTone(stat.Value)
				}
				labelStyle, valueStyle := officeStatCardStyles(tone)
				col := offset * 2
				labelRow.Cells[col] = officeXLSXCell{Value: stat.Label, Style: labelStyle, ForceString: true}
				valueRow.Cells[col] = officeXLSXCell{Value: stat.Value, Style: valueStyle, ForceString: true}
				rowIndex := len(sheet.Rows) + 1
				sheet.Merges = append(sheet.Merges,
					officeXLSXRangeRef(col, rowIndex, col+1, rowIndex),
					officeXLSXRangeRef(col, rowIndex+1, col+1, rowIndex+1),
				)
			}
			sheet.Rows = append(sheet.Rows, labelRow, valueRow, makeRow(8))
		}
	}

	addSection("Sheets")
	header := makeRow(22)
	header.Cells[0] = officeXLSXCell{Value: "Sheet", Style: 5, ForceString: true}
	header.Cells[1] = officeXLSXCell{Value: "Rows", Style: 5, ForceString: true}
	header.Cells[2] = officeXLSXCell{Value: "Columns", Style: 5, ForceString: true}
	header.Cells[3] = officeXLSXCell{Value: "Freeze", Style: 5, ForceString: true}
	header.Cells[4] = officeXLSXCell{Value: "Filter", Style: 5, ForceString: true}
	header.Cells[5] = officeXLSXCell{Value: "Theme", Style: 5, ForceString: true}
	sheet.Rows = append(sheet.Rows, header)
	for idx, item := range spec.Sheets {
		row := makeRow(20)
		if idx%2 == 0 {
			row.Cells[0] = officeXLSXCell{Value: item.Name, Style: 6, ForceString: true}
			row.Cells[1] = officeXLSXCell{Value: len(item.Rows), Style: 10}
			row.Cells[2] = officeXLSXCell{Value: len(item.Columns), Style: 10}
			row.Cells[3] = officeXLSXCell{Value: firstNonEmptyOfficeString(item.Freeze, "A2"), Style: 6, ForceString: true}
			row.Cells[4] = officeXLSXCell{Value: officeBoolWord(item.Filter), Style: 6, ForceString: true}
			row.Cells[5] = officeXLSXCell{Value: spec.Theme.Name, Style: 15, ForceString: true}
		} else {
			row.Cells[0] = officeXLSXCell{Value: item.Name, Style: 7, ForceString: true}
			row.Cells[1] = officeXLSXCell{Value: len(item.Rows), Style: 11}
			row.Cells[2] = officeXLSXCell{Value: len(item.Columns), Style: 11}
			row.Cells[3] = officeXLSXCell{Value: firstNonEmptyOfficeString(item.Freeze, "A2"), Style: 7, ForceString: true}
			row.Cells[4] = officeXLSXCell{Value: officeBoolWord(item.Filter), Style: 7, ForceString: true}
			row.Cells[5] = officeXLSXCell{Value: spec.Theme.Name, Style: 15, ForceString: true}
		}
		sheet.Rows = append(sheet.Rows, row)
	}

	if len(spec.Notes) > 0 {
		sheet.Rows = append(sheet.Rows, makeRow(10))
		addSection("Notes")
		for _, note := range spec.Notes {
			note = strings.TrimSpace(note)
			if note == "" {
				continue
			}
			row := makeRow(34)
			addMergedValue(&row, 0, overviewCols-1, "• "+note, 4)
			sheet.Rows = append(sheet.Rows, row)
		}
	}

	return sheet
}

func officeBuildDataSheet(theme officeTheme, spec officeSheetSpec, used map[string]int) officeXLSXSheetBuild {
	name := officeUniqueSheetName(spec.Name, used)
	if name == "" {
		name = officeUniqueSheetName("Sheet", used)
	}

	columns := append([]officeColumnSpec(nil), spec.Columns...)
	maxCells := 0
	for _, row := range spec.Rows {
		if len(row) > maxCells {
			maxCells = len(row)
		}
	}
	for len(columns) < maxCells {
		idx := len(columns) + 1
		columns = append(columns, officeColumnSpec{
			Header: fmt.Sprintf("Column %d", idx),
			Key:    fmt.Sprintf("col_%d", idx),
			Kind:   "text",
		})
	}

	rows := make([]officeXLSXRow, 0, len(spec.Rows)+1)
	header := officeXLSXRow{
		Height: 22,
		Cells:  make([]officeXLSXCell, len(columns)),
	}
	for idx, column := range columns {
		header.Cells[idx] = officeXLSXCell{Value: column.Header, Style: 5, ForceString: true}
	}
	rows = append(rows, header)

	for rowIndex, raw := range spec.Rows {
		row := officeXLSXRow{
			Height: 20,
			Cells:  make([]officeXLSXCell, len(columns)),
		}
		for colIndex, column := range columns {
			var value interface{}
			if colIndex < len(raw) {
				value = raw[colIndex]
			}
			style := officeXLSXDataStyle(column, rowIndex, value)
			row.Cells[colIndex] = officeXLSXCell{
				Value:       value,
				Style:       style,
				ForceString: !officeShouldWriteNumericCell(column, value),
			}
		}
		rows = append(rows, row)
	}

	freeze := strings.TrimSpace(spec.Freeze)
	if freeze == "" && len(columns) > 0 {
		freeze = "A2"
	}

	autoFilter := ""
	if spec.Filter && len(columns) > 0 && len(rows) > 1 {
		autoFilter = officeXLSXRangeRef(0, 1, len(columns)-1, len(rows))
	}

	widths := make([]float64, len(columns))
	for idx, column := range columns {
		widths[idx] = officeInferXLSXColumnWidth(column, spec.Rows, idx)
	}

	return officeXLSXSheetBuild{
		Name:       name,
		Rows:       rows,
		ColWidths:  widths,
		Freeze:     freeze,
		AutoFilter: autoFilter,
		TabColor:   theme.Primary,
	}
}

func officeUniqueSheetName(raw string, used map[string]int) string {
	base := officeSanitizeSheetName(raw)
	if base == "" {
		base = "Sheet"
	}
	count := used[base]
	if count == 0 {
		used[base] = 1
		return base
	}
	for idx := count + 1; ; idx++ {
		suffix := fmt.Sprintf(" %d", idx)
		candidate := base
		if len([]rune(candidate))+len([]rune(suffix)) > 31 {
			candidate = string([]rune(candidate)[:31-len([]rune(suffix))])
		}
		candidate += suffix
		if used[candidate] == 0 {
			used[base] = idx
			used[candidate] = 1
			return candidate
		}
	}
}

func officeSanitizeSheetName(raw string) string {
	replacer := strings.NewReplacer("\\", " ", "/", " ", "?", " ", "*", " ", "[", " ", "]", " ", ":", " ")
	clean := strings.TrimSpace(replacer.Replace(raw))
	clean = strings.Join(strings.Fields(clean), " ")
	if clean == "" {
		return ""
	}
	runes := []rune(clean)
	if len(runes) > 31 {
		return string(runes[:31])
	}
	return clean
}

func officeInferXLSXColumnWidth(column officeColumnSpec, rows [][]interface{}, columnIndex int) float64 {
	if column.Width > 0 {
		return officeClampFloat(column.Width, 8, 48)
	}
	maxLen := officeMaxLineRunes(column.Header)
	sample := len(rows)
	if sample > 40 {
		sample = 40
	}
	for idx := 0; idx < sample; idx++ {
		if columnIndex >= len(rows[idx]) {
			continue
		}
		text := officeCellString(rows[idx][columnIndex])
		if lineLen := officeMaxLineRunes(text); lineLen > maxLen {
			maxLen = lineLen
		}
	}
	width := float64(maxLen + 2)
	switch strings.ToLower(strings.TrimSpace(column.Kind)) {
	case "number":
		return officeClampFloat(width, 10, 16)
	case "wrap":
		return officeClampFloat(width+4, 18, 36)
	default:
		if maxLen > 28 {
			return officeClampFloat(width+2, 14, 42)
		}
		return officeClampFloat(width, 10, 24)
	}
}

func officeMaxLineRunes(text string) int {
	lines := strings.Split(strings.ReplaceAll(text, "\r\n", "\n"), "\n")
	maxLen := 0
	for _, line := range lines {
		if l := runeCount(strings.TrimSpace(line)); l > maxLen {
			maxLen = l
		}
	}
	return maxLen
}

func officeXLSXDataStyle(column officeColumnSpec, rowIndex int, value interface{}) int {
	alt := rowIndex%2 == 1
	kind := strings.ToLower(strings.TrimSpace(column.Kind))
	switch kind {
	case "tone":
		if tone := officeClassifyTone(value); tone != "" {
			return officeToneDataStyle(tone)
		}
	case "delta":
		if tone := officeClassifyDeltaTone(value); tone != "" {
			return officeToneDataStyle(tone)
		}
	case "number":
		if alt {
			return 11
		}
		return 10
	case "wrap":
		if alt {
			return 9
		}
		return 8
	}

	text := officeCellString(value)
	if strings.Contains(text, "\n") || runeCount(text) > 40 {
		if alt {
			return 9
		}
		return 8
	}
	if alt {
		return 7
	}
	return 6
}

func officeShouldWriteNumericCell(column officeColumnSpec, value interface{}) bool {
	if value == nil {
		return false
	}
	switch strings.ToLower(strings.TrimSpace(column.Kind)) {
	case "tone", "delta":
		return false
	}
	_, ok := officeCellNumber(value)
	return ok
}

func officeStatCardStyles(tone string) (int, int) {
	switch tone {
	case "success":
		return 18, 19
	case "warning":
		return 20, 21
	case "danger":
		return 22, 23
	case "muted":
		return 24, 25
	default:
		return 16, 17
	}
}

func officeToneDataStyle(tone string) int {
	switch tone {
	case "success":
		return 12
	case "warning":
		return 13
	case "danger":
		return 14
	default:
		return 15
	}
}

func officeNormalizeToneName(raw string) string {
	value := strings.ToLower(strings.TrimSpace(raw))
	switch {
	case value == "":
		return ""
	case officeContainsAny(value, "success", "positive", "good", "pass", "green", "通过", "成功", "正向", "良好"):
		return "success"
	case officeContainsAny(value, "warning", "warn", "attention", "watch", "amber", "中等", "提醒", "注意", "预警"):
		return "warning"
	case officeContainsAny(value, "danger", "risk", "critical", "error", "fail", "red", "风险", "严重", "失败", "危险"):
		return "danger"
	case officeContainsAny(value, "muted", "neutral", "secondary", "subtle", "中性", "次要", "弱化"):
		return "muted"
	default:
		return "primary"
	}
}

func officeClassifyTone(value interface{}) string {
	text := strings.ToLower(strings.TrimSpace(officeCellString(value)))
	switch {
	case text == "":
		return ""
	case officeContainsAny(text,
		"critical", "blocker", "failed", "fail", "error", "down", "poor", "bad", "high risk", "red",
		"严重", "阻塞", "失败", "故障", "异常", "高风险", "较差", "不可用",
	):
		return "danger"
	case officeContainsAny(text,
		"warning", "warn", "attention", "monitor", "needs work", "partial", "pending", "medium",
		"提醒", "注意", "需优化", "待观察", "一般", "中等", "待处理",
	):
		return "warning"
	case officeContainsAny(text,
		"success", "passed", "pass", "healthy", "good", "excellent", "resolved", "approved", "stable", "done", "yes", "green",
		"通过", "成功", "健康", "良好", "优秀", "已解决", "已完成", "稳定", "正常",
	):
		return "success"
	default:
		return "muted"
	}
}

func officeClassifyDeltaTone(value interface{}) string {
	if number, ok := officeCellNumber(value); ok {
		switch {
		case number > 0:
			return "success"
		case number < 0:
			return "danger"
		default:
			return "muted"
		}
	}
	text := strings.TrimSpace(officeCellString(value))
	switch {
	case strings.HasPrefix(text, "+"):
		return "success"
	case strings.HasPrefix(text, "-"):
		return "danger"
	default:
		return officeClassifyTone(text)
	}
}

func officeXLSXWorksheetXML(sheet officeXLSXSheetBuild) string {
	lastRow := len(sheet.Rows)
	lastCol := len(sheet.ColWidths)
	if lastCol == 0 {
		for _, row := range sheet.Rows {
			if len(row.Cells) > lastCol {
				lastCol = len(row.Cells)
			}
		}
	}
	if lastCol == 0 {
		lastCol = 1
	}
	if lastRow == 0 {
		lastRow = 1
	}

	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8"?>`)
	sb.WriteString(`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">`)
	if color := officeHex(sheet.TabColor); color != "" {
		sb.WriteString(`<sheetPr><tabColor rgb="`)
		sb.WriteString(officeARGB(color))
		sb.WriteString(`"/></sheetPr>`)
	}
	sb.WriteString(`<dimension ref="`)
	sb.WriteString(officeXLSXRangeRef(0, 1, lastCol-1, lastRow))
	sb.WriteString(`"/>`)
	sb.WriteString(`<sheetViews><sheetView workbookViewId="0"`)
	if lastRow > 0 {
		sb.WriteString(` tabSelected="1"`)
	}
	sb.WriteString(`>`)
	sb.WriteString(officeXLSXFreezePaneXML(sheet.Freeze))
	sb.WriteString(`</sheetView></sheetViews>`)
	sb.WriteString(`<sheetFormatPr defaultRowHeight="18"/>`)
	if len(sheet.ColWidths) > 0 {
		sb.WriteString(`<cols>`)
		for idx, width := range sheet.ColWidths {
			sb.WriteString(fmt.Sprintf(`<col min="%d" max="%d" width="%.2f" customWidth="1"/>`, idx+1, idx+1, officeClampFloat(width, 8, 48)))
		}
		sb.WriteString(`</cols>`)
	}
	sb.WriteString(`<sheetData>`)
	for rowIndex, row := range sheet.Rows {
		sb.WriteString(`<row r="`)
		sb.WriteString(strconv.Itoa(rowIndex + 1))
		sb.WriteString(`"`)
		if row.Height > 0 {
			sb.WriteString(fmt.Sprintf(` ht="%.2f" customHeight="1"`, row.Height))
		}
		sb.WriteString(`>`)
		for colIndex, cell := range row.Cells {
			if cell.Value == nil && cell.Style == 0 {
				continue
			}
			sb.WriteString(officeXLSXCellXML(rowIndex+1, colIndex, cell))
		}
		sb.WriteString(`</row>`)
	}
	sb.WriteString(`</sheetData>`)
	if strings.TrimSpace(sheet.AutoFilter) != "" {
		sb.WriteString(`<autoFilter ref="`)
		sb.WriteString(officeXMLText(sheet.AutoFilter))
		sb.WriteString(`"/>`)
	}
	if len(sheet.Merges) > 0 {
		sb.WriteString(fmt.Sprintf(`<mergeCells count="%d">`, len(sheet.Merges)))
		for _, merge := range sheet.Merges {
			sb.WriteString(`<mergeCell ref="`)
			sb.WriteString(officeXMLText(merge))
			sb.WriteString(`"/>`)
		}
		sb.WriteString(`</mergeCells>`)
	}
	sb.WriteString(`<pageMargins left="0.35" right="0.35" top="0.55" bottom="0.55" header="0.3" footer="0.3"/>`)
	sb.WriteString(`</worksheet>`)
	return sb.String()
}

func officeXLSXCellXML(rowIndex, colIndex int, cell officeXLSXCell) string {
	ref := officeXLSXCellRef(colIndex, rowIndex)
	styleAttr := ""
	if cell.Style > 0 {
		styleAttr = fmt.Sprintf(` s="%d"`, cell.Style)
	}
	if !cell.ForceString {
		if number, ok := officeCellNumber(cell.Value); ok {
			return fmt.Sprintf(`<c r="%s"%s><v>%s</v></c>`, ref, styleAttr, officeNumericXMLValue(number))
		}
	}
	text := officeCellString(cell.Value)
	if text == "" {
		return fmt.Sprintf(`<c r="%s"%s/>`, ref, styleAttr)
	}
	return fmt.Sprintf(`<c r="%s"%s t="inlineStr"><is><t xml:space="preserve">%s</t></is></c>`, ref, styleAttr, officeXMLText(text))
}

func officeXLSXFreezePaneXML(ref string) string {
	ref = strings.TrimSpace(ref)
	if ref == "" {
		return ""
	}
	col, row, ok := officeParseCellRef(ref)
	if !ok || row <= 1 && col <= 1 {
		return ""
	}
	parts := make([]string, 0, 3)
	if col > 1 {
		parts = append(parts, fmt.Sprintf(`xSplit="%d"`, col-1))
	}
	if row > 1 {
		parts = append(parts, fmt.Sprintf(`ySplit="%d"`, row-1))
	}
	parts = append(parts, fmt.Sprintf(`topLeftCell="%s"`, officeXMLText(ref)))
	pane := "bottomLeft"
	if col > 1 && row > 1 {
		pane = "bottomRight"
	} else if col > 1 {
		pane = "topRight"
	}
	parts = append(parts, fmt.Sprintf(`activePane="%s" state="frozen"`, pane))
	return `<pane ` + strings.Join(parts, " ") + `/><selection pane="` + pane + `" activeCell="` + officeXMLText(ref) + `" sqref="` + officeXMLText(ref) + `"/>`
}

func officeParseCellRef(ref string) (int, int, bool) {
	ref = strings.TrimSpace(ref)
	if ref == "" {
		return 0, 0, false
	}
	col := 0
	row := 0
	seenLetter := false
	for _, r := range ref {
		switch {
		case r >= 'A' && r <= 'Z':
			col = col*26 + int(r-'A'+1)
			seenLetter = true
		case r >= 'a' && r <= 'z':
			col = col*26 + int(r-'a'+1)
			seenLetter = true
		case r >= '0' && r <= '9':
			if !seenLetter {
				return 0, 0, false
			}
			row = row*10 + int(r-'0')
		default:
			return 0, 0, false
		}
	}
	if col <= 0 || row <= 0 {
		return 0, 0, false
	}
	return col, row, true
}

func officeXLSXCellRef(colIndex, rowIndex int) string {
	return officeXLSXColumnName(colIndex) + strconv.Itoa(rowIndex)
}

func officeXLSXRangeRef(startCol, startRow, endCol, endRow int) string {
	return officeXLSXCellRef(startCol, startRow) + ":" + officeXLSXCellRef(endCol, endRow)
}

func officeXLSXColumnName(index int) string {
	index++
	name := ""
	for index > 0 {
		index--
		name = string(rune('A'+index%26)) + name
		index /= 26
	}
	return name
}

func officeNumericXMLValue(number float64) string {
	return strconv.FormatFloat(number, 'f', -1, 64)
}

func officeClampFloat(value, minValue, maxValue float64) float64 {
	if value < minValue {
		return minValue
	}
	if value > maxValue {
		return maxValue
	}
	return value
}

func officeXLSXContentTypesXML(sheetCount int) string {
	var overrides strings.Builder
	for idx := 0; idx < sheetCount; idx++ {
		overrides.WriteString(fmt.Sprintf(`<Override PartName="/xl/worksheets/sheet%d.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`, idx+1))
	}
	return `<?xml version="1.0" encoding="UTF-8"?>` +
		`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
		`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
		`<Default Extension="xml" ContentType="application/xml"/>` +
		`<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>` +
		`<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>` +
		`<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>` +
		`<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>` +
		overrides.String() +
		`</Types>`
}

func officeXLSXAppPropsXML(sheets []officeXLSXSheetBuild) string {
	var titles strings.Builder
	for _, sheet := range sheets {
		titles.WriteString(`<vt:lpstr>`)
		titles.WriteString(officeXMLText(sheet.Name))
		titles.WriteString(`</vt:lpstr>`)
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">` +
		`<Application>ZimaOS Blue</Application>` +
		`<DocSecurity>0</DocSecurity>` +
		`<ScaleCrop>false</ScaleCrop>` +
		`<HeadingPairs><vt:vector size="2" baseType="variant"><vt:variant><vt:lpstr>Worksheets</vt:lpstr></vt:variant><vt:variant><vt:i4>` + strconv.Itoa(len(sheets)) + `</vt:i4></vt:variant></vt:vector></HeadingPairs>` +
		`<TitlesOfParts><vt:vector size="` + strconv.Itoa(len(sheets)) + `" baseType="lpstr">` + titles.String() + `</vt:vector></TitlesOfParts>` +
		`<Company>IceWhaleTech</Company>` +
		`<LinksUpToDate>false</LinksUpToDate><SharedDoc>false</SharedDoc><HyperlinksChanged>false</HyperlinksChanged>` +
		`<AppVersion>1.0</AppVersion>` +
		`</Properties>`
}

func officeXLSXWorkbookXML(sheets []officeXLSXSheetBuild) string {
	var body strings.Builder
	for idx, sheet := range sheets {
		body.WriteString(fmt.Sprintf(`<sheet name="%s" sheetId="%d" r:id="rId%d"/>`, officeXMLText(sheet.Name), idx+1, idx+1))
	}
	return `<?xml version="1.0" encoding="UTF-8"?>` +
		`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
		`<bookViews><workbookView xWindow="120" yWindow="60" windowWidth="18000" windowHeight="9000"/></bookViews>` +
		`<sheets>` + body.String() + `</sheets>` +
		`</workbook>`
}

func officeXLSXWorkbookRelsXML(sheetCount int) string {
	var body strings.Builder
	for idx := 0; idx < sheetCount; idx++ {
		body.WriteString(fmt.Sprintf(`<Relationship Id="rId%d" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet%d.xml"/>`, idx+1, idx+1))
	}
	body.WriteString(fmt.Sprintf(`<Relationship Id="rId%d" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>`, sheetCount+1))
	return `<?xml version="1.0" encoding="UTF-8"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		body.String() +
		`</Relationships>`
}

func officeXLSXStylesXML(theme officeTheme) string {
	fills := []string{
		`<fill><patternFill patternType="none"/></fill>`,
		`<fill><patternFill patternType="gray125"/></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.Primary) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.SurfaceAlt) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.PrimaryTint) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.SuccessTint) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.WarningTint) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.DangerTint) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.SurfaceMuted) + `"/><bgColor indexed="64"/></patternFill></fill>`,
	}
	fonts := []string{
		`<font><sz val="11"/><color rgb="FF111827"/><name val="` + officeXMLText(theme.BodyFont) + `"/><family val="2"/></font>`,
		`<font><b/><sz val="22"/><color rgb="` + officeARGB(theme.PrimaryDark) + `"/><name val="` + officeXMLText(theme.DisplayFont) + `"/><family val="2"/></font>`,
		`<font><sz val="11"/><color rgb="` + officeARGB(theme.Slate) + `"/><name val="` + officeXMLText(theme.BodyFont) + `"/><family val="2"/></font>`,
		`<font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="` + officeXMLText(theme.BodyFont) + `"/><family val="2"/></font>`,
		`<font><b/><sz val="12"/><color rgb="` + officeARGB(theme.PrimaryDark) + `"/><name val="` + officeXMLText(theme.BodyFont) + `"/><family val="2"/></font>`,
		`<font><b/><sz val="10"/><color rgb="` + officeARGB(theme.PrimaryDark) + `"/><name val="` + officeXMLText(theme.BodyFont) + `"/><family val="2"/></font>`,
		`<font><b/><sz val="16"/><color rgb="` + officeARGB(theme.PrimaryDark) + `"/><name val="` + officeXMLText(theme.DisplayFont) + `"/><family val="2"/></font>`,
	}
	xfs := []officeXLSXXF{
		{FontID: 0, FillID: 0, BorderID: 0},
		{FontID: 1, FillID: 0, BorderID: 0, Vertical: "center", Wrap: true},
		{FontID: 2, FillID: 0, BorderID: 0, Vertical: "center", Wrap: true},
		{FontID: 4, FillID: 4, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 0, FillID: 8, BorderID: 1, Vertical: "top", Wrap: true},
		{FontID: 3, FillID: 2, BorderID: 1, Horizontal: "center", Vertical: "center", Wrap: true},
		{FontID: 0, FillID: 0, BorderID: 1, Vertical: "top"},
		{FontID: 0, FillID: 3, BorderID: 1, Vertical: "top"},
		{FontID: 0, FillID: 0, BorderID: 1, Vertical: "top", Wrap: true},
		{FontID: 0, FillID: 3, BorderID: 1, Vertical: "top", Wrap: true},
		{FontID: 0, FillID: 0, BorderID: 1, Horizontal: "right", Vertical: "center"},
		{FontID: 0, FillID: 3, BorderID: 1, Horizontal: "right", Vertical: "center"},
		{FontID: 0, FillID: 5, BorderID: 1, Horizontal: "center", Vertical: "center", Wrap: true},
		{FontID: 0, FillID: 6, BorderID: 1, Horizontal: "center", Vertical: "center", Wrap: true},
		{FontID: 0, FillID: 7, BorderID: 1, Horizontal: "center", Vertical: "center", Wrap: true},
		{FontID: 0, FillID: 8, BorderID: 1, Horizontal: "center", Vertical: "center", Wrap: true},
		{FontID: 5, FillID: 4, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 6, FillID: 4, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 5, FillID: 5, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 6, FillID: 5, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 5, FillID: 6, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 6, FillID: 6, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 5, FillID: 7, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 6, FillID: 7, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 5, FillID: 8, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 6, FillID: 8, BorderID: 1, Vertical: "center", Wrap: true},
	}

	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8"?>`)
	sb.WriteString(`<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">`)
	sb.WriteString(fmt.Sprintf(`<fonts count="%d">`, len(fonts)))
	for _, font := range fonts {
		sb.WriteString(font)
	}
	sb.WriteString(`</fonts>`)
	sb.WriteString(fmt.Sprintf(`<fills count="%d">`, len(fills)))
	for _, fill := range fills {
		sb.WriteString(fill)
	}
	sb.WriteString(`</fills>`)
	sb.WriteString(`<borders count="2">`)
	sb.WriteString(`<border><left/><right/><top/><bottom/><diagonal/></border>`)
	sb.WriteString(`<border><left style="thin"><color rgb="` + officeARGB(theme.Border) + `"/></left><right style="thin"><color rgb="` + officeARGB(theme.Border) + `"/></right><top style="thin"><color rgb="` + officeARGB(theme.Border) + `"/></top><bottom style="thin"><color rgb="` + officeARGB(theme.Border) + `"/></bottom><diagonal/></border>`)
	sb.WriteString(`</borders>`)
	sb.WriteString(`<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>`)
	sb.WriteString(fmt.Sprintf(`<cellXfs count="%d">`, len(xfs)))
	for _, xf := range xfs {
		sb.WriteString(officeXLSXXFXML(xf))
	}
	sb.WriteString(`</cellXfs>`)
	sb.WriteString(`<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>`)
	sb.WriteString(`</styleSheet>`)
	return sb.String()
}

func officeXLSXXFXML(xf officeXLSXXF) string {
	var sb strings.Builder
	sb.WriteString(`<xf numFmtId="0"`)
	sb.WriteString(fmt.Sprintf(` fontId="%d" fillId="%d" borderId="%d" xfId="0"`, xf.FontID, xf.FillID, xf.BorderID))
	if xf.FontID != 0 {
		sb.WriteString(` applyFont="1"`)
	}
	if xf.FillID != 0 {
		sb.WriteString(` applyFill="1"`)
	}
	if xf.BorderID != 0 {
		sb.WriteString(` applyBorder="1"`)
	}
	if xf.Horizontal != "" || xf.Vertical != "" || xf.Wrap {
		sb.WriteString(` applyAlignment="1">`)
		sb.WriteString(`<alignment`)
		if xf.Horizontal != "" {
			sb.WriteString(` horizontal="`)
			sb.WriteString(xf.Horizontal)
			sb.WriteString(`"`)
		}
		if xf.Vertical != "" {
			sb.WriteString(` vertical="`)
			sb.WriteString(xf.Vertical)
			sb.WriteString(`"`)
		}
		if xf.Wrap {
			sb.WriteString(` wrapText="1"`)
		}
		sb.WriteString(`/>`)
		sb.WriteString(`</xf>`)
		return sb.String()
	}
	sb.WriteString(`/>`)
	return sb.String()
}

func officeBoolWord(value bool) string {
	if value {
		return "On"
	}
	return "Off"
}

func firstNonEmptyOfficeString(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}
