package tools

import (
	"fmt"
	"io"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

type officeDOCXHyperlink struct {
	RelID string
	URL   string
}

func buildOfficeDOCX(spec officeDocSpec) ([]byte, officeBuildInfo, error) {
	spec = cleanupOfficeDocSpec(spec)
	images, err := officeDOCXCollectImages(spec)
	if err != nil {
		return nil, officeBuildInfo{}, err
	}
	hyperlinks := officeDOCXCollectHyperlinks(spec)

	entries := []officeZipEntry{
		{Name: "[Content_Types].xml", Content: officeDOCXContentTypesXML(images)},
		{Name: "_rels/.rels", Content: officePackageRelsXML("word/document.xml")},
		{Name: "docProps/core.xml", Content: officeCorePropsXML(spec.Title, "Styled report generated by ZimaOS Blue")},
		{Name: "docProps/app.xml", Content: officeDOCXAppPropsXML(spec)},
		{Name: "word/document.xml", Content: officeDOCXDocumentXML(spec, hyperlinks, images)},
		{Name: "word/styles.xml", Content: officeDOCXStylesXML(spec.Theme)},
		{Name: "word/settings.xml", Content: officeDOCXSettingsXML()},
		{Name: "word/fontTable.xml", Content: officeDOCXFontTableXML(spec.Theme)},
		{Name: "word/numbering.xml", Content: officeDOCXNumberingXML()},
		{Name: "word/_rels/document.xml.rels", Content: officeDOCXDocumentRelsXML(hyperlinks, images)},
	}
	for _, image := range images {
		imageData := append([]byte(nil), image.Data...)
		entries = append(entries, officeZipEntry{
			Name:     image.EntryName,
			SizeHint: len(imageData),
			WriteTo: func(w io.Writer) error {
				_, err := w.Write(imageData)
				return err
			},
		})
	}

	data, err := officeBuildZip(entries)
	if err != nil {
		return nil, officeBuildInfo{}, err
	}

	paragraphCount := len(splitOfficeParagraphs(spec.Summary)) + len(spec.ParagraphBlocks) + len(spec.Paragraphs) + len(spec.Notes)
	for _, section := range spec.Sections {
		paragraphCount += len(section.ParagraphBlocks) + len(section.Paragraphs) + len(section.Bullets)
	}

	return data, officeBuildInfo{
		Format:         "docx",
		SectionCount:   len(spec.Sections),
		ParagraphCount: paragraphCount,
	}, nil
}

func officeDOCXCollectHyperlinks(spec officeDocSpec) []officeDOCXHyperlink {
	seen := map[string]string{}
	ordered := make([]officeDOCXHyperlink, 0, 4)
	nextID := 5

	collectText := func(text string) {
		for _, run := range parseOfficeInlineMarkdown(text) {
			url := strings.TrimSpace(run.LinkURL)
			if url == "" {
				continue
			}
			if _, ok := seen[url]; ok {
				continue
			}
			relID := "rId" + strconv.Itoa(nextID)
			nextID++
			seen[url] = relID
			ordered = append(ordered, officeDOCXHyperlink{RelID: relID, URL: url})
		}
	}

	collectText(spec.Title)
	collectText(spec.Subtitle)
	collectText(spec.Summary)
	for _, block := range officeDocBlocksOrParagraphs(spec.ParagraphBlocks, spec.Paragraphs) {
		if block.Kind == officeDocBlockCode || block.Kind == officeDocBlockSeparator || block.Kind == officeDocBlockImage {
			continue
		}
		collectText(block.Text)
	}
	for _, note := range spec.Notes {
		collectText(note)
	}
	for _, section := range spec.Sections {
		collectText(section.Heading)
		for _, block := range officeDocBlocksOrParagraphs(section.ParagraphBlocks, section.Paragraphs) {
			if block.Kind == officeDocBlockCode || block.Kind == officeDocBlockSeparator || block.Kind == officeDocBlockImage {
				continue
			}
			collectText(block.Text)
		}
		for _, bullet := range section.Bullets {
			collectText(bullet)
		}
		if section.Table == nil {
			continue
		}
		for _, header := range section.Table.Headers {
			collectText(header)
		}
		for _, row := range section.Table.Rows {
			for _, cell := range row {
				collectText(cell)
			}
		}
	}

	return ordered
}

func officeDOCXCollectImages(spec officeDocSpec) ([]officeEmbeddedImage, error) {
	ordered := make([]officeEmbeddedImage, 0, 4)
	seen := map[string]struct{}{}
	nextIndex := 1

	collectBlock := func(block officeDocBlock) error {
		if block.Kind != officeDocBlockImage {
			return nil
		}
		source := strings.TrimSpace(block.Source)
		if source == "" {
			return nil
		}
		if _, ok := seen[source]; ok {
			return nil
		}
		image, err := officeLoadEmbeddedImage(source)
		if err != nil {
			return err
		}
		image.Index = nextIndex
		image.RelID = "rId" + strconv.Itoa(100+nextIndex)
		image.EntryName = fmt.Sprintf("word/media/image%d.%s", nextIndex, strings.TrimPrefix(filepath.Ext(image.EntryName), "."))
		image.Target = fmt.Sprintf("media/image%d.%s", nextIndex, strings.TrimPrefix(filepath.Ext(image.EntryName), "."))
		nextIndex++
		seen[source] = struct{}{}
		ordered = append(ordered, image)
		return nil
	}

	for _, block := range officeDocBlocksOrParagraphs(spec.ParagraphBlocks, spec.Paragraphs) {
		if err := collectBlock(block); err != nil {
			return nil, err
		}
	}
	for _, section := range spec.Sections {
		for _, block := range officeDocBlocksOrParagraphs(section.ParagraphBlocks, section.Paragraphs) {
			if err := collectBlock(block); err != nil {
				return nil, err
			}
		}
	}
	return ordered, nil
}

func officeDOCXHyperlinkRelID(hyperlinks []officeDOCXHyperlink, url string) string {
	url = strings.TrimSpace(url)
	for _, link := range hyperlinks {
		if link.URL == url {
			return link.RelID
		}
	}
	return ""
}

func officeDOCXContentTypesXML(images []officeEmbeddedImage) string {
	return `<?xml version="1.0" encoding="UTF-8"?>` +
		`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
		`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
		`<Default Extension="xml" ContentType="application/xml"/>` +
		officeImageContentTypeDefaults(images) +
		`<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>` +
		`<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>` +
		`<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>` +
		`<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>` +
		`<Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/>` +
		`<Override PartName="/word/fontTable.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml"/>` +
		`<Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/>` +
		`</Types>`
}

func officeDOCXAppPropsXML(spec officeDocSpec) string {
	title := strings.TrimSpace(spec.Title)
	if title == "" {
		title = "Document"
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">` +
		`<Application>ZimaOS Blue</Application>` +
		`<DocSecurity>0</DocSecurity>` +
		`<ScaleCrop>false</ScaleCrop>` +
		`<HeadingPairs><vt:vector size="2" baseType="variant"><vt:variant><vt:lpstr>Title</vt:lpstr></vt:variant><vt:variant><vt:i4>1</vt:i4></vt:variant></vt:vector></HeadingPairs>` +
		`<TitlesOfParts><vt:vector size="1" baseType="lpstr"><vt:lpstr>` + officeXMLText(title) + `</vt:lpstr></vt:vector></TitlesOfParts>` +
		`<Company>IceWhaleTech</Company>` +
		`<LinksUpToDate>false</LinksUpToDate><SharedDoc>false</SharedDoc><HyperlinksChanged>false</HyperlinksChanged>` +
		`<AppVersion>1.0</AppVersion>` +
		`</Properties>`
}

func officeDOCXDocumentRelsXML(hyperlinks []officeDOCXHyperlink, images []officeEmbeddedImage) string {
	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8"?>`)
	sb.WriteString(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">`)
	sb.WriteString(`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>`)
	sb.WriteString(`<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/>`)
	sb.WriteString(`<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/>`)
	sb.WriteString(`<Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/>`)
	for _, link := range hyperlinks {
		sb.WriteString(`<Relationship Id="`)
		sb.WriteString(link.RelID)
		sb.WriteString(`" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="`)
		sb.WriteString(officeXMLText(link.URL))
		sb.WriteString(`" TargetMode="External"/>`)
	}
	for _, image := range images {
		sb.WriteString(`<Relationship Id="`)
		sb.WriteString(image.RelID)
		sb.WriteString(`" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="`)
		sb.WriteString(officeXMLText(image.Target))
		sb.WriteString(`"/>`)
	}
	sb.WriteString(`</Relationships>`)
	return sb.String()
}

func officeDOCXNumberingXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">` +
		`<w:abstractNum w:abstractNumId="1"><w:multiLevelType w:val="singleLevel"/><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="bullet"/><w:lvlText w:val="•"/><w:lvlJc w:val="left"/><w:pPr><w:ind w:left="360" w:hanging="240"/></w:pPr><w:rPr><w:rFonts w:ascii="Aptos" w:hAnsi="Aptos" w:eastAsia="Aptos"/></w:rPr></w:lvl></w:abstractNum>` +
		`<w:abstractNum w:abstractNumId="2"><w:multiLevelType w:val="singleLevel"/><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/><w:lvlJc w:val="left"/><w:suff w:val="space"/><w:pPr><w:ind w:left="360" w:hanging="240"/></w:pPr></w:lvl></w:abstractNum>` +
		`<w:num w:numId="1"><w:abstractNumId w:val="1"/></w:num>` +
		`<w:num w:numId="2"><w:abstractNumId w:val="2"/></w:num>` +
		`</w:numbering>`
}

func officeDOCXSettingsXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">` +
		`<w:zoom w:percent="100"/>` +
		`<w:defaultTabStop w:val="720"/>` +
		`<w:compat/>` +
		`</w:settings>`
}

func officeDOCXFontTableXML(theme officeTheme) string {
	fonts := []string{theme.BodyFont, theme.DisplayFont, theme.EastAsiaFont, theme.MonospaceFont}
	seen := make(map[string]struct{}, len(fonts))
	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	sb.WriteString(`<w:fonts xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">`)
	for _, font := range fonts {
		font = strings.TrimSpace(font)
		if font == "" {
			continue
		}
		if _, ok := seen[font]; ok {
			continue
		}
		seen[font] = struct{}{}
		sb.WriteString(`<w:font w:name="`)
		sb.WriteString(officeXMLText(font))
		sb.WriteString(`"><w:family w:val="swiss"/></w:font>`)
	}
	sb.WriteString(`</w:fonts>`)
	return sb.String()
}

func officeDOCXStylesXML(theme officeTheme) string {
	primaryDark := officeWordHex(theme.PrimaryDark)
	primary := officeWordHex(theme.Primary)
	accent := officeWordHex(theme.Accent)
	secondary := officeWordHex(theme.Secondary)
	slate := officeWordHex(theme.Slate)
	border := officeWordHex(theme.Border)
	calloutFill := officeWordHex(theme.PrimaryTint)

	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	sb.WriteString(`<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">`)
	sb.WriteString(`<w:docDefaults>`)
	sb.WriteString(`<w:rPrDefault><w:rPr><w:rFonts w:ascii="` + officeXMLText(theme.BodyFont) + `" w:hAnsi="` + officeXMLText(theme.BodyFont) + `" w:eastAsia="` + officeXMLText(theme.EastAsiaFont) + `" w:cs="` + officeXMLText(theme.BodyFont) + `"/><w:color w:val="111827"/><w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr></w:rPrDefault>`)
	sb.WriteString(`<w:pPrDefault><w:pPr><w:spacing w:after="120" w:line="320" w:lineRule="auto"/></w:pPr></w:pPrDefault>`)
	sb.WriteString(`</w:docDefaults>`)
	sb.WriteString(`<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:qFormat/></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueTitle"><w:name w:val="Blue Title"/><w:basedOn w:val="Normal"/><w:next w:val="BlueBody"/><w:uiPriority w:val="1"/><w:qFormat/><w:pPr><w:spacing w:after="60"/><w:keepNext/></w:pPr><w:rPr><w:rFonts w:ascii="` + officeXMLText(theme.DisplayFont) + `" w:hAnsi="` + officeXMLText(theme.DisplayFont) + `" w:eastAsia="` + officeXMLText(theme.EastAsiaFont) + `"/><w:b/><w:color w:val="` + primaryDark + `"/><w:sz w:val="40"/><w:szCs w:val="40"/></w:rPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueSubtitle"><w:name w:val="Blue Subtitle"/><w:basedOn w:val="Normal"/><w:next w:val="BlueBody"/><w:pPr><w:spacing w:after="40"/><w:keepNext/></w:pPr><w:rPr><w:rFonts w:ascii="` + officeXMLText(theme.DisplayFont) + `" w:hAnsi="` + officeXMLText(theme.DisplayFont) + `" w:eastAsia="` + officeXMLText(theme.EastAsiaFont) + `"/><w:color w:val="` + secondary + `"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueMeta"><w:name w:val="Blue Meta"/><w:basedOn w:val="Normal"/><w:next w:val="BlueBody"/><w:pPr><w:spacing w:after="200"/></w:pPr><w:rPr><w:color w:val="` + slate + `"/><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueHeading1"><w:name w:val="Blue Heading 1"/><w:basedOn w:val="Normal"/><w:next w:val="BlueBody"/><w:uiPriority w:val="9"/><w:qFormat/><w:pPr><w:spacing w:before="280" w:after="80"/><w:keepNext/></w:pPr><w:rPr><w:rFonts w:ascii="` + officeXMLText(theme.DisplayFont) + `" w:hAnsi="` + officeXMLText(theme.DisplayFont) + `" w:eastAsia="` + officeXMLText(theme.EastAsiaFont) + `"/><w:b/><w:color w:val="` + primary + `"/><w:sz w:val="30"/><w:szCs w:val="30"/></w:rPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueBody"><w:name w:val="Blue Body"/><w:basedOn w:val="Normal"/><w:next w:val="BlueBody"/></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueBullet"><w:name w:val="Blue Bullet"/><w:basedOn w:val="BlueBody"/><w:pPr><w:ind w:left="360" w:hanging="240"/><w:spacing w:after="80"/></w:pPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueCallout"><w:name w:val="Blue Callout"/><w:basedOn w:val="BlueBody"/><w:pPr><w:spacing w:before="60" w:after="60"/><w:shd w:val="clear" w:fill="` + calloutFill + `"/><w:pBdr><w:left w:val="single" w:sz="12" w:space="1" w:color="` + accent + `"/><w:top w:val="single" w:sz="4" w:space="1" w:color="` + border + `"/><w:right w:val="single" w:sz="4" w:space="1" w:color="` + border + `"/><w:bottom w:val="single" w:sz="4" w:space="1" w:color="` + border + `"/></w:pBdr><w:ind w:left="180" w:right="60"/></w:pPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueCodeBlock"><w:name w:val="Blue Code Block"/><w:basedOn w:val="BlueBody"/><w:next w:val="BlueBody"/><w:pPr><w:spacing w:before="80" w:after="80"/><w:shd w:val="clear" w:fill="` + officeWordHex(theme.SurfaceMuted) + `"/><w:pBdr><w:left w:val="single" w:sz="8" w:space="1" w:color="` + border + `"/><w:top w:val="single" w:sz="8" w:space="1" w:color="` + border + `"/><w:right w:val="single" w:sz="8" w:space="1" w:color="` + border + `"/><w:bottom w:val="single" w:sz="8" w:space="1" w:color="` + border + `"/></w:pBdr><w:ind w:left="240" w:right="120"/></w:pPr><w:rPr><w:rFonts w:ascii="` + officeXMLText(theme.MonospaceFont) + `" w:hAnsi="` + officeXMLText(theme.MonospaceFont) + `" w:eastAsia="` + officeXMLText(theme.MonospaceFont) + `"/><w:color w:val="` + primaryDark + `"/><w:sz w:val="20"/><w:szCs w:val="20"/></w:rPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueSeparator"><w:name w:val="Blue Separator"/><w:basedOn w:val="BlueBody"/><w:next w:val="BlueBody"/><w:pPr><w:spacing w:before="140" w:after="140"/><w:pBdr><w:bottom w:val="single" w:sz="12" w:space="1" w:color="` + accent + `"/></w:pBdr></w:pPr></w:style>`)
	sb.WriteString(`</w:styles>`)
	return sb.String()
}

func officeDOCXDocumentXML(spec officeDocSpec, hyperlinks []officeDOCXHyperlink, images []officeEmbeddedImage) string {
	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	sb.WriteString(`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">`)
	sb.WriteString(`<w:body>`)

	title := strings.TrimSpace(spec.Title)
	if title != "" {
		sb.WriteString(officeDOCXParagraphXML("BlueTitle", title, spec.Theme.MonospaceFont, spec.Theme.Accent, hyperlinks))
	}
	if subtitle := strings.TrimSpace(spec.Subtitle); subtitle != "" {
		sb.WriteString(officeDOCXParagraphXML("BlueSubtitle", subtitle, spec.Theme.MonospaceFont, spec.Theme.Accent, hyperlinks))
	}
	meta := "Generated " + time.Now().Format("2006-01-02") + "  •  Theme " + spec.Theme.Name
	if hint := strings.TrimSpace(spec.StyleHint); hint != "" {
		meta += "  •  " + hint
	}
	sb.WriteString(officeDOCXParagraphXML("BlueMeta", meta, spec.Theme.MonospaceFont, spec.Theme.Accent, hyperlinks))

	for _, paragraph := range splitOfficeParagraphs(spec.Summary) {
		sb.WriteString(officeDOCXParagraphXML("BlueCallout", paragraph, spec.Theme.MonospaceFont, spec.Theme.Accent, hyperlinks))
	}
	for _, block := range officeDocBlocksOrParagraphs(spec.ParagraphBlocks, spec.Paragraphs) {
		sb.WriteString(officeDOCXBlockXML(block, spec.Theme.MonospaceFont, spec.Theme.Accent, hyperlinks, images))
	}

	for _, section := range spec.Sections {
		if heading := strings.TrimSpace(section.Heading); heading != "" {
			sb.WriteString(officeDOCXParagraphXML("BlueHeading1", heading, spec.Theme.MonospaceFont, spec.Theme.Accent, hyperlinks))
		}
		for _, block := range officeDocBlocksOrParagraphs(section.ParagraphBlocks, section.Paragraphs) {
			sb.WriteString(officeDOCXBlockXML(block, spec.Theme.MonospaceFont, spec.Theme.Accent, hyperlinks, images))
		}
		for _, bullet := range section.Bullets {
			bullet = strings.TrimSpace(bullet)
			if bullet == "" {
				continue
			}
			sb.WriteString(officeDOCXListParagraphXML(bullet, spec.Theme.MonospaceFont, spec.Theme.Accent, hyperlinks))
		}
		if section.Table != nil {
			sb.WriteString(officeDOCXTableXML(section.Table, spec.Theme, hyperlinks))
		}
	}

	if len(spec.Notes) > 0 {
		sb.WriteString(officeDOCXParagraphXML("BlueHeading1", "Notes", spec.Theme.MonospaceFont, spec.Theme.Accent, hyperlinks))
		for _, note := range spec.Notes {
			note = strings.TrimSpace(note)
			if note == "" {
				continue
			}
			sb.WriteString(officeDOCXParagraphXML("BlueBullet", "• "+note, spec.Theme.MonospaceFont, spec.Theme.Accent, hyperlinks))
		}
	}

	sb.WriteString(officeDOCXSectionPropsXML())
	sb.WriteString(`</w:body></w:document>`)
	return sb.String()
}

func officeDOCXBlockXML(block officeDocBlock, monospaceFont, linkColor string, hyperlinks []officeDOCXHyperlink, images []officeEmbeddedImage) string {
	switch block.Kind {
	case officeDocBlockQuote:
		return officeDOCXParagraphXML("BlueCallout", block.Text, monospaceFont, linkColor, hyperlinks)
	case officeDocBlockCode:
		return officeDOCXPlainParagraphXML("BlueCodeBlock", block.Text, officeResolvedMonospaceFont(monospaceFont))
	case officeDocBlockSeparator:
		return officeDOCXSeparatorXML()
	case officeDocBlockImage:
		return officeDOCXImageXML(block, images)
	default:
		return officeDOCXParagraphXML("BlueBody", block.Text, monospaceFont, linkColor, hyperlinks)
	}
}

func officeDOCXSeparatorXML() string {
	return `<w:p><w:pPr><w:pStyle w:val="BlueSeparator"/></w:pPr><w:r><w:t xml:space="preserve"> </w:t></w:r></w:p>`
}

func officeDOCXImageXML(block officeDocBlock, images []officeEmbeddedImage) string {
	image := officeImageBySource(images, block.Source)
	if image == nil {
		return ""
	}
	const (
		maxWidthEMU  = 5486400
		maxHeightEMU = 3657600
	)
	cx, cy := officeImageFitEMU(image.WidthPx, image.HeightPx, maxWidthEMU, maxHeightEMU)
	alt := officeImageAltText(block)
	docPrID := 300 + image.Index
	return `<w:p><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="` +
		strconv.Itoa(cx) + `" cy="` + strconv.Itoa(cy) + `"/><wp:docPr id="` + strconv.Itoa(docPrID) +
		`" name="Image ` + strconv.Itoa(image.Index) + `" descr="` + officeXMLText(alt) +
		`"/><wp:cNvGraphicFramePr/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="` +
		strconv.Itoa(docPrID) + `" name="Image ` + strconv.Itoa(image.Index) + `" descr="` + officeXMLText(alt) +
		`"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="` + officeXMLText(image.RelID) +
		`"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="` +
		strconv.Itoa(cx) + `" cy="` + strconv.Itoa(cy) + `"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`
}

func officeDOCXParagraphXML(style, text, monospaceFont, linkColor string, hyperlinks []officeDOCXHyperlink) string {
	return officeDOCXParagraphWithPropsXML(style, "", text, monospaceFont, linkColor, hyperlinks)
}

func officeDOCXParagraphWithPropsXML(style, extraProps, text, monospaceFont, linkColor string, hyperlinks []officeDOCXHyperlink) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return ""
	}
	var sb strings.Builder
	sb.WriteString(`<w:p>`)
	if style != "" || extraProps != "" {
		sb.WriteString(`<w:pPr>`)
		if style != "" {
			sb.WriteString(`<w:pStyle w:val="`)
			sb.WriteString(style)
			sb.WriteString(`"/>`)
		}
		if extraProps != "" {
			sb.WriteString(extraProps)
		}
		sb.WriteString(`</w:pPr>`)
	}
	sb.WriteString(officeDOCXTextRunsXML(text, "", "", false, false, monospaceFont, linkColor, hyperlinks))
	sb.WriteString(`</w:p>`)
	return sb.String()
}

func officeDOCXListParagraphXML(item, monospaceFont, linkColor string, hyperlinks []officeDOCXHyperlink) string {
	item = strings.TrimSpace(item)
	if item == "" {
		return ""
	}
	if officeIsTaskListItem(item) {
		return officeDOCXParagraphXML("BlueBullet", item, monospaceFont, linkColor, hyperlinks)
	}
	if _, text, ok := officeOrderedListParts(item); ok {
		return officeDOCXParagraphWithPropsXML("BlueBullet", officeDOCXNumPrXML(2), text, monospaceFont, linkColor, hyperlinks)
	}
	if text, ok := officeExplicitUnorderedListBody(item); ok {
		return officeDOCXParagraphWithPropsXML("BlueBullet", officeDOCXNumPrXML(1), text, monospaceFont, linkColor, hyperlinks)
	}
	return officeDOCXParagraphWithPropsXML("BlueBullet", officeDOCXNumPrXML(1), item, monospaceFont, linkColor, hyperlinks)
}

func officeDOCXNumPrXML(numID int) string {
	return `<w:numPr><w:ilvl w:val="0"/><w:numId w:val="` + strconv.Itoa(numID) + `"/></w:numPr>`
}

func officeDOCXPlainParagraphXML(style, text, font string) string {
	text = strings.ReplaceAll(text, "\r\n", "\n")
	if strings.TrimSpace(text) == "" {
		return ""
	}
	var sb strings.Builder
	sb.WriteString(`<w:p>`)
	if style != "" {
		sb.WriteString(`<w:pPr><w:pStyle w:val="`)
		sb.WriteString(style)
		sb.WriteString(`"/></w:pPr>`)
	}
	sb.WriteString(officeDOCXLiteralTextRunsXML(text, font))
	sb.WriteString(`</w:p>`)
	return sb.String()
}

func officeDOCXTextRunsXML(text, color, font string, bold, italic bool, monospaceFont, linkColor string, hyperlinks []officeDOCXHyperlink) string {
	normalized := strings.ReplaceAll(text, "\r\n", "\n")
	parts := strings.Split(normalized, "\n")
	var sb strings.Builder
	for idx, part := range parts {
		runs := parseOfficeInlineMarkdown(part)
		if len(runs) == 0 {
			runs = []officeInlineRun{{Text: ""}}
		}
		for _, run := range runs {
			resolvedFont := strings.TrimSpace(font)
			if run.Code {
				resolvedFont = officeResolvedMonospaceFont(monospaceFont)
			}
			resolvedColor := color
			underline := false
			linkRelID := officeDOCXHyperlinkRelID(hyperlinks, run.LinkURL)
			if strings.TrimSpace(run.LinkURL) != "" {
				if strings.TrimSpace(resolvedColor) == "" {
					resolvedColor = strings.TrimSpace(linkColor)
					if resolvedColor == "" {
						resolvedColor = "2563EB"
					}
				}
				underline = true
			}
			if linkRelID != "" {
				sb.WriteString(`<w:hyperlink r:id="`)
				sb.WriteString(linkRelID)
				sb.WriteString(`" w:history="1">`)
			}
			sb.WriteString(`<w:r>`)
			if runProps := officeDOCXRunPropsXML(resolvedColor, resolvedFont, bold || run.Bold, italic || run.Italic, run.Strike, underline); runProps != "" {
				sb.WriteString(`<w:rPr>`)
				sb.WriteString(runProps)
				sb.WriteString(`</w:rPr>`)
			}
			sb.WriteString(`<w:t xml:space="preserve">`)
			sb.WriteString(officeXMLText(run.Text))
			sb.WriteString(`</w:t></w:r>`)
			if linkRelID != "" {
				sb.WriteString(`</w:hyperlink>`)
			}
		}
		if idx < len(parts)-1 {
			sb.WriteString(`<w:r><w:br/></w:r>`)
		}
	}
	return sb.String()
}

func officeDOCXLiteralTextRunsXML(text, font string) string {
	normalized := strings.ReplaceAll(text, "\r\n", "\n")
	parts := strings.Split(normalized, "\n")
	var sb strings.Builder
	for idx, part := range parts {
		sb.WriteString(`<w:r>`)
		if runProps := officeDOCXRunPropsXML("", strings.TrimSpace(font), false, false, false, false); runProps != "" {
			sb.WriteString(`<w:rPr>`)
			sb.WriteString(runProps)
			sb.WriteString(`</w:rPr>`)
		}
		sb.WriteString(`<w:t xml:space="preserve">`)
		sb.WriteString(officeXMLText(part))
		sb.WriteString(`</w:t></w:r>`)
		if idx < len(parts)-1 {
			sb.WriteString(`<w:r><w:br/></w:r>`)
		}
	}
	return sb.String()
}

func officeDOCXRunPropsXML(color, font string, bold, italic, strike, underline bool) string {
	var sb strings.Builder
	if font = strings.TrimSpace(font); font != "" {
		sb.WriteString(`<w:rFonts w:ascii="`)
		sb.WriteString(officeXMLText(font))
		sb.WriteString(`" w:hAnsi="`)
		sb.WriteString(officeXMLText(font))
		sb.WriteString(`" w:eastAsia="`)
		sb.WriteString(officeXMLText(font))
		sb.WriteString(`"/>`)
	}
	if bold {
		sb.WriteString(`<w:b/>`)
	}
	if italic {
		sb.WriteString(`<w:i/>`)
	}
	if strike {
		sb.WriteString(`<w:strike/>`)
	}
	if underline {
		sb.WriteString(`<w:u w:val="single"/>`)
	}
	if color = strings.TrimSpace(color); color != "" {
		sb.WriteString(`<w:color w:val="`)
		sb.WriteString(officeWordHex(color))
		sb.WriteString(`"/>`)
	}
	return sb.String()
}

func officeDOCXTableXML(table *officeTableSpec, theme officeTheme, hyperlinks []officeDOCXHyperlink) string {
	if table == nil {
		return ""
	}
	columnCount := len(table.Headers)
	for _, row := range table.Rows {
		if len(row) > columnCount {
			columnCount = len(row)
		}
	}
	if columnCount == 0 {
		return ""
	}

	headers := append([]string(nil), table.Headers...)
	for len(headers) < columnCount {
		headers = append(headers, fmt.Sprintf("Column %d", len(headers)+1))
	}
	widths := officeDOCXColumnWidths(table, headers, table.Rows)

	var sb strings.Builder
	sb.WriteString(`<w:tbl>`)
	sb.WriteString(`<w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders>`)
	for _, edge := range []string{"top", "left", "bottom", "right", "insideH", "insideV"} {
		sb.WriteString(`<w:` + edge + ` w:val="single" w:sz="6" w:space="0" w:color="` + officeWordHex(theme.Border) + `"/>`)
	}
	sb.WriteString(`</w:tblBorders><w:tblCellMar><w:top w:w="90" w:type="dxa"/><w:left w:w="120" w:type="dxa"/><w:bottom w:w="90" w:type="dxa"/><w:right w:w="120" w:type="dxa"/></w:tblCellMar></w:tblPr>`)
	sb.WriteString(`<w:tblGrid>`)
	for _, width := range widths {
		sb.WriteString(`<w:gridCol w:w="`)
		sb.WriteString(strconv.Itoa(width))
		sb.WriteString(`"/>`)
	}
	sb.WriteString(`</w:tblGrid>`)
	sb.WriteString(officeDOCXTableRowXML(table, headers, widths, theme.Primary, "FFFFFF", true, theme.MonospaceFont, theme.Accent, hyperlinks))
	for idx, row := range table.Rows {
		fill := ""
		if idx%2 == 1 {
			fill = theme.SurfaceAlt
		}
		values := make([]string, columnCount)
		copy(values, row)
		sb.WriteString(officeDOCXTableRowXML(table, values, widths, fill, "", false, theme.MonospaceFont, theme.Accent, hyperlinks))
	}
	sb.WriteString(`</w:tbl>`)
	return sb.String()
}

func officeDOCXTableRowXML(table *officeTableSpec, values []string, widths []int, fill, textColor string, bold bool, monospaceFont, linkColor string, hyperlinks []officeDOCXHyperlink) string {
	var sb strings.Builder
	sb.WriteString(`<w:tr>`)
	for idx, value := range values {
		width := 1800
		if idx < len(widths) {
			width = widths[idx]
		}
		sb.WriteString(officeDOCXTableCellXML(value, width, fill, textColor, bold, officeDOCXTableCellAlignment(table, idx), monospaceFont, linkColor, hyperlinks))
	}
	sb.WriteString(`</w:tr>`)
	return sb.String()
}

func officeDOCXTableCellXML(text string, width int, fill, textColor string, bold bool, alignment, monospaceFont, linkColor string, hyperlinks []officeDOCXHyperlink) string {
	var sb strings.Builder
	sb.WriteString(`<w:tc><w:tcPr><w:tcW w:w="`)
	sb.WriteString(strconv.Itoa(width))
	sb.WriteString(`" w:type="dxa"/>`)
	if strings.TrimSpace(fill) != "" {
		sb.WriteString(`<w:shd w:val="clear" w:fill="`)
		sb.WriteString(officeWordHex(fill))
		sb.WriteString(`"/>`)
	}
	sb.WriteString(`<w:vAlign w:val="top"/></w:tcPr>`)
	sb.WriteString(`<w:p><w:pPr><w:spacing w:after="0" w:line="260" w:lineRule="auto"/>`)
	if wordAlignment := officeDOCXTableParagraphAlignment(alignment); wordAlignment != "" {
		sb.WriteString(`<w:jc w:val="`)
		sb.WriteString(wordAlignment)
		sb.WriteString(`"/>`)
	}
	sb.WriteString(`</w:pPr>`)
	sb.WriteString(officeDOCXTextRunsXML(strings.TrimSpace(text), textColor, "", bold, false, monospaceFont, linkColor, hyperlinks))
	sb.WriteString(`</w:p></w:tc>`)
	return sb.String()
}

func officeDOCXTableCellAlignment(table *officeTableSpec, columnIndex int) string {
	if table == nil || columnIndex < 0 || columnIndex >= len(table.ColumnAlignments) {
		return ""
	}
	return table.ColumnAlignments[columnIndex]
}

func officeDOCXTableParagraphAlignment(alignment string) string {
	switch strings.ToLower(strings.TrimSpace(alignment)) {
	case "left":
		return "left"
	case "center":
		return "center"
	case "right":
		return "right"
	default:
		return ""
	}
}

func officeDOCXColumnWidths(table *officeTableSpec, headers []string, rows [][]string) []int {
	if widths := officeDOCXExplicitColumnWidths(table, len(headers)); len(widths) > 0 {
		return widths
	}
	weights := make([]int, len(headers))
	total := 0
	for idx, header := range headers {
		weight := officeMaxLineRunes(header) + 4
		for rowIdx := 0; rowIdx < len(rows) && rowIdx < 20; rowIdx++ {
			if idx >= len(rows[rowIdx]) {
				continue
			}
			if lineWeight := officeMaxLineRunes(rows[rowIdx][idx]) + 2; lineWeight > weight {
				weight = lineWeight
			}
		}
		if weight < 8 {
			weight = 8
		}
		weights[idx] = weight
		total += weight
	}
	if total == 0 {
		total = len(headers) * 8
	}
	widths := make([]int, len(headers))
	const tableWidth = 9000
	for idx, weight := range weights {
		width := tableWidth * weight / total
		if width < 1200 {
			width = 1200
		}
		widths[idx] = width
	}
	return widths
}

func officeDOCXExplicitColumnWidths(table *officeTableSpec, columnCount int) []int {
	if table == nil || columnCount <= 0 || len(table.ColumnWidths) == 0 {
		return nil
	}
	totalWeight := 0.0
	for idx := 0; idx < columnCount; idx++ {
		weight := 1.0
		if idx < len(table.ColumnWidths) && table.ColumnWidths[idx] > 0 {
			weight = table.ColumnWidths[idx]
		}
		totalWeight += weight
	}
	if totalWeight <= 0 {
		return nil
	}

	const tableWidth = 9000
	widths := make([]int, columnCount)
	remainingWidth := tableWidth
	remainingWeight := totalWeight
	for idx := range widths {
		weight := 1.0
		if idx < len(table.ColumnWidths) && table.ColumnWidths[idx] > 0 {
			weight = table.ColumnWidths[idx]
		}
		if idx == columnCount-1 || remainingWeight <= 0 {
			widths[idx] = remainingWidth
		} else {
			width := int(float64(tableWidth) * (weight / totalWeight))
			if width < 0 {
				width = 0
			}
			if width > remainingWidth {
				width = remainingWidth
			}
			widths[idx] = width
		}
		remainingWidth -= widths[idx]
		remainingWeight -= weight
	}
	return widths
}

func officeDOCXSectionPropsXML() string {
	return `<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1080" w:right="1020" w:bottom="1080" w:left="1020" w:header="480" w:footer="480" w:gutter="0"/><w:cols w:space="720"/></w:sectPr>`
}

func parseMarkdownishOfficeDoc(content string) officeDocSpec {
	spec := officeDocSpec{}
	normalized := strings.ReplaceAll(content, "\r\n", "\n")
	blocks := strings.Split(normalized, "\n\n")
	currentSection := -1

	appendTopParagraph := func(text string) {
		text = strings.TrimSpace(text)
		if text == "" {
			return
		}
		lower := strings.ToLower(text)
		if strings.HasPrefix(lower, "summary:") || strings.HasPrefix(lower, "摘要：") || strings.HasPrefix(lower, "摘要:") {
			text = strings.TrimSpace(strings.TrimPrefix(strings.TrimPrefix(strings.TrimPrefix(text, "Summary:"), "摘要:"), "摘要："))
			if text != "" {
				spec.Summary = text
			}
			return
		}
		if spec.Title != "" && spec.Subtitle == "" && spec.Summary == "" && len(spec.ParagraphBlocks) == 0 && len(spec.Paragraphs) == 0 && runeCount(text) <= 96 {
			spec.Subtitle = text
			return
		}
		if spec.Summary == "" {
			spec.Summary = text
			return
		}
		spec.ParagraphBlocks = append(spec.ParagraphBlocks, officeDocBlock{Kind: officeDocBlockParagraph, Text: text})
	}

	appendBlock := func(block officeDocBlock) {
		block.Text = strings.TrimSpace(block.Text)
		if block.Kind == officeDocBlockImage {
			block.Source = strings.TrimSpace(block.Source)
			if block.Source == "" {
				return
			}
		} else if block.Text == "" {
			return
		}
		if currentSection >= 0 && currentSection < len(spec.Sections) {
			spec.Sections[currentSection].ParagraphBlocks = append(spec.Sections[currentSection].ParagraphBlocks, block)
			return
		}
		if block.Kind == officeDocBlockParagraph {
			appendTopParagraph(block.Text)
			return
		}
		spec.ParagraphBlocks = append(spec.ParagraphBlocks, block)
	}

	startSection := func(heading string) {
		spec.Sections = append(spec.Sections, officeDocSection{Heading: strings.TrimSpace(heading)})
		currentSection = len(spec.Sections) - 1
	}

	for _, block := range blocks {
		block = strings.TrimSpace(strings.ReplaceAll(block, "\r\n", "\n"))
		if block == "" {
			continue
		}

		firstLine, rest := officeSplitFirstMarkdownLine(block)
		if heading, level, ok := officeMarkdownHeading(firstLine); ok {
			if level == 1 && spec.Title == "" && currentSection < 0 && spec.Summary == "" && len(spec.ParagraphBlocks) == 0 && len(spec.Paragraphs) == 0 {
				spec.Title = heading
			} else {
				startSection(heading)
			}
			block = strings.TrimSpace(rest)
			if block == "" {
				continue
			}
		}

		if alt, source, ok := officeMarkdownImageBlock(block); ok {
			appendBlock(officeDocBlock{Kind: officeDocBlockImage, Text: alt, Source: source})
			continue
		}
		if separator, ok := officeMarkdownThematicBreak(block); ok {
			appendBlock(officeDocBlock{Kind: officeDocBlockSeparator, Text: separator})
			continue
		}
		if code, ok := officeMarkdownFencedCodeBlock(block); ok {
			appendBlock(officeDocBlock{Kind: officeDocBlockCode, Text: code})
			continue
		}

		lines := officeTrimmedLines(block)
		if len(lines) == 0 {
			continue
		}
		if quote, ok := officeMarkdownBlockquote(lines); ok {
			appendBlock(officeDocBlock{Kind: officeDocBlockQuote, Text: quote})
			continue
		}
		if officeAllBulletLines(lines) {
			bullets := officeMarkdownBullets(lines)
			if len(bullets) == 0 {
				continue
			}
			if currentSection >= 0 && currentSection < len(spec.Sections) {
				spec.Sections[currentSection].Bullets = append(spec.Sections[currentSection].Bullets, bullets...)
			} else {
				startSection("Highlights")
				spec.Sections[currentSection].Bullets = append(spec.Sections[currentSection].Bullets, bullets...)
			}
			continue
		}

		if table := officeParseMarkdownTable(lines); table != nil {
			if currentSection >= 0 && currentSection < len(spec.Sections) {
				spec.Sections[currentSection].Table = table
			} else {
				startSection("Table")
				spec.Sections[currentSection].Table = table
			}
			continue
		}

		appendBlock(officeDocBlock{Kind: officeDocBlockParagraph, Text: officeJoinTextFragments(lines)})
	}

	return spec
}

func officeSplitFirstMarkdownLine(text string) (string, string) {
	text = strings.ReplaceAll(text, "\r\n", "\n")
	if idx := strings.IndexByte(text, '\n'); idx >= 0 {
		return strings.TrimSpace(text[:idx]), text[idx+1:]
	}
	return strings.TrimSpace(text), ""
}

func officeTrimmedLines(block string) []string {
	rawLines := strings.Split(strings.ReplaceAll(block, "\r\n", "\n"), "\n")
	lines := make([]string, 0, len(rawLines))
	for _, line := range rawLines {
		if trimmed := strings.TrimSpace(line); trimmed != "" {
			lines = append(lines, trimmed)
		}
	}
	return lines
}

func officeMarkdownHeading(line string) (string, int, bool) {
	line = strings.TrimSpace(line)
	for level := 1; level <= 3; level++ {
		prefix := strings.Repeat("#", level) + " "
		if strings.HasPrefix(line, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(line, prefix)), level, true
		}
	}
	return "", 0, false
}

func officeAllBulletLines(lines []string) bool {
	if len(lines) == 0 {
		return false
	}
	for _, line := range lines {
		if _, ok := officeParseMarkdownListItem(line); !ok {
			return false
		}
	}
	return true
}

func officeMarkdownBullets(lines []string) []string {
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		if bullet, ok := officeParseMarkdownListItem(line); ok && bullet != "" {
			out = append(out, bullet)
		}
	}
	return out
}

func officeParseMarkdownListItem(line string) (string, bool) {
	line = strings.TrimSpace(line)
	switch {
	case strings.HasPrefix(line, "- [x] "), strings.HasPrefix(line, "- [X] "), strings.HasPrefix(line, "* [x] "), strings.HasPrefix(line, "* [X] "):
		return "☑ " + strings.TrimSpace(line[6:]), true
	case strings.HasPrefix(line, "- [ ] "), strings.HasPrefix(line, "* [ ] "):
		return "☐ " + strings.TrimSpace(line[6:]), true
	}
	if officeIsOrderedListItem(line) {
		return line, true
	}
	switch {
	case strings.HasPrefix(line, "- "):
		return strings.TrimSpace(strings.TrimPrefix(line, "- ")), true
	case strings.HasPrefix(line, "* "):
		return strings.TrimSpace(strings.TrimPrefix(line, "* ")), true
	case strings.HasPrefix(line, "• "):
		return strings.TrimSpace(strings.TrimPrefix(line, "• ")), true
	}
	return "", false
}

func officeIsOrderedListItem(line string) bool {
	line = strings.TrimSpace(line)
	if line == "" {
		return false
	}
	for idx := 0; idx < len(line); idx++ {
		if line[idx] >= '0' && line[idx] <= '9' {
			continue
		}
		if idx == 0 || idx+1 >= len(line) {
			return false
		}
		if (line[idx] == '.' || line[idx] == ')') && line[idx+1] == ' ' {
			return true
		}
		return false
	}
	return false
}

func officeOrderedListParts(text string) (int, string, bool) {
	text = strings.TrimSpace(text)
	if text == "" {
		return 0, "", false
	}
	prefixLen := 0
	for prefixLen < len(text) && text[prefixLen] >= '0' && text[prefixLen] <= '9' {
		prefixLen++
	}
	if prefixLen == 0 || prefixLen >= len(text) {
		return 0, "", false
	}
	if text[prefixLen] != '.' && text[prefixLen] != ')' {
		return 0, "", false
	}
	prefixLen++
	if prefixLen >= len(text) || text[prefixLen] != ' ' {
		return 0, "", false
	}
	start, err := strconv.Atoi(text[:prefixLen-1])
	if err != nil || start <= 0 {
		return 0, "", false
	}
	return start, strings.TrimSpace(text[prefixLen+1:]), true
}

func officeExplicitUnorderedListBody(text string) (string, bool) {
	trimmed := strings.TrimSpace(text)
	for _, prefix := range []string{"- ", "* ", "• "} {
		if strings.HasPrefix(trimmed, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(trimmed, prefix)), true
		}
	}
	return "", false
}

func officeIsTaskListItem(text string) bool {
	text = strings.TrimSpace(text)
	return strings.HasPrefix(text, "☑ ") || strings.HasPrefix(text, "☐ ")
}

func officeRenderedListLine(text, defaultPrefix string) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return ""
	}
	if officeIsOrderedListItem(text) || officeIsTaskListItem(text) {
		return text
	}
	return defaultPrefix + text
}

func officeParseMarkdownTable(lines []string) *officeTableSpec {
	if len(lines) < 2 {
		return nil
	}
	for _, line := range lines {
		if !strings.Contains(line, "|") {
			return nil
		}
	}
	headers := officeMarkdownTableCells(lines[0])
	if len(headers) == 0 || !officeMarkdownTableDivider(lines[1], len(headers)) {
		return nil
	}
	rows := make([][]string, 0, len(lines)-2)
	for _, line := range lines[2:] {
		cells := officeMarkdownTableCells(line)
		if len(cells) == 0 {
			continue
		}
		for len(cells) < len(headers) {
			cells = append(cells, "")
		}
		rows = append(rows, cells)
	}
	return &officeTableSpec{Headers: headers, Rows: rows}
}

func officeMarkdownTableCells(line string) []string {
	line = strings.TrimSpace(line)
	line = strings.TrimPrefix(line, "|")
	line = strings.TrimSuffix(line, "|")
	parts := strings.Split(line, "|")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		out = append(out, strings.TrimSpace(part))
	}
	return out
}

func officeMarkdownTableDivider(line string, columns int) bool {
	cells := officeMarkdownTableCells(line)
	if len(cells) != columns {
		return false
	}
	for _, cell := range cells {
		cell = strings.TrimSpace(strings.Trim(cell, ":"))
		if cell == "" {
			return false
		}
		for _, r := range cell {
			if r != '-' {
				return false
			}
		}
	}
	return true
}
