package tools

import (
	"bufio"
	"fmt"
	"io"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode/utf8"
)

const officeStreamWriterBufferSize = 32 << 10

var officeStreamBufioWriterPool = sync.Pool{
	New: func() interface{} {
		return bufio.NewWriterSize(io.Discard, officeStreamWriterBufferSize)
	},
}

type officeXLSXCell struct {
	Value       interface{}
	Formula     string
	Type        string
	Format      string
	Style       int
	ForceString bool
}

type officeXLSXRow struct {
	Height float64
	Cells  []officeXLSXCell
}

type officeXLSXSheetBuild struct {
	Name       string
	Rows       []officeXLSXRow
	ColWidths  []float64
	ColStyles  []int
	Freeze     string
	AutoFilter string
	Merges     []string
	TabColor   string
}

type officeXLSXXF struct {
	NumFmtID   int
	FontID     int
	FillID     int
	BorderID   int
	Horizontal string
	Vertical   string
	Wrap       bool
}

type officeXLSXSheetArtifact struct {
	Name string
	XML  string
}

func buildOfficeXLSX(spec officeWorkbookSpec) ([]byte, officeBuildInfo, error) {
	used := make(map[string]int)
	sheets := make([]officeXLSXSheetBuild, 0, len(spec.Sheets)+1)
	sheetEntries := make([]officeZipEntry, 0, len(spec.Sheets)+1)
	if officeWorkbookNeedsOverview(spec) {
		overview := officeBuildOverviewSheet(spec, used)
		sheets = append(sheets, officeXLSXSheetBuild{Name: overview.Name})
		sheetEntries = append(sheetEntries, officeZipEntry{
			Name:    fmt.Sprintf("xl/worksheets/sheet%d.xml", len(sheetEntries)+1),
			Content: officeXLSXWorksheetXML(overview),
		})
	}
	for _, sheetSpec := range spec.Sheets {
		name, entry := officeBuildDataSheetZipEntry(spec.Theme, sheetSpec, used, fmt.Sprintf("xl/worksheets/sheet%d.xml", len(sheetEntries)+1))
		sheets = append(sheets, officeXLSXSheetBuild{Name: name})
		sheetEntries = append(sheetEntries, entry)
	}
	if len(sheets) == 0 {
		return nil, officeBuildInfo{}, fmt.Errorf("xlsx output requires at least one worksheet")
	}

	entries := make([]officeZipEntry, 0, 7+len(sheetEntries))
	entries = append(entries,
		officeZipEntry{Name: "[Content_Types].xml", Content: officeXLSXContentTypesXML(len(sheets))},
		officeZipEntry{Name: "_rels/.rels", Content: officePackageRelsXML("xl/workbook.xml")},
		officeZipEntry{Name: "docProps/core.xml", Content: officeCorePropsXML(spec.Title, "Styled workbook generated by ZimaOS Blue")},
		officeZipEntry{Name: "docProps/app.xml", Content: officeXLSXAppPropsXML(sheets)},
		officeZipEntry{Name: "xl/workbook.xml", Content: officeXLSXWorkbookXML(sheets)},
		officeZipEntry{Name: "xl/_rels/workbook.xml.rels", Content: officeXLSXWorkbookRelsXML(len(sheets))},
		officeZipEntry{Name: "xl/styles.xml", Content: officeXLSXStylesXML(spec.Theme)},
	)
	entries = append(entries, sheetEntries...)

	data, err := officeBuildZip(entries)
	if err != nil {
		return nil, officeBuildInfo{}, err
	}

	rowCount := 0
	for _, sheet := range spec.Sheets {
		rowCount += len(sheet.Rows)
	}
	return data, officeBuildInfo{
		Format:     "xlsx",
		SheetCount: len(sheets),
		RowCount:   rowCount,
	}, nil
}

func officeBuildWorkbookSheets(spec officeWorkbookSpec) []officeXLSXSheetBuild {
	used := make(map[string]int)
	out := make([]officeXLSXSheetBuild, 0, len(spec.Sheets)+1)
	if officeWorkbookNeedsOverview(spec) {
		out = append(out, officeBuildOverviewSheet(spec, used))
	}
	for _, sheet := range spec.Sheets {
		out = append(out, officeBuildDataSheet(spec.Theme, sheet, used))
	}
	return out
}

func officePrepareDataSheet(name string, spec officeSheetSpec, used map[string]int) (string, []officeColumnSpec) {
	name = officeUniqueSheetName(name, used)
	if name == "" {
		name = officeUniqueSheetName("Sheet", used)
	}

	columns := append([]officeColumnSpec(nil), spec.Columns...)
	maxCells := 0
	for _, row := range spec.Rows {
		if len(row) > maxCells {
			maxCells = len(row)
		}
	}
	for len(columns) < maxCells {
		idx := len(columns) + 1
		columns = append(columns, officeColumnSpec{
			Header: fmt.Sprintf("Column %d", idx),
			Key:    fmt.Sprintf("col_%d", idx),
			Kind:   "text",
		})
	}
	return name, columns
}

func officeDataSheetViewSettings(spec officeSheetSpec, columnCount, rowCount int) (string, string) {
	freeze := strings.TrimSpace(spec.Freeze)
	if freeze == "" && columnCount > 0 {
		freeze = "A2"
	}

	autoFilter := ""
	if spec.Filter && columnCount > 0 && rowCount > 1 {
		autoFilter = officeXLSXRangeRef(0, 1, columnCount-1, rowCount)
	}
	return freeze, autoFilter
}

func officeDataSheetWidths(columns []officeColumnSpec, rows [][]interface{}) []float64 {
	widths := make([]float64, len(columns))
	for idx, column := range columns {
		widths[idx] = officeInferXLSXColumnWidth(column, rows, idx)
	}
	return widths
}

func officeWorkbookNeedsOverview(spec officeWorkbookSpec) bool {
	return strings.TrimSpace(spec.Title) != "" ||
		strings.TrimSpace(spec.Subtitle) != "" ||
		len(spec.Stats) > 0 ||
		len(spec.Notes) > 0 ||
		len(spec.Sheets) > 1
}

func officeBuildOverviewSheet(spec officeWorkbookSpec, used map[string]int) officeXLSXSheetBuild {
	const overviewCols = 6

	sheet := officeXLSXSheetBuild{
		Name:      officeUniqueSheetName("Overview", used),
		ColWidths: []float64{18, 18, 18, 18, 18, 18},
		TabColor:  spec.Theme.Accent,
	}

	makeRow := func(height float64) officeXLSXRow {
		return officeXLSXRow{
			Height: height,
			Cells:  make([]officeXLSXCell, overviewCols),
		}
	}
	addMergedValue := func(row *officeXLSXRow, startCol, endCol int, value interface{}, style int) {
		if row == nil || startCol < 0 || endCol < startCol || startCol >= len(row.Cells) {
			return
		}
		row.Cells[startCol] = officeXLSXCell{
			Value:       value,
			Style:       style,
			ForceString: true,
		}
		rowIndex := len(sheet.Rows) + 1
		sheet.Merges = append(sheet.Merges, officeXLSXRangeRef(startCol, rowIndex, endCol, rowIndex))
	}
	addSection := func(title string) {
		row := makeRow(22)
		addMergedValue(&row, 0, overviewCols-1, title, 3)
		sheet.Rows = append(sheet.Rows, row)
	}

	title := strings.TrimSpace(spec.Title)
	if title == "" {
		title = "Workbook Overview"
	}
	titleRow := makeRow(30)
	addMergedValue(&titleRow, 0, overviewCols-1, title, 1)
	sheet.Rows = append(sheet.Rows, titleRow)

	subtitleParts := make([]string, 0, 3)
	if subtitle := strings.TrimSpace(spec.Subtitle); subtitle != "" {
		subtitleParts = append(subtitleParts, subtitle)
	}
	subtitleParts = append(subtitleParts, "Generated "+time.Now().Format("2006-01-02"))
	subtitleParts = append(subtitleParts, "Theme "+spec.Theme.Name)
	subtitleRow := makeRow(20)
	addMergedValue(&subtitleRow, 0, overviewCols-1, strings.Join(subtitleParts, "  •  "), 2)
	sheet.Rows = append(sheet.Rows, subtitleRow, makeRow(10))

	if len(spec.Stats) > 0 {
		addSection("Snapshot")
		for start := 0; start < len(spec.Stats); start += 3 {
			labelRow := makeRow(18)
			valueRow := makeRow(28)
			for offset := 0; offset < 3 && start+offset < len(spec.Stats); offset++ {
				stat := spec.Stats[start+offset]
				tone := officeNormalizeToneName(stat.Tone)
				if tone == "" {
					tone = officeClassifyTone(stat.Value)
				}
				labelStyle, valueStyle := officeStatCardStyles(tone)
				col := offset * 2
				labelRow.Cells[col] = officeXLSXCell{Value: stat.Label, Style: labelStyle, ForceString: true}
				valueRow.Cells[col] = officeXLSXCell{Value: stat.Value, Style: valueStyle, ForceString: true}
				rowIndex := len(sheet.Rows) + 1
				sheet.Merges = append(sheet.Merges,
					officeXLSXRangeRef(col, rowIndex, col+1, rowIndex),
					officeXLSXRangeRef(col, rowIndex+1, col+1, rowIndex+1),
				)
			}
			sheet.Rows = append(sheet.Rows, labelRow, valueRow, makeRow(8))
		}
	}

	addSection("Sheets")
	header := makeRow(22)
	header.Cells[0] = officeXLSXCell{Value: "Sheet", Style: 5, ForceString: true}
	header.Cells[1] = officeXLSXCell{Value: "Rows", Style: 5, ForceString: true}
	header.Cells[2] = officeXLSXCell{Value: "Columns", Style: 5, ForceString: true}
	header.Cells[3] = officeXLSXCell{Value: "Freeze", Style: 5, ForceString: true}
	header.Cells[4] = officeXLSXCell{Value: "Filter", Style: 5, ForceString: true}
	header.Cells[5] = officeXLSXCell{Value: "Theme", Style: 5, ForceString: true}
	sheet.Rows = append(sheet.Rows, header)
	for idx, item := range spec.Sheets {
		row := makeRow(20)
		if idx%2 == 0 {
			row.Cells[0] = officeXLSXCell{Value: item.Name, Style: 6, ForceString: true}
			row.Cells[1] = officeXLSXCell{Value: len(item.Rows), Style: 10}
			row.Cells[2] = officeXLSXCell{Value: len(item.Columns), Style: 10}
			row.Cells[3] = officeXLSXCell{Value: firstNonEmptyOfficeString(item.Freeze, "A2"), Style: 6, ForceString: true}
			row.Cells[4] = officeXLSXCell{Value: officeBoolWord(item.Filter), Style: 6, ForceString: true}
			row.Cells[5] = officeXLSXCell{Value: spec.Theme.Name, Style: 15, ForceString: true}
		} else {
			row.Cells[0] = officeXLSXCell{Value: item.Name, Style: 7, ForceString: true}
			row.Cells[1] = officeXLSXCell{Value: len(item.Rows), Style: 11}
			row.Cells[2] = officeXLSXCell{Value: len(item.Columns), Style: 11}
			row.Cells[3] = officeXLSXCell{Value: firstNonEmptyOfficeString(item.Freeze, "A2"), Style: 7, ForceString: true}
			row.Cells[4] = officeXLSXCell{Value: officeBoolWord(item.Filter), Style: 7, ForceString: true}
			row.Cells[5] = officeXLSXCell{Value: spec.Theme.Name, Style: 15, ForceString: true}
		}
		sheet.Rows = append(sheet.Rows, row)
	}

	if len(spec.Notes) > 0 {
		sheet.Rows = append(sheet.Rows, makeRow(10))
		addSection("Notes")
		for _, note := range spec.Notes {
			note = strings.TrimSpace(note)
			if note == "" {
				continue
			}
			row := makeRow(34)
			addMergedValue(&row, 0, overviewCols-1, "• "+note, 4)
			sheet.Rows = append(sheet.Rows, row)
		}
	}

	return sheet
}

func officeBuildDataSheet(theme officeTheme, spec officeSheetSpec, used map[string]int) officeXLSXSheetBuild {
	name, columns := officePrepareDataSheet(spec.Name, spec, used)

	rows := make([]officeXLSXRow, 0, len(spec.Rows)+1)
	header := officeXLSXRow{
		Height: 22,
		Cells:  make([]officeXLSXCell, len(columns)),
	}
	for idx, column := range columns {
		header.Cells[idx] = officeXLSXCell{Value: column.Header, Style: 5, ForceString: true}
	}
	rows = append(rows, header)

	for rowIndex, raw := range spec.Rows {
		row := officeXLSXRow{
			Height: 20,
			Cells:  make([]officeXLSXCell, len(columns)),
		}
		for colIndex, column := range columns {
			var rawValue interface{}
			if colIndex < len(raw) {
				rawValue = raw[colIndex]
			}
			cellInput, _ := officeParseStructuredCell(rawValue)
			value := rawValue
			if cellInput.HasShape {
				value = cellInput.Value
			}
			style := officeXLSXDataStyle(column, rowIndex, rawValue)
			if cellInput.HasShape {
				if formattedStyle := officeXLSXFormatStyle(cellInput.Format); formattedStyle > 0 {
					style = formattedStyle
				}
			}
			row.Cells[colIndex] = officeXLSXCell{
				Value:       value,
				Formula:     cellInput.Formula,
				Type:        cellInput.Type,
				Format:      cellInput.Format,
				Style:       style,
				ForceString: officeShouldWriteStringCell(column, rawValue, cellInput),
			}
		}
		rows = append(rows, row)
	}

	freeze, autoFilter := officeDataSheetViewSettings(spec, len(columns), len(rows))
	widths := officeDataSheetWidths(columns, spec.Rows)

	return officeXLSXSheetBuild{
		Name:       name,
		Rows:       rows,
		ColWidths:  widths,
		Freeze:     freeze,
		AutoFilter: autoFilter,
		TabColor:   theme.Primary,
	}
}

func officeBuildDataSheetArtifact(theme officeTheme, spec officeSheetSpec, used map[string]int) officeXLSXSheetArtifact {
	if officeSheetRowsContainFormula(spec.Rows) {
		sheet := officeBuildDataSheet(theme, spec, used)
		return officeXLSXSheetArtifact{
			Name: sheet.Name,
			XML:  officeXLSXWorksheetXML(sheet),
		}
	}
	name, columns := officePrepareDataSheet(spec.Name, spec, used)
	freeze, autoFilter := officeDataSheetViewSettings(spec, len(columns), len(spec.Rows)+1)
	widths := officeDataSheetWidths(columns, spec.Rows)

	var sb strings.Builder
	sb.Grow(256 + len(columns)*64 + len(spec.Rows)*len(columns)*48)
	officeAppendXLSXDataSheetXML(&sb, theme, columns, widths, freeze, autoFilter, spec.Rows)
	return officeXLSXSheetArtifact{
		Name: name,
		XML:  sb.String(),
	}
}

func officeBuildDataSheetZipEntry(theme officeTheme, spec officeSheetSpec, used map[string]int, path string) (string, officeZipEntry) {
	if officeSheetRowsContainFormula(spec.Rows) {
		sheet := officeBuildDataSheet(theme, spec, used)
		return sheet.Name, officeZipEntry{
			Name:     strings.TrimSpace(path),
			SizeHint: officeEstimateXLSXWorksheetXMLSize(sheet),
			Content:  officeXLSXWorksheetXML(sheet),
		}
	}
	name, columns := officePrepareDataSheet(spec.Name, spec, used)
	freeze, autoFilter := officeDataSheetViewSettings(spec, len(columns), len(spec.Rows)+1)
	widths := officeDataSheetWidths(columns, spec.Rows)
	sizeHint := 256 + len(columns)*64 + len(spec.Rows)*len(columns)*48
	return name, officeZipEntry{
		Name:     strings.TrimSpace(path),
		SizeHint: sizeHint,
		WriteTo: func(w io.Writer) error {
			return officeWriteXLSXDataSheet(w, theme, columns, widths, freeze, autoFilter, spec.Rows)
		},
	}
}

func officeAppendXLSXDataSheetXML(sb *strings.Builder, theme officeTheme, columns []officeColumnSpec, widths []float64, freeze, autoFilter string, rows [][]interface{}) {
	lastCol := len(columns)
	if lastCol == 0 {
		lastCol = 1
	}
	lastRow := len(rows) + 1
	if lastRow == 0 {
		lastRow = 1
	}

	sb.WriteString(`<?xml version="1.0" encoding="UTF-8"?>`)
	sb.WriteString(`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">`)
	if color := officeHex(theme.Primary); color != "" {
		sb.WriteString(`<sheetPr><tabColor rgb="`)
		sb.WriteString(officeARGB(color))
		sb.WriteString(`"/></sheetPr>`)
	}
	sb.WriteString(`<dimension ref="`)
	officeAppendXLSXRangeRef(sb, 0, 1, lastCol-1, lastRow)
	sb.WriteString(`"/>`)
	sb.WriteString(`<sheetViews><sheetView workbookViewId="0" tabSelected="1">`)
	officeAppendXLSXFreezePaneXML(sb, freeze)
	sb.WriteString(`</sheetView></sheetViews>`)
	sb.WriteString(`<sheetFormatPr defaultRowHeight="18"/>`)
	if len(widths) > 0 {
		sb.WriteString(`<cols>`)
		for idx, width := range widths {
			sb.WriteString(`<col min="`)
			officeAppendInt(sb, idx+1)
			sb.WriteString(`" max="`)
			officeAppendInt(sb, idx+1)
			sb.WriteString(`" width="`)
			officeAppendFloat(sb, officeClampFloat(width, 8, 48), 2)
			sb.WriteString(`" customWidth="1"/>`)
		}
		sb.WriteString(`</cols>`)
	}
	sb.WriteString(`<sheetData>`)
	sb.WriteString(`<row r="1" ht="22.00" customHeight="1">`)
	for colIndex, column := range columns {
		officeAppendXLSXCellXML(sb, 1, colIndex, officeXLSXCell{
			Value:       column.Header,
			Style:       5,
			ForceString: true,
		})
	}
	sb.WriteString(`</row>`)
	for rowIndex, raw := range rows {
		sb.WriteString(`<row r="`)
		officeAppendInt(sb, rowIndex+2)
		sb.WriteString(`" ht="20.00" customHeight="1">`)
		for colIndex, column := range columns {
			var rawValue interface{}
			if colIndex < len(raw) {
				rawValue = raw[colIndex]
			}
			cellInput, _ := officeParseStructuredCell(rawValue)
			value := rawValue
			if cellInput.HasShape {
				value = cellInput.Value
			}
			style := officeXLSXDataStyle(column, rowIndex, rawValue)
			if cellInput.HasShape {
				if formattedStyle := officeXLSXFormatStyle(cellInput.Format); formattedStyle > 0 {
					style = formattedStyle
				}
			}
			officeAppendXLSXCellXML(sb, rowIndex+2, colIndex, officeXLSXCell{
				Value:       value,
				Formula:     cellInput.Formula,
				Type:        cellInput.Type,
				Format:      cellInput.Format,
				Style:       style,
				ForceString: officeShouldWriteStringCell(column, rawValue, cellInput),
			})
		}
		sb.WriteString(`</row>`)
	}
	sb.WriteString(`</sheetData>`)
	if strings.TrimSpace(autoFilter) != "" {
		sb.WriteString(`<autoFilter ref="`)
		officeAppendXMLText(sb, autoFilter)
		sb.WriteString(`"/>`)
	}
	sb.WriteString(`<pageMargins left="0.35" right="0.35" top="0.55" bottom="0.55" header="0.3" footer="0.3"/>`)
	sb.WriteString(`</worksheet>`)
}

type officeStreamWriter struct {
	w   *bufio.Writer
	err error
}

type officeStreamResolvedCellValue struct {
	cellType   string
	inlineText string
	scalarText string
	number     float64
	mode       uint8
}

const (
	officeStreamCellValueNone uint8 = iota
	officeStreamCellValueNumber
	officeStreamCellValueScalar
	officeStreamCellValueInline
)

func officeWriteXLSXDataSheet(w io.Writer, theme officeTheme, columns []officeColumnSpec, widths []float64, freeze, autoFilter string, rows [][]interface{}) error {
	bufWriter := officeAcquireStreamBufioWriter(w)
	defer officeReleaseStreamBufioWriter(bufWriter)

	writer := officeStreamWriter{w: bufWriter}
	writer.writeDataSheetXML(theme, columns, widths, freeze, autoFilter, rows)
	if writer.err != nil {
		return writer.err
	}
	return writer.w.Flush()
}

func officeAcquireStreamBufioWriter(target io.Writer) *bufio.Writer {
	writer := officeStreamBufioWriterPool.Get().(*bufio.Writer)
	writer.Reset(target)
	return writer
}

func officeReleaseStreamBufioWriter(writer *bufio.Writer) {
	if writer == nil {
		return
	}
	writer.Reset(io.Discard)
	officeStreamBufioWriterPool.Put(writer)
}

func (w *officeStreamWriter) writeDataSheetXML(theme officeTheme, columns []officeColumnSpec, widths []float64, freeze, autoFilter string, rows [][]interface{}) {
	lastCol := len(columns)
	if lastCol == 0 {
		lastCol = 1
	}
	lastRow := len(rows) + 1
	if lastRow == 0 {
		lastRow = 1
	}

	w.writeString(`<?xml version="1.0" encoding="UTF-8"?>`)
	w.writeString(`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">`)
	if color := officeHex(theme.Primary); color != "" {
		w.writeString(`<sheetPr><tabColor rgb="`)
		w.writeString(officeARGB(color))
		w.writeString(`"/></sheetPr>`)
	}
	w.writeString(`<dimension ref="`)
	w.writeRangeRef(0, 1, lastCol-1, lastRow)
	w.writeString(`"/>`)
	w.writeString(`<sheetViews><sheetView workbookViewId="0" tabSelected="1">`)
	w.writeFreezePaneXML(freeze)
	w.writeString(`</sheetView></sheetViews>`)
	w.writeString(`<sheetFormatPr defaultRowHeight="18"/>`)
	if len(widths) > 0 {
		w.writeString(`<cols>`)
		for idx, width := range widths {
			w.writeString(`<col min="`)
			w.writeInt(idx + 1)
			w.writeString(`" max="`)
			w.writeInt(idx + 1)
			w.writeString(`" width="`)
			w.writeFloat(officeClampFloat(width, 8, 48), 2)
			w.writeString(`" customWidth="1"/>`)
		}
		w.writeString(`</cols>`)
	}
	w.writeString(`<sheetData>`)
	w.writeString(`<row r="1" ht="22.00" customHeight="1">`)
	for colIndex, column := range columns {
		w.writeCellXML(1, colIndex, officeXLSXCell{
			Value:       column.Header,
			Style:       5,
			ForceString: true,
		})
	}
	w.writeString(`</row>`)
	for rowIndex, raw := range rows {
		w.writeString(`<row r="`)
		w.writeInt(rowIndex + 2)
		w.writeString(`" ht="20.00" customHeight="1">`)
		for colIndex, column := range columns {
			var rawValue interface{}
			if colIndex < len(raw) {
				rawValue = raw[colIndex]
			}
			cellInput, _ := officeParseStructuredCell(rawValue)
			value := rawValue
			if cellInput.HasShape {
				value = cellInput.Value
			}
			style := officeXLSXDataStyle(column, rowIndex, rawValue)
			if cellInput.HasShape {
				if formattedStyle := officeXLSXFormatStyle(cellInput.Format); formattedStyle > 0 {
					style = formattedStyle
				}
			}
			w.writeCellXML(rowIndex+2, colIndex, officeXLSXCell{
				Value:       value,
				Formula:     cellInput.Formula,
				Type:        cellInput.Type,
				Format:      cellInput.Format,
				Style:       style,
				ForceString: officeShouldWriteStringCell(column, rawValue, cellInput),
			})
		}
		w.writeString(`</row>`)
	}
	w.writeString(`</sheetData>`)
	if strings.TrimSpace(autoFilter) != "" {
		w.writeString(`<autoFilter ref="`)
		w.writeXMLText(autoFilter)
		w.writeString(`"/>`)
	}
	w.writeString(`<pageMargins left="0.35" right="0.35" top="0.55" bottom="0.55" header="0.3" footer="0.3"/>`)
	w.writeString(`</worksheet>`)
}

func (w *officeStreamWriter) writeCellXML(rowIndex, colIndex int, cell officeXLSXCell) {
	if w.err != nil {
		return
	}
	format := officeNormalizeCellFormat(cell.Format)
	formula := strings.TrimSpace(cell.Formula)
	value, hasValue := officeResolveStreamCellValue(cell.Value, cell.Type, format, cell.ForceString)
	cellType := officeStreamCellTypeAttr(value, hasValue)

	var start [64]byte
	tag := officeAppendXLSXCellStartBytes(start[:0], rowIndex, colIndex, cell.Style, cellType)
	if formula == "" && !hasValue {
		tag = append(tag, '/', '>')
		w.writeBytes(tag)
		return
	}
	tag = append(tag, '>')
	w.writeBytes(tag)
	if formula != "" {
		w.writeString(`<f>`)
		w.writeXMLText(formula)
		w.writeString(`</f>`)
	}
	if hasValue {
		w.writeResolvedCellValueXML(value)
	}
	w.writeString(`</c>`)
}

func (w *officeStreamWriter) writeResolvedCellValueXML(value officeStreamResolvedCellValue) {
	switch value.mode {
	case officeStreamCellValueInline:
		w.writeString(`<is><t xml:space="preserve">`)
		w.writeXMLText(value.inlineText)
		w.writeString(`</t></is>`)
	case officeStreamCellValueNumber:
		w.writeString(`<v>`)
		w.writeFloat(value.number, -1)
		w.writeString(`</v>`)
	case officeStreamCellValueScalar:
		w.writeString(`<v>`)
		w.writeString(value.scalarText)
		w.writeString(`</v>`)
	}
}

func officeStreamCellTypeAttr(value officeStreamResolvedCellValue, hasValue bool) string {
	if !hasValue {
		return ""
	}
	return value.cellType
}

func officeResolveStreamCellValue(value interface{}, rawType, format string, forceString bool) (officeStreamResolvedCellValue, bool) {
	cellType := strings.ToLower(strings.TrimSpace(rawType))
	switch cellType {
	case "bool", "boolean":
		text := strings.ToLower(strings.TrimSpace(officeCellString(value)))
		if text == "true" || text == "1" {
			return officeStreamResolvedCellValue{cellType: "b", scalarText: "1", mode: officeStreamCellValueScalar}, true
		}
		if text == "false" || text == "0" || text == "" {
			return officeStreamResolvedCellValue{cellType: "b", scalarText: "0", mode: officeStreamCellValueScalar}, true
		}
	case "text", "string", "inline_str", "inline":
		text := officeCellString(value)
		if text == "" {
			return officeStreamResolvedCellValue{}, false
		}
		return officeStreamResolvedCellValue{cellType: "inlineStr", inlineText: text, mode: officeStreamCellValueInline}, true
	case "number", "numeric":
		if number, ok := officeCellNumber(value); ok {
			return officeStreamResolvedCellValue{number: number, mode: officeStreamCellValueNumber}, true
		}
	}

	switch format {
	case "date":
		if serial, ok := officeExcelDateSerial(value, false); ok {
			return officeStreamResolvedCellValue{scalarText: serial, mode: officeStreamCellValueScalar}, true
		}
	case "datetime":
		if serial, ok := officeExcelDateSerial(value, true); ok {
			return officeStreamResolvedCellValue{scalarText: serial, mode: officeStreamCellValueScalar}, true
		}
	case "text":
		text := officeCellString(value)
		if text == "" {
			return officeStreamResolvedCellValue{}, false
		}
		return officeStreamResolvedCellValue{cellType: "inlineStr", inlineText: text, mode: officeStreamCellValueInline}, true
	}

	if !forceString {
		if number, ok := officeCellNumber(value); ok {
			return officeStreamResolvedCellValue{number: number, mode: officeStreamCellValueNumber}, true
		}
	}
	text := officeCellString(value)
	if text == "" {
		return officeStreamResolvedCellValue{}, false
	}
	return officeStreamResolvedCellValue{cellType: "inlineStr", inlineText: text, mode: officeStreamCellValueInline}, true
}

func (w *officeStreamWriter) writeFreezePaneXML(ref string) {
	ref = strings.TrimSpace(ref)
	if ref == "" {
		return
	}
	col, row, ok := officeParseCellRef(ref)
	if !ok || row <= 1 && col <= 1 {
		return
	}
	pane := "bottomLeft"
	if col > 1 && row > 1 {
		pane = "bottomRight"
	} else if col > 1 {
		pane = "topRight"
	}

	w.writeString(`<pane`)
	if col > 1 {
		w.writeString(` xSplit="`)
		w.writeInt(col - 1)
		w.writeString(`"`)
	}
	if row > 1 {
		w.writeString(` ySplit="`)
		w.writeInt(row - 1)
		w.writeString(`"`)
	}
	w.writeString(` topLeftCell="`)
	w.writeXMLText(ref)
	w.writeString(`" activePane="`)
	w.writeString(pane)
	w.writeString(`" state="frozen"/>`)
	w.writeString(`<selection pane="`)
	w.writeString(pane)
	w.writeString(`" activeCell="`)
	w.writeXMLText(ref)
	w.writeString(`" sqref="`)
	w.writeXMLText(ref)
	w.writeString(`"/>`)
}

func (w *officeStreamWriter) writeCellRef(colIndex, rowIndex int) {
	if w.err != nil {
		return
	}
	var buf [24]byte
	w.writeBytes(officeAppendXLSXCellRefBytes(buf[:0], colIndex, rowIndex))
}

func (w *officeStreamWriter) writeRangeRef(startCol, startRow, endCol, endRow int) {
	w.writeCellRef(startCol, startRow)
	w.writeByte(':')
	w.writeCellRef(endCol, endRow)
}

func (w *officeStreamWriter) writeColumnName(index int) {
	if w.err != nil || index < 0 {
		return
	}
	index++
	var buf [16]byte
	pos := len(buf)
	for index > 0 {
		index--
		pos--
		buf[pos] = byte('A' + index%26)
		index /= 26
	}
	_, w.err = w.w.Write(buf[pos:])
}

func (w *officeStreamWriter) writeXMLText(text string) {
	if text == "" || w.err != nil {
		return
	}
	if officeXMLTextCanWriteRawASCII(text) {
		w.writeString(text)
		return
	}
	start := 0
	for i := 0; i < len(text) && w.err == nil; {
		r, width := utf8.DecodeRuneInString(text[i:])
		escape := ""
		switch r {
		case '"':
			escape = "&#34;"
		case '\'':
			escape = "&#39;"
		case '&':
			escape = "&amp;"
		case '<':
			escape = "&lt;"
		case '>':
			escape = "&gt;"
		case '\t':
			escape = "&#x9;"
		case '\n':
			escape = "&#xA;"
		case '\r':
			escape = "&#xD;"
		default:
			if officeXMLRuneAllowed(r) && !(r == utf8.RuneError && width == 1) {
				i += width
				continue
			}
			escape = "\uFFFD"
		}
		if start < i {
			w.writeString(text[start:i])
		}
		w.writeString(escape)
		i += width
		start = i
	}
	if start < len(text) {
		w.writeString(text[start:])
	}
}

func (w *officeStreamWriter) writeInt(value int) {
	if w.err != nil {
		return
	}
	var buf [20]byte
	_, w.err = w.w.Write(strconv.AppendInt(buf[:0], int64(value), 10))
}

func (w *officeStreamWriter) writeFloat(value float64, precision int) {
	if w.err != nil {
		return
	}
	var buf [32]byte
	_, w.err = w.w.Write(strconv.AppendFloat(buf[:0], value, 'f', precision, 64))
}

func (w *officeStreamWriter) writeByte(value byte) {
	if w.err != nil {
		return
	}
	w.err = w.w.WriteByte(value)
}

func (w *officeStreamWriter) writeBytes(value []byte) {
	if w.err != nil || len(value) == 0 {
		return
	}
	_, w.err = w.w.Write(value)
}

func (w *officeStreamWriter) writeString(value string) {
	if w.err != nil || value == "" {
		return
	}
	_, w.err = w.w.WriteString(value)
}

func officeUniqueSheetName(raw string, used map[string]int) string {
	base := officeSanitizeSheetName(raw)
	if base == "" {
		base = "Sheet"
	}
	count := used[base]
	if count == 0 {
		used[base] = 1
		return base
	}
	for idx := count + 1; ; idx++ {
		suffix := fmt.Sprintf(" %d", idx)
		candidate := base
		if len([]rune(candidate))+len([]rune(suffix)) > 31 {
			candidate = string([]rune(candidate)[:31-len([]rune(suffix))])
		}
		candidate += suffix
		if used[candidate] == 0 {
			used[base] = idx
			used[candidate] = 1
			return candidate
		}
	}
}

func officeSanitizeSheetName(raw string) string {
	replacer := strings.NewReplacer("\\", " ", "/", " ", "?", " ", "*", " ", "[", " ", "]", " ", ":", " ")
	clean := strings.TrimSpace(replacer.Replace(raw))
	clean = strings.Join(strings.Fields(clean), " ")
	if clean == "" {
		return ""
	}
	runes := []rune(clean)
	if len(runes) > 31 {
		return string(runes[:31])
	}
	return clean
}

func officeInferXLSXColumnWidth(column officeColumnSpec, rows [][]interface{}, columnIndex int) float64 {
	if column.Width > 0 {
		return officeClampFloat(column.Width, 8, 48)
	}
	maxLen := officeMaxLineRunes(column.Header)
	sample := len(rows)
	if sample > 40 {
		sample = 40
	}
	for idx := 0; idx < sample; idx++ {
		if columnIndex >= len(rows[idx]) {
			continue
		}
		text := officeCellString(rows[idx][columnIndex])
		if lineLen := officeMaxLineRunes(text); lineLen > maxLen {
			maxLen = lineLen
		}
	}
	width := float64(maxLen + 2)
	switch strings.ToLower(strings.TrimSpace(column.Kind)) {
	case "number":
		return officeClampFloat(width, 10, 16)
	case "wrap":
		return officeClampFloat(width+4, 18, 36)
	default:
		if maxLen > 28 {
			return officeClampFloat(width+2, 14, 42)
		}
		return officeClampFloat(width, 10, 24)
	}
}

func officeMaxLineRunes(text string) int {
	lines := strings.Split(strings.ReplaceAll(text, "\r\n", "\n"), "\n")
	maxLen := 0
	for _, line := range lines {
		if l := runeCount(strings.TrimSpace(line)); l > maxLen {
			maxLen = l
		}
	}
	return maxLen
}

func officeXLSXDataStyle(column officeColumnSpec, rowIndex int, value interface{}) int {
	alt := rowIndex%2 == 1
	kind := strings.ToLower(strings.TrimSpace(column.Kind))
	switch kind {
	case "tone":
		if tone := officeClassifyTone(value); tone != "" {
			return officeToneDataStyle(tone)
		}
	case "delta":
		if tone := officeClassifyDeltaTone(value); tone != "" {
			return officeToneDataStyle(tone)
		}
	case "number":
		if alt {
			return 11
		}
		return 10
	case "wrap":
		if alt {
			return 9
		}
		return 8
	}

	text := officeCellString(value)
	if strings.Contains(text, "\n") || runeCount(text) > 40 {
		if alt {
			return 9
		}
		return 8
	}
	if alt {
		return 7
	}
	return 6
}

func officeShouldWriteNumericCell(column officeColumnSpec, value interface{}) bool {
	if cell, ok := officeParseStructuredCell(value); ok {
		value = cell.Value
	}
	if value == nil {
		return false
	}
	switch strings.ToLower(strings.TrimSpace(column.Kind)) {
	case "tone", "delta":
		return false
	}
	_, ok := officeCellNumber(value)
	return ok
}

func officeShouldWriteStringCell(column officeColumnSpec, raw interface{}, cell officeStructuredCell) bool {
	if cell.HasShape {
		if strings.TrimSpace(cell.Formula) != "" {
			switch cell.Type {
			case "text", "string", "inline_str", "inline":
				return true
			case "number", "numeric", "bool", "boolean":
				return false
			}
			return officeNormalizeCellFormat(cell.Format) == "text"
		}
		switch cell.Type {
		case "text", "string", "inline_str", "inline":
			return true
		case "number", "numeric":
			return false
		case "bool", "boolean":
			return false
		}
		switch officeNormalizeCellFormat(cell.Format) {
		case "date", "datetime", "text":
			return true
		}
		return !officeShouldWriteNumericCell(column, cell.Value)
	}
	return !officeShouldWriteNumericCell(column, raw)
}

func officeStatCardStyles(tone string) (int, int) {
	switch tone {
	case "success":
		return 18, 19
	case "warning":
		return 20, 21
	case "danger":
		return 22, 23
	case "muted":
		return 24, 25
	default:
		return 16, 17
	}
}

func officeToneDataStyle(tone string) int {
	switch tone {
	case "success":
		return 12
	case "warning":
		return 13
	case "danger":
		return 14
	default:
		return 15
	}
}

func officeNormalizeCellFormat(format string) string {
	switch strings.ToLower(strings.TrimSpace(format)) {
	case "general", "integer", "decimal", "currency", "percent", "date", "datetime", "text":
		return strings.ToLower(strings.TrimSpace(format))
	default:
		return ""
	}
}

func officeXLSXFormatStyle(format string) int {
	switch officeNormalizeCellFormat(format) {
	case "integer":
		return 26
	case "decimal":
		return 27
	case "currency":
		return 28
	case "percent":
		return 29
	case "date":
		return 30
	case "datetime":
		return 31
	case "text":
		return 32
	default:
		return 0
	}
}

func officeExcelDateSerial(value interface{}, withTime bool) (string, bool) {
	switch typed := value.(type) {
	case string:
		text := strings.TrimSpace(typed)
		if text == "" {
			return "", false
		}
		layouts := []string{
			time.RFC3339,
			"2006-01-02 15:04:05",
			"2006-01-02 15:04",
			"2006-01-02",
		}
		for _, layout := range layouts {
			ts, err := time.Parse(layout, text)
			if err != nil {
				continue
			}
			return officeTimeToExcelSerial(ts, withTime), true
		}
	case time.Time:
		return officeTimeToExcelSerial(typed, withTime), true
	}
	return "", false
}

func officeTimeToExcelSerial(ts time.Time, withTime bool) string {
	base := time.Date(1899, 12, 30, 0, 0, 0, 0, time.UTC)
	ts = ts.UTC()
	if !withTime {
		ts = time.Date(ts.Year(), ts.Month(), ts.Day(), 0, 0, 0, 0, time.UTC)
	}
	return officeNumericXMLValue(ts.Sub(base).Hours() / 24)
}

func officeNormalizeToneName(raw string) string {
	value := strings.ToLower(strings.TrimSpace(raw))
	switch {
	case value == "":
		return ""
	case officeContainsAny(value, "success", "positive", "good", "pass", "green", "通过", "成功", "正向", "良好"):
		return "success"
	case officeContainsAny(value, "warning", "warn", "attention", "watch", "amber", "中等", "提醒", "注意", "预警"):
		return "warning"
	case officeContainsAny(value, "danger", "risk", "critical", "error", "fail", "red", "风险", "严重", "失败", "危险"):
		return "danger"
	case officeContainsAny(value, "muted", "neutral", "secondary", "subtle", "中性", "次要", "弱化"):
		return "muted"
	default:
		return "primary"
	}
}

func officeClassifyTone(value interface{}) string {
	text := strings.ToLower(strings.TrimSpace(officeCellString(value)))
	switch {
	case text == "":
		return ""
	case officeContainsAny(text,
		"critical", "blocker", "failed", "fail", "error", "down", "poor", "bad", "high risk", "red",
		"严重", "阻塞", "失败", "故障", "异常", "高风险", "较差", "不可用",
	):
		return "danger"
	case officeContainsAny(text,
		"warning", "warn", "attention", "monitor", "needs work", "partial", "pending", "medium",
		"提醒", "注意", "需优化", "待观察", "一般", "中等", "待处理",
	):
		return "warning"
	case officeContainsAny(text,
		"success", "passed", "pass", "healthy", "good", "excellent", "resolved", "approved", "stable", "done", "yes", "green",
		"通过", "成功", "健康", "良好", "优秀", "已解决", "已完成", "稳定", "正常",
	):
		return "success"
	default:
		return "muted"
	}
}

func officeClassifyDeltaTone(value interface{}) string {
	if number, ok := officeCellNumber(value); ok {
		switch {
		case number > 0:
			return "success"
		case number < 0:
			return "danger"
		default:
			return "muted"
		}
	}
	text := strings.TrimSpace(officeCellString(value))
	switch {
	case strings.HasPrefix(text, "+"):
		return "success"
	case strings.HasPrefix(text, "-"):
		return "danger"
	default:
		return officeClassifyTone(text)
	}
}

type officeXLSXResolvedCellValue struct {
	CellType     string
	Text         string
	InlineString bool
}

func officeEstimateXLSXWorksheetXMLSize(sheet officeXLSXSheetBuild) int {
	cellCount := 0
	mergeTextLen := 0
	for _, row := range sheet.Rows {
		cellCount += len(row.Cells)
	}
	for _, merge := range sheet.Merges {
		mergeTextLen += len(merge)
	}
	return 512 +
		len(sheet.Rows)*32 +
		cellCount*56 +
		len(sheet.ColWidths)*48 +
		len(sheet.ColStyles)*16 +
		len(sheet.Merges)*24 +
		mergeTextLen +
		len(sheet.AutoFilter)
}

func officeXLSXWorksheetXML(sheet officeXLSXSheetBuild) string {
	var sb strings.Builder
	sb.Grow(officeEstimateXLSXWorksheetXMLSize(sheet))
	officeAppendXLSXWorksheetXML(&sb, sheet)
	return sb.String()
}

func officeAppendXLSXWorksheetXML(sb *strings.Builder, sheet officeXLSXSheetBuild) {
	sheet = officeResolveSupportedFormulaCaches(sheet)
	lastRow := len(sheet.Rows)
	lastCol := len(sheet.ColWidths)
	if len(sheet.ColStyles) > lastCol {
		lastCol = len(sheet.ColStyles)
	}
	if lastCol == 0 {
		for _, row := range sheet.Rows {
			if len(row.Cells) > lastCol {
				lastCol = len(row.Cells)
			}
		}
	}
	if lastCol == 0 {
		lastCol = 1
	}
	if lastRow == 0 {
		lastRow = 1
	}

	sb.WriteString(`<?xml version="1.0" encoding="UTF-8"?>`)
	sb.WriteString(`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">`)
	if color := officeHex(sheet.TabColor); color != "" {
		sb.WriteString(`<sheetPr><tabColor rgb="`)
		sb.WriteString(officeARGB(color))
		sb.WriteString(`"/></sheetPr>`)
	}
	sb.WriteString(`<dimension ref="`)
	officeAppendXLSXRangeRef(sb, 0, 1, lastCol-1, lastRow)
	sb.WriteString(`"/>`)
	sb.WriteString(`<sheetViews><sheetView workbookViewId="0"`)
	if lastRow > 0 {
		sb.WriteString(` tabSelected="1"`)
	}
	sb.WriteString(`>`)
	officeAppendXLSXFreezePaneXML(sb, sheet.Freeze)
	sb.WriteString(`</sheetView></sheetViews>`)
	sb.WriteString(`<sheetFormatPr defaultRowHeight="18"/>`)
	colCount := len(sheet.ColWidths)
	if len(sheet.ColStyles) > colCount {
		colCount = len(sheet.ColStyles)
	}
	if colCount > 0 {
		sb.WriteString(`<cols>`)
		for idx := 0; idx < colCount; idx++ {
			width := 12.0
			if idx < len(sheet.ColWidths) && sheet.ColWidths[idx] > 0 {
				width = sheet.ColWidths[idx]
			}
			sb.WriteString(`<col min="`)
			officeAppendInt(sb, idx+1)
			sb.WriteString(`" max="`)
			officeAppendInt(sb, idx+1)
			sb.WriteString(`" width="`)
			officeAppendFloat(sb, officeClampFloat(width, 8, 48), 2)
			sb.WriteString(`" customWidth="1"`)
			if idx < len(sheet.ColStyles) && sheet.ColStyles[idx] > 0 {
				sb.WriteString(` style="`)
				officeAppendInt(sb, sheet.ColStyles[idx])
				sb.WriteString(`" customFormat="1"`)
			}
			sb.WriteString(`/>`)
		}
		sb.WriteString(`</cols>`)
	}
	sb.WriteString(`<sheetData>`)
	for rowIndex, row := range sheet.Rows {
		sb.WriteString(`<row r="`)
		officeAppendInt(sb, rowIndex+1)
		sb.WriteString(`"`)
		if row.Height > 0 {
			sb.WriteString(` ht="`)
			officeAppendFloat(sb, row.Height, 2)
			sb.WriteString(`" customHeight="1"`)
		}
		sb.WriteString(`>`)
		for colIndex, cell := range row.Cells {
			if cell.Value == nil && cell.Style == 0 {
				continue
			}
			officeAppendXLSXCellXML(sb, rowIndex+1, colIndex, cell)
		}
		sb.WriteString(`</row>`)
	}
	sb.WriteString(`</sheetData>`)
	if strings.TrimSpace(sheet.AutoFilter) != "" {
		sb.WriteString(`<autoFilter ref="`)
		officeAppendXMLText(sb, sheet.AutoFilter)
		sb.WriteString(`"/>`)
	}
	if len(sheet.Merges) > 0 {
		sb.WriteString(`<mergeCells count="`)
		officeAppendInt(sb, len(sheet.Merges))
		sb.WriteString(`">`)
		for _, merge := range sheet.Merges {
			sb.WriteString(`<mergeCell ref="`)
			officeAppendXMLText(sb, merge)
			sb.WriteString(`"/>`)
		}
		sb.WriteString(`</mergeCells>`)
	}
	sb.WriteString(`<pageMargins left="0.35" right="0.35" top="0.55" bottom="0.55" header="0.3" footer="0.3"/>`)
	sb.WriteString(`</worksheet>`)
}

func officeXLSXCellXML(rowIndex, colIndex int, cell officeXLSXCell) string {
	var sb strings.Builder
	sb.Grow(64)
	officeAppendXLSXCellXML(&sb, rowIndex, colIndex, cell)
	return sb.String()
}

func officeAppendXLSXCellXML(sb *strings.Builder, rowIndex, colIndex int, cell officeXLSXCell) {
	format := officeNormalizeCellFormat(cell.Format)
	formula := strings.TrimSpace(cell.Formula)
	value, hasValue := officeResolveXLSXCellValue(cell.Value, cell.Type, format, cell.ForceString)

	sb.WriteString(`<c r="`)
	officeAppendXLSXCellRef(sb, colIndex, rowIndex)
	sb.WriteString(`"`)
	if cell.Style > 0 {
		sb.WriteString(` s="`)
		officeAppendInt(sb, cell.Style)
		sb.WriteString(`"`)
	}
	if hasValue && value.CellType != "" {
		sb.WriteString(` t="`)
		sb.WriteString(value.CellType)
		sb.WriteString(`"`)
	}
	if formula == "" && !hasValue {
		sb.WriteString(`/>`)
		return
	}
	sb.WriteString(`>`)
	if formula != "" {
		sb.WriteString(`<f>`)
		officeAppendXMLText(sb, formula)
		sb.WriteString(`</f>`)
	}
	if hasValue {
		officeAppendResolvedXLSXCellValueXML(sb, value)
	}
	sb.WriteString(`</c>`)
}

func officeXLSXCellValueXML(value interface{}, rawType, format string, forceString bool) (string, string, bool) {
	resolved, ok := officeResolveXLSXCellValue(value, rawType, format, forceString)
	if !ok {
		return "", "", false
	}
	var sb strings.Builder
	sb.Grow(len(resolved.Text) + 32)
	officeAppendResolvedXLSXCellValueXML(&sb, resolved)
	return sb.String(), resolved.CellType, true
}

func officeResolveXLSXCellValue(value interface{}, rawType, format string, forceString bool) (officeXLSXResolvedCellValue, bool) {
	cellType := strings.ToLower(strings.TrimSpace(rawType))
	switch cellType {
	case "bool", "boolean":
		text := strings.ToLower(strings.TrimSpace(officeCellString(value)))
		if text == "true" || text == "1" {
			return officeXLSXResolvedCellValue{CellType: "b", Text: "1"}, true
		}
		if text == "false" || text == "0" || text == "" {
			return officeXLSXResolvedCellValue{CellType: "b", Text: "0"}, true
		}
	case "text", "string", "inline_str", "inline":
		text := officeCellString(value)
		if text == "" {
			return officeXLSXResolvedCellValue{}, false
		}
		return officeXLSXResolvedCellValue{CellType: "inlineStr", Text: text, InlineString: true}, true
	case "number", "numeric":
		if number, ok := officeCellNumber(value); ok {
			return officeXLSXResolvedCellValue{Text: officeNumericXMLValue(number)}, true
		}
	}

	switch format {
	case "date":
		if serial, ok := officeExcelDateSerial(value, false); ok {
			return officeXLSXResolvedCellValue{Text: serial}, true
		}
	case "datetime":
		if serial, ok := officeExcelDateSerial(value, true); ok {
			return officeXLSXResolvedCellValue{Text: serial}, true
		}
	case "text":
		text := officeCellString(value)
		if text == "" {
			return officeXLSXResolvedCellValue{}, false
		}
		return officeXLSXResolvedCellValue{CellType: "inlineStr", Text: text, InlineString: true}, true
	}

	if !forceString {
		if number, ok := officeCellNumber(value); ok {
			return officeXLSXResolvedCellValue{Text: officeNumericXMLValue(number)}, true
		}
	}
	text := officeCellString(value)
	if text == "" {
		return officeXLSXResolvedCellValue{}, false
	}
	return officeXLSXResolvedCellValue{CellType: "inlineStr", Text: text, InlineString: true}, true
}

func officeAppendResolvedXLSXCellValueXML(sb *strings.Builder, value officeXLSXResolvedCellValue) {
	if value.InlineString {
		sb.WriteString(`<is><t xml:space="preserve">`)
		officeAppendXMLText(sb, value.Text)
		sb.WriteString(`</t></is>`)
		return
	}
	sb.WriteString(`<v>`)
	sb.WriteString(value.Text)
	sb.WriteString(`</v>`)
}

func officeXLSXFreezePaneXML(ref string) string {
	var sb strings.Builder
	sb.Grow(len(ref) + 64)
	officeAppendXLSXFreezePaneXML(&sb, ref)
	return sb.String()
}

func officeAppendXLSXFreezePaneXML(sb *strings.Builder, ref string) {
	ref = strings.TrimSpace(ref)
	if ref == "" {
		return
	}
	col, row, ok := officeParseCellRef(ref)
	if !ok || row <= 1 && col <= 1 {
		return
	}
	pane := "bottomLeft"
	if col > 1 && row > 1 {
		pane = "bottomRight"
	} else if col > 1 {
		pane = "topRight"
	}

	sb.WriteString(`<pane`)
	if col > 1 {
		sb.WriteString(` xSplit="`)
		officeAppendInt(sb, col-1)
		sb.WriteString(`"`)
	}
	if row > 1 {
		sb.WriteString(` ySplit="`)
		officeAppendInt(sb, row-1)
		sb.WriteString(`"`)
	}
	sb.WriteString(` topLeftCell="`)
	officeAppendXMLText(sb, ref)
	sb.WriteString(`" activePane="`)
	sb.WriteString(pane)
	sb.WriteString(`" state="frozen"/>`)
	sb.WriteString(`<selection pane="`)
	sb.WriteString(pane)
	sb.WriteString(`" activeCell="`)
	officeAppendXMLText(sb, ref)
	sb.WriteString(`" sqref="`)
	officeAppendXMLText(sb, ref)
	sb.WriteString(`"/>`)
}

func officeParseCellRef(ref string) (int, int, bool) {
	ref = strings.TrimSpace(ref)
	if ref == "" {
		return 0, 0, false
	}
	col := 0
	row := 0
	seenLetter := false
	for _, r := range ref {
		switch {
		case r >= 'A' && r <= 'Z':
			col = col*26 + int(r-'A'+1)
			seenLetter = true
		case r >= 'a' && r <= 'z':
			col = col*26 + int(r-'a'+1)
			seenLetter = true
		case r >= '0' && r <= '9':
			if !seenLetter {
				return 0, 0, false
			}
			row = row*10 + int(r-'0')
		default:
			return 0, 0, false
		}
	}
	if col <= 0 || row <= 0 {
		return 0, 0, false
	}
	return col, row, true
}

func officeXLSXCellRef(colIndex, rowIndex int) string {
	var sb strings.Builder
	sb.Grow(8)
	officeAppendXLSXCellRef(&sb, colIndex, rowIndex)
	return sb.String()
}

func officeAppendXLSXCellRef(sb *strings.Builder, colIndex, rowIndex int) {
	officeAppendXLSXColumnName(sb, colIndex)
	officeAppendInt(sb, rowIndex)
}

func officeAppendXLSXCellRefBytes(dst []byte, colIndex, rowIndex int) []byte {
	colIndex++
	var colBuf [16]byte
	pos := len(colBuf)
	for colIndex > 0 {
		colIndex--
		pos--
		colBuf[pos] = byte('A' + colIndex%26)
		colIndex /= 26
	}
	dst = append(dst, colBuf[pos:]...)
	return strconv.AppendInt(dst, int64(rowIndex), 10)
}

func officeAppendXLSXCellStartBytes(dst []byte, rowIndex, colIndex, style int, cellType string) []byte {
	dst = append(dst, `<c r="`...)
	dst = officeAppendXLSXCellRefBytes(dst, colIndex, rowIndex)
	dst = append(dst, '"')
	if style > 0 {
		dst = append(dst, ` s="`...)
		dst = strconv.AppendInt(dst, int64(style), 10)
		dst = append(dst, '"')
	}
	if cellType != "" {
		dst = append(dst, ` t="`...)
		dst = append(dst, cellType...)
		dst = append(dst, '"')
	}
	return dst
}

func officeXLSXRangeRef(startCol, startRow, endCol, endRow int) string {
	var sb strings.Builder
	sb.Grow(18)
	officeAppendXLSXRangeRef(&sb, startCol, startRow, endCol, endRow)
	return sb.String()
}

func officeAppendXLSXRangeRef(sb *strings.Builder, startCol, startRow, endCol, endRow int) {
	officeAppendXLSXCellRef(sb, startCol, startRow)
	sb.WriteString(`:`)
	officeAppendXLSXCellRef(sb, endCol, endRow)
}

func officeXLSXColumnName(index int) string {
	var sb strings.Builder
	sb.Grow(4)
	officeAppendXLSXColumnName(&sb, index)
	return sb.String()
}

func officeAppendXLSXColumnName(sb *strings.Builder, index int) {
	if index < 0 {
		return
	}
	index++
	var buf [16]byte
	pos := len(buf)
	for index > 0 {
		index--
		pos--
		buf[pos] = byte('A' + index%26)
		index /= 26
	}
	_, _ = sb.Write(buf[pos:])
}

func officeNumericXMLValue(number float64) string {
	var buf [32]byte
	return string(strconv.AppendFloat(buf[:0], number, 'f', -1, 64))
}

func officeClampFloat(value, minValue, maxValue float64) float64 {
	if value < minValue {
		return minValue
	}
	if value > maxValue {
		return maxValue
	}
	return value
}

func officeAppendInt(sb *strings.Builder, value int) {
	var buf [20]byte
	_, _ = sb.Write(strconv.AppendInt(buf[:0], int64(value), 10))
}

func officeAppendFloat(sb *strings.Builder, value float64, precision int) {
	var buf [32]byte
	_, _ = sb.Write(strconv.AppendFloat(buf[:0], value, 'f', precision, 64))
}

func officeXLSXContentTypesXML(sheetCount int) string {
	var overrides strings.Builder
	for idx := 0; idx < sheetCount; idx++ {
		overrides.WriteString(fmt.Sprintf(`<Override PartName="/xl/worksheets/sheet%d.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`, idx+1))
	}
	return `<?xml version="1.0" encoding="UTF-8"?>` +
		`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
		`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
		`<Default Extension="xml" ContentType="application/xml"/>` +
		`<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>` +
		`<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>` +
		`<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>` +
		`<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>` +
		overrides.String() +
		`</Types>`
}

func officeXLSXAppPropsXML(sheets []officeXLSXSheetBuild) string {
	var titles strings.Builder
	for _, sheet := range sheets {
		titles.WriteString(`<vt:lpstr>`)
		titles.WriteString(officeXMLText(sheet.Name))
		titles.WriteString(`</vt:lpstr>`)
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">` +
		`<Application>ZimaOS Blue</Application>` +
		`<DocSecurity>0</DocSecurity>` +
		`<ScaleCrop>false</ScaleCrop>` +
		`<HeadingPairs><vt:vector size="2" baseType="variant"><vt:variant><vt:lpstr>Worksheets</vt:lpstr></vt:variant><vt:variant><vt:i4>` + strconv.Itoa(len(sheets)) + `</vt:i4></vt:variant></vt:vector></HeadingPairs>` +
		`<TitlesOfParts><vt:vector size="` + strconv.Itoa(len(sheets)) + `" baseType="lpstr">` + titles.String() + `</vt:vector></TitlesOfParts>` +
		`<Company>IceWhaleTech</Company>` +
		`<LinksUpToDate>false</LinksUpToDate><SharedDoc>false</SharedDoc><HyperlinksChanged>false</HyperlinksChanged>` +
		`<AppVersion>1.0</AppVersion>` +
		`</Properties>`
}

func officeXLSXWorkbookXML(sheets []officeXLSXSheetBuild) string {
	var body strings.Builder
	for idx, sheet := range sheets {
		body.WriteString(fmt.Sprintf(`<sheet name="%s" sheetId="%d" r:id="rId%d"/>`, officeXMLText(sheet.Name), idx+1, idx+1))
	}
	return `<?xml version="1.0" encoding="UTF-8"?>` +
		`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
		`<bookViews><workbookView xWindow="120" yWindow="60" windowWidth="18000" windowHeight="9000"/></bookViews>` +
		`<sheets>` + body.String() + `</sheets>` +
		`</workbook>`
}

func officeXLSXWorkbookRelsXML(sheetCount int) string {
	var body strings.Builder
	for idx := 0; idx < sheetCount; idx++ {
		body.WriteString(fmt.Sprintf(`<Relationship Id="rId%d" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet%d.xml"/>`, idx+1, idx+1))
	}
	body.WriteString(fmt.Sprintf(`<Relationship Id="rId%d" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>`, sheetCount+1))
	return `<?xml version="1.0" encoding="UTF-8"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		body.String() +
		`</Relationships>`
}

func officeXLSXStylesXML(theme officeTheme) string {
	fills := []string{
		`<fill><patternFill patternType="none"/></fill>`,
		`<fill><patternFill patternType="gray125"/></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.Primary) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.SurfaceAlt) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.PrimaryTint) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.SuccessTint) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.WarningTint) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.DangerTint) + `"/><bgColor indexed="64"/></patternFill></fill>`,
		`<fill><patternFill patternType="solid"><fgColor rgb="` + officeARGB(theme.SurfaceMuted) + `"/><bgColor indexed="64"/></patternFill></fill>`,
	}
	fonts := []string{
		`<font><sz val="11"/><color rgb="FF111827"/><name val="` + officeXMLText(theme.BodyFont) + `"/><family val="2"/></font>`,
		`<font><b/><sz val="22"/><color rgb="` + officeARGB(theme.PrimaryDark) + `"/><name val="` + officeXMLText(theme.DisplayFont) + `"/><family val="2"/></font>`,
		`<font><sz val="11"/><color rgb="` + officeARGB(theme.Slate) + `"/><name val="` + officeXMLText(theme.BodyFont) + `"/><family val="2"/></font>`,
		`<font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="` + officeXMLText(theme.BodyFont) + `"/><family val="2"/></font>`,
		`<font><b/><sz val="12"/><color rgb="` + officeARGB(theme.PrimaryDark) + `"/><name val="` + officeXMLText(theme.BodyFont) + `"/><family val="2"/></font>`,
		`<font><b/><sz val="10"/><color rgb="` + officeARGB(theme.PrimaryDark) + `"/><name val="` + officeXMLText(theme.BodyFont) + `"/><family val="2"/></font>`,
		`<font><b/><sz val="16"/><color rgb="` + officeARGB(theme.PrimaryDark) + `"/><name val="` + officeXMLText(theme.DisplayFont) + `"/><family val="2"/></font>`,
	}
	xfs := []officeXLSXXF{
		{FontID: 0, FillID: 0, BorderID: 0},
		{FontID: 1, FillID: 0, BorderID: 0, Vertical: "center", Wrap: true},
		{FontID: 2, FillID: 0, BorderID: 0, Vertical: "center", Wrap: true},
		{FontID: 4, FillID: 4, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 0, FillID: 8, BorderID: 1, Vertical: "top", Wrap: true},
		{FontID: 3, FillID: 2, BorderID: 1, Horizontal: "center", Vertical: "center", Wrap: true},
		{FontID: 0, FillID: 0, BorderID: 1, Vertical: "top"},
		{FontID: 0, FillID: 3, BorderID: 1, Vertical: "top"},
		{FontID: 0, FillID: 0, BorderID: 1, Vertical: "top", Wrap: true},
		{FontID: 0, FillID: 3, BorderID: 1, Vertical: "top", Wrap: true},
		{FontID: 0, FillID: 0, BorderID: 1, Horizontal: "right", Vertical: "center"},
		{FontID: 0, FillID: 3, BorderID: 1, Horizontal: "right", Vertical: "center"},
		{FontID: 0, FillID: 5, BorderID: 1, Horizontal: "center", Vertical: "center", Wrap: true},
		{FontID: 0, FillID: 6, BorderID: 1, Horizontal: "center", Vertical: "center", Wrap: true},
		{FontID: 0, FillID: 7, BorderID: 1, Horizontal: "center", Vertical: "center", Wrap: true},
		{FontID: 0, FillID: 8, BorderID: 1, Horizontal: "center", Vertical: "center", Wrap: true},
		{FontID: 5, FillID: 4, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 6, FillID: 4, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 5, FillID: 5, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 6, FillID: 5, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 5, FillID: 6, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 6, FillID: 6, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 5, FillID: 7, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 6, FillID: 7, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 5, FillID: 8, BorderID: 1, Vertical: "center", Wrap: true},
		{FontID: 6, FillID: 8, BorderID: 1, Vertical: "center", Wrap: true},
		{NumFmtID: 1, FontID: 0, FillID: 0, BorderID: 1, Horizontal: "right", Vertical: "center"},
		{NumFmtID: 2, FontID: 0, FillID: 0, BorderID: 1, Horizontal: "right", Vertical: "center"},
		{NumFmtID: 164, FontID: 0, FillID: 0, BorderID: 1, Horizontal: "right", Vertical: "center"},
		{NumFmtID: 10, FontID: 0, FillID: 0, BorderID: 1, Horizontal: "right", Vertical: "center"},
		{NumFmtID: 14, FontID: 0, FillID: 0, BorderID: 1, Horizontal: "center", Vertical: "center"},
		{NumFmtID: 22, FontID: 0, FillID: 0, BorderID: 1, Horizontal: "center", Vertical: "center"},
		{NumFmtID: 49, FontID: 0, FillID: 0, BorderID: 1, Vertical: "top"},
	}

	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8"?>`)
	sb.WriteString(`<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">`)
	sb.WriteString(`<numFmts count="1"><numFmt numFmtId="164" formatCode="&quot;$&quot;#,##0.00"/></numFmts>`)
	sb.WriteString(fmt.Sprintf(`<fonts count="%d">`, len(fonts)))
	for _, font := range fonts {
		sb.WriteString(font)
	}
	sb.WriteString(`</fonts>`)
	sb.WriteString(fmt.Sprintf(`<fills count="%d">`, len(fills)))
	for _, fill := range fills {
		sb.WriteString(fill)
	}
	sb.WriteString(`</fills>`)
	sb.WriteString(`<borders count="2">`)
	sb.WriteString(`<border><left/><right/><top/><bottom/><diagonal/></border>`)
	sb.WriteString(`<border><left style="thin"><color rgb="` + officeARGB(theme.Border) + `"/></left><right style="thin"><color rgb="` + officeARGB(theme.Border) + `"/></right><top style="thin"><color rgb="` + officeARGB(theme.Border) + `"/></top><bottom style="thin"><color rgb="` + officeARGB(theme.Border) + `"/></bottom><diagonal/></border>`)
	sb.WriteString(`</borders>`)
	sb.WriteString(`<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>`)
	sb.WriteString(fmt.Sprintf(`<cellXfs count="%d">`, len(xfs)))
	for _, xf := range xfs {
		sb.WriteString(officeXLSXXFXML(xf))
	}
	sb.WriteString(`</cellXfs>`)
	sb.WriteString(`<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>`)
	sb.WriteString(`</styleSheet>`)
	return sb.String()
}

func officeXLSXXFXML(xf officeXLSXXF) string {
	var sb strings.Builder
	sb.WriteString(`<xf numFmtId="`)
	sb.WriteString(strconv.Itoa(xf.NumFmtID))
	sb.WriteString(`"`)
	sb.WriteString(fmt.Sprintf(` fontId="%d" fillId="%d" borderId="%d" xfId="0"`, xf.FontID, xf.FillID, xf.BorderID))
	if xf.FontID != 0 {
		sb.WriteString(` applyFont="1"`)
	}
	if xf.FillID != 0 {
		sb.WriteString(` applyFill="1"`)
	}
	if xf.BorderID != 0 {
		sb.WriteString(` applyBorder="1"`)
	}
	if xf.NumFmtID != 0 {
		sb.WriteString(` applyNumberFormat="1"`)
	}
	if xf.Horizontal != "" || xf.Vertical != "" || xf.Wrap {
		sb.WriteString(` applyAlignment="1">`)
		sb.WriteString(`<alignment`)
		if xf.Horizontal != "" {
			sb.WriteString(` horizontal="`)
			sb.WriteString(xf.Horizontal)
			sb.WriteString(`"`)
		}
		if xf.Vertical != "" {
			sb.WriteString(` vertical="`)
			sb.WriteString(xf.Vertical)
			sb.WriteString(`"`)
		}
		if xf.Wrap {
			sb.WriteString(` wrapText="1"`)
		}
		sb.WriteString(`/>`)
		sb.WriteString(`</xf>`)
		return sb.String()
	}
	sb.WriteString(`/>`)
	return sb.String()
}

func officeBoolWord(value bool) string {
	if value {
		return "On"
	}
	return "Off"
}

func firstNonEmptyOfficeString(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}
