package tools

import (
	"fmt"
	"strings"
)

type officePPTXSlide struct {
	Title string
	Lines []string
}

func buildOfficePPTX(spec officeDocSpec) ([]byte, officeBuildInfo, error) {
	slides := officeBuildPresentationSlides(spec)
	if len(slides) == 0 {
		return nil, officeBuildInfo{}, fmt.Errorf("pptx output requires at least one slide")
	}

	entries := []officeZipEntry{
		{Name: "[Content_Types].xml", Content: officePPTXContentTypesXML(len(slides))},
		{Name: "_rels/.rels", Content: officePackageRelsXML("ppt/presentation.xml")},
		{Name: "docProps/core.xml", Content: officeCorePropsXML(spec.Title, "Presentation generated by ZimaOS Blue")},
		{Name: "docProps/app.xml", Content: officePPTXAppPropsXML(slides)},
		{Name: "ppt/presentation.xml", Content: officePPTXPresentationXML(len(slides))},
		{Name: "ppt/_rels/presentation.xml.rels", Content: officePPTXPresentationRelsXML(len(slides))},
		{Name: "ppt/slideMasters/slideMaster1.xml", Content: officePPTXSlideMasterXML()},
		{Name: "ppt/slideMasters/_rels/slideMaster1.xml.rels", Content: officePPTXSlideMasterRelsXML()},
		{Name: "ppt/slideLayouts/slideLayout1.xml", Content: officePPTXSlideLayoutXML()},
		{Name: "ppt/slideLayouts/_rels/slideLayout1.xml.rels", Content: officePPTXSlideLayoutRelsXML()},
		{Name: "ppt/theme/theme1.xml", Content: officePPTXThemeXML()},
	}
	for idx, slide := range slides {
		entries = append(entries,
			officeZipEntry{Name: fmt.Sprintf("ppt/slides/slide%d.xml", idx+1), Content: officePPTXSlideXML(slide)},
			officeZipEntry{Name: fmt.Sprintf("ppt/slides/_rels/slide%d.xml.rels", idx+1), Content: officePPTXSlideRelsXML()},
		)
	}

	data, err := officeBuildZip(entries)
	if err != nil {
		return nil, officeBuildInfo{}, err
	}

	paragraphCount := 0
	for _, slide := range slides {
		paragraphCount += len(slide.Lines)
	}
	return data, officeBuildInfo{
		Format:         "pptx",
		SectionCount:   len(slides),
		ParagraphCount: paragraphCount,
	}, nil
}

func officeBuildPresentationSlides(spec officeDocSpec) []officePPTXSlide {
	slides := make([]officePPTXSlide, 0, len(spec.Sections)+4)

	title := strings.TrimSpace(spec.Title)
	subtitle := strings.TrimSpace(spec.Subtitle)
	sectionTitles := officePPTXSectionTitles(spec.Sections)
	if title != "" || subtitle != "" {
		lines := []string(nil)
		if subtitle != "" {
			lines = append(lines, subtitle)
		}
		slides = append(slides, officePPTXSlide{
			Title: firstNonEmptyOfficeString(title, "Presentation"),
			Lines: lines,
		})
	}

	if len(sectionTitles) > 0 {
		tocLines := make([]string, 0, len(sectionTitles))
		for idx, sectionTitle := range sectionTitles {
			tocLines = append(tocLines, fmt.Sprintf("%d. %s", idx+1, sectionTitle))
		}
		slides = append(slides, officePPTXSlide{Title: "Table of Contents", Lines: tocLines})
	}
	if len(spec.Paragraphs) > 0 {
		slides = append(slides, officePPTXSlide{Title: "Content", Lines: officePPTXNormalizeLines(spec.Paragraphs...)})
	}

	for idx, section := range spec.Sections {
		lines := make([]string, 0, len(section.Paragraphs)+len(section.Bullets)+4)
		lines = append(lines, officePPTXNormalizeLines(section.Paragraphs...)...)
		for _, bullet := range officePPTXNormalizeLines(section.Bullets...) {
			lines = append(lines, "- "+bullet)
		}
		lines = append(lines, officePPTXTableLines(section.Table)...)
		if len(lines) == 0 {
			continue
		}
		title := strings.TrimSpace(section.Heading)
		if title == "" {
			title = fmt.Sprintf("Slide %d", idx+1)
		}
		slides = append(slides, officePPTXSlide{Title: title, Lines: lines})
	}

	if summaryLines := officePPTXSummaryLines(spec); len(summaryLines) > 0 {
		slides = append(slides, officePPTXSlide{Title: "Summary", Lines: summaryLines})
	}

	if len(slides) == 0 {
		slides = append(slides, officePPTXSlide{
			Title: firstNonEmptyOfficeString(title, "Presentation"),
			Lines: officePPTXNormalizeLines(subtitle),
		})
	}
	return slides
}

func officePPTXSectionTitles(sections []officeDocSection) []string {
	titles := make([]string, 0, len(sections))
	for idx, section := range sections {
		title := strings.TrimSpace(section.Heading)
		if title == "" {
			title = fmt.Sprintf("Section %d", idx+1)
		}
		titles = append(titles, title)
	}
	return titles
}

func officePPTXSummaryLines(spec officeDocSpec) []string {
	lines := officePPTXNormalizeLines(spec.Summary)
	for _, note := range officePPTXNormalizeLines(spec.Notes...) {
		lines = append(lines, "- "+note)
	}
	return lines
}

func officePPTXNormalizeLines(values ...string) []string {
	lines := make([]string, 0, len(values))
	for _, value := range values {
		for _, line := range strings.Split(value, "\n") {
			line = strings.TrimSpace(line)
			if line == "" {
				continue
			}
			lines = append(lines, line)
		}
	}
	return lines
}

func officePPTXTableLines(table *officeTableSpec) []string {
	if table == nil {
		return nil
	}
	lines := make([]string, 0, len(table.Rows)+1)
	if len(table.Headers) > 0 {
		lines = append(lines, strings.Join(table.Headers, " | "))
	}
	for _, row := range table.Rows {
		cells := make([]string, 0, len(row))
		for _, cell := range row {
			cells = append(cells, anyToStringForLLM(cell))
		}
		lines = append(lines, strings.Join(cells, " | "))
	}
	return officePPTXNormalizeLines(lines...)
}

func officePPTXContentTypesXML(slideCount int) string {
	var overrides strings.Builder
	for idx := 1; idx <= slideCount; idx++ {
		overrides.WriteString(fmt.Sprintf(`<Override PartName="/ppt/slides/slide%d.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`, idx))
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
		`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
		`<Default Extension="xml" ContentType="application/xml"/>` +
		`<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>` +
		`<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>` +
		`<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>` +
		`<Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/>` +
		`<Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>` +
		`<Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>` +
		overrides.String() +
		`</Types>`
}

func officePPTXAppPropsXML(slides []officePPTXSlide) string {
	var parts strings.Builder
	for _, slide := range slides {
		parts.WriteString("<vt:lpstr>")
		parts.WriteString(officeXMLText(firstNonEmptyOfficeString(slide.Title, "Slide")))
		parts.WriteString("</vt:lpstr>")
	}
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>ZimaOS Blue</Application>
  <PresentationFormat>Custom</PresentationFormat>
  <Slides>%d</Slides>
  <Notes>0</Notes>
  <HiddenSlides>0</HiddenSlides>
  <MMClips>0</MMClips>
  <ScaleCrop>false</ScaleCrop>
  <HeadingPairs>
    <vt:vector size="2" baseType="variant">
      <vt:variant><vt:lpstr>Slides</vt:lpstr></vt:variant>
      <vt:variant><vt:i4>%d</vt:i4></vt:variant>
    </vt:vector>
  </HeadingPairs>
  <TitlesOfParts>
    <vt:vector size="%d" baseType="lpstr">%s</vt:vector>
  </TitlesOfParts>
</Properties>`, len(slides), len(slides), len(slides), parts.String())
}

func officePPTXPresentationXML(slideCount int) string {
	var slideIDs strings.Builder
	for idx := 1; idx <= slideCount; idx++ {
		slideIDs.WriteString(fmt.Sprintf(`<p:sldId id="%d" r:id="rId%d"/>`, 255+idx, idx+1))
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">` +
		`<p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst>` +
		`<p:sldIdLst>` + slideIDs.String() + `</p:sldIdLst>` +
		`<p:sldSz cx="12192000" cy="6858000"/>` +
		`<p:notesSz cx="6858000" cy="9144000"/>` +
		`</p:presentation>`
}

func officePPTXPresentationRelsXML(slideCount int) string {
	var rels strings.Builder
	rels.WriteString(`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>`)
	for idx := 1; idx <= slideCount; idx++ {
		rels.WriteString(fmt.Sprintf(`<Relationship Id="rId%d" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide%d.xml"/>`, idx+1, idx))
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		rels.String() +
		`</Relationships>`
}

func officePPTXSlideMasterXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">` +
		`<p:cSld name="Blue Master"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld>` +
		`<p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/>` +
		`<p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst>` +
		`</p:sldMaster>`
}

func officePPTXSlideMasterRelsXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>` +
		`<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/>` +
		`</Relationships>`
}

func officePPTXSlideLayoutXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank" preserve="1">` +
		`<p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`
}

func officePPTXSlideLayoutRelsXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>`
}

func officePPTXThemeXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Blue Theme">` +
		`<a:themeElements><a:clrScheme name="Blue"><a:dk1><a:srgbClr val="111827"/></a:dk1><a:lt1><a:srgbClr val="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="1F2937"/></a:dk2><a:lt2><a:srgbClr val="F3F4F6"/></a:lt2><a:accent1><a:srgbClr val="2563EB"/></a:accent1><a:accent2><a:srgbClr val="0F766E"/></a:accent2><a:accent3><a:srgbClr val="EA580C"/></a:accent3><a:accent4><a:srgbClr val="7C3AED"/></a:accent4><a:accent5><a:srgbClr val="DC2626"/></a:accent5><a:accent6><a:srgbClr val="059669"/></a:accent6><a:hlink><a:srgbClr val="2563EB"/></a:hlink><a:folHlink><a:srgbClr val="7C3AED"/></a:folHlink></a:clrScheme><a:fontScheme name="Blue"><a:majorFont><a:latin typeface="Aptos Display"/></a:majorFont><a:minorFont><a:latin typeface="Aptos"/></a:minorFont></a:fontScheme><a:fmtScheme name="Blue"><a:fillStyleLst><a:solidFill><a:schemeClr val="lt1"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="9525"><a:solidFill><a:schemeClr val="accent1"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle/></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="lt1"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements>` +
		`</a:theme>`
}

func officePPTXSlideXML(slide officePPTXSlide) string {
	var body strings.Builder
	for _, line := range slide.Lines {
		body.WriteString(`<a:p><a:r><a:rPr lang="en-US" sz="2200"/><a:t>`)
		body.WriteString(officeXMLText(line))
		body.WriteString(`</a:t></a:r></a:p>`)
	}
	if body.Len() == 0 {
		body.WriteString(`<a:p/>`)
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">` +
		`<p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>` +
		`<p:sp><p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" b="1" sz="2800"/><a:t>` + officeXMLText(firstNonEmptyOfficeString(slide.Title, "Slide")) + `</a:t></a:r></a:p></p:txBody></p:sp>` +
		`<p:sp><p:nvSpPr><p:cNvPr id="3" name="Content"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr wrap="square"/><a:lstStyle/>` + body.String() + `</p:txBody></p:sp>` +
		`</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`
}

func officePPTXSlideRelsXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>` +
		`</Relationships>`
}
