package tools

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

func buildOfficeDOCX(spec officeDocSpec) ([]byte, officeBuildInfo, error) {
	spec = cleanupOfficeDocSpec(spec)

	entries := []officeZipEntry{
		{Name: "[Content_Types].xml", Content: officeDOCXContentTypesXML()},
		{Name: "_rels/.rels", Content: officePackageRelsXML("word/document.xml")},
		{Name: "docProps/core.xml", Content: officeCorePropsXML(spec.Title, "Styled report generated by ZimaOS Blue")},
		{Name: "docProps/app.xml", Content: officeDOCXAppPropsXML(spec)},
		{Name: "word/document.xml", Content: officeDOCXDocumentXML(spec)},
		{Name: "word/styles.xml", Content: officeDOCXStylesXML(spec.Theme)},
		{Name: "word/settings.xml", Content: officeDOCXSettingsXML()},
		{Name: "word/fontTable.xml", Content: officeDOCXFontTableXML(spec.Theme)},
		{Name: "word/_rels/document.xml.rels", Content: officeDOCXDocumentRelsXML()},
	}

	data, err := officeBuildZip(entries)
	if err != nil {
		return nil, officeBuildInfo{}, err
	}

	paragraphCount := len(splitOfficeParagraphs(spec.Summary)) + len(spec.Paragraphs) + len(spec.Notes)
	for _, section := range spec.Sections {
		paragraphCount += len(section.Paragraphs) + len(section.Bullets)
	}

	return data, officeBuildInfo{
		Format:         "docx",
		SectionCount:   len(spec.Sections),
		ParagraphCount: paragraphCount,
	}, nil
}

func officeDOCXContentTypesXML() string {
	return `<?xml version="1.0" encoding="UTF-8"?>` +
		`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
		`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
		`<Default Extension="xml" ContentType="application/xml"/>` +
		`<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>` +
		`<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>` +
		`<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>` +
		`<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>` +
		`<Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/>` +
		`<Override PartName="/word/fontTable.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml"/>` +
		`</Types>`
}

func officeDOCXAppPropsXML(spec officeDocSpec) string {
	title := strings.TrimSpace(spec.Title)
	if title == "" {
		title = "Document"
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">` +
		`<Application>ZimaOS Blue</Application>` +
		`<DocSecurity>0</DocSecurity>` +
		`<ScaleCrop>false</ScaleCrop>` +
		`<HeadingPairs><vt:vector size="2" baseType="variant"><vt:variant><vt:lpstr>Title</vt:lpstr></vt:variant><vt:variant><vt:i4>1</vt:i4></vt:variant></vt:vector></HeadingPairs>` +
		`<TitlesOfParts><vt:vector size="1" baseType="lpstr"><vt:lpstr>` + officeXMLText(title) + `</vt:lpstr></vt:vector></TitlesOfParts>` +
		`<Company>IceWhaleTech</Company>` +
		`<LinksUpToDate>false</LinksUpToDate><SharedDoc>false</SharedDoc><HyperlinksChanged>false</HyperlinksChanged>` +
		`<AppVersion>1.0</AppVersion>` +
		`</Properties>`
}

func officeDOCXDocumentRelsXML() string {
	return `<?xml version="1.0" encoding="UTF-8"?>` +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>` +
		`<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/>` +
		`<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/>` +
		`</Relationships>`
}

func officeDOCXSettingsXML() string {
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
		`<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">` +
		`<w:zoom w:percent="100"/>` +
		`<w:defaultTabStop w:val="720"/>` +
		`<w:compat/>` +
		`</w:settings>`
}

func officeDOCXFontTableXML(theme officeTheme) string {
	fonts := []string{theme.BodyFont, theme.DisplayFont, theme.EastAsiaFont, theme.MonospaceFont}
	seen := make(map[string]struct{}, len(fonts))
	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	sb.WriteString(`<w:fonts xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">`)
	for _, font := range fonts {
		font = strings.TrimSpace(font)
		if font == "" {
			continue
		}
		if _, ok := seen[font]; ok {
			continue
		}
		seen[font] = struct{}{}
		sb.WriteString(`<w:font w:name="`)
		sb.WriteString(officeXMLText(font))
		sb.WriteString(`"><w:family w:val="swiss"/></w:font>`)
	}
	sb.WriteString(`</w:fonts>`)
	return sb.String()
}

func officeDOCXStylesXML(theme officeTheme) string {
	primaryDark := officeWordHex(theme.PrimaryDark)
	primary := officeWordHex(theme.Primary)
	accent := officeWordHex(theme.Accent)
	slate := officeWordHex(theme.Slate)
	border := officeWordHex(theme.Border)
	calloutFill := officeWordHex(theme.PrimaryTint)

	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	sb.WriteString(`<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">`)
	sb.WriteString(`<w:docDefaults>`)
	sb.WriteString(`<w:rPrDefault><w:rPr><w:rFonts w:ascii="` + officeXMLText(theme.BodyFont) + `" w:hAnsi="` + officeXMLText(theme.BodyFont) + `" w:eastAsia="` + officeXMLText(theme.EastAsiaFont) + `" w:cs="` + officeXMLText(theme.BodyFont) + `"/><w:color w:val="111827"/><w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr></w:rPrDefault>`)
	sb.WriteString(`<w:pPrDefault><w:pPr><w:spacing w:after="120" w:line="320" w:lineRule="auto"/></w:pPr></w:pPrDefault>`)
	sb.WriteString(`</w:docDefaults>`)
	sb.WriteString(`<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:qFormat/></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueTitle"><w:name w:val="Blue Title"/><w:basedOn w:val="Normal"/><w:next w:val="BlueBody"/><w:uiPriority w:val="1"/><w:qFormat/><w:pPr><w:spacing w:after="60"/><w:keepNext/></w:pPr><w:rPr><w:rFonts w:ascii="` + officeXMLText(theme.DisplayFont) + `" w:hAnsi="` + officeXMLText(theme.DisplayFont) + `" w:eastAsia="` + officeXMLText(theme.EastAsiaFont) + `"/><w:b/><w:color w:val="` + primaryDark + `"/><w:sz w:val="40"/><w:szCs w:val="40"/></w:rPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueSubtitle"><w:name w:val="Blue Subtitle"/><w:basedOn w:val="Normal"/><w:next w:val="BlueBody"/><w:pPr><w:spacing w:after="40"/><w:keepNext/></w:pPr><w:rPr><w:color w:val="` + slate + `"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueMeta"><w:name w:val="Blue Meta"/><w:basedOn w:val="Normal"/><w:next w:val="BlueBody"/><w:pPr><w:spacing w:after="200"/></w:pPr><w:rPr><w:color w:val="` + slate + `"/><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueHeading1"><w:name w:val="Blue Heading 1"/><w:basedOn w:val="Normal"/><w:next w:val="BlueBody"/><w:uiPriority w:val="9"/><w:qFormat/><w:pPr><w:spacing w:before="280" w:after="80"/><w:keepNext/></w:pPr><w:rPr><w:b/><w:color w:val="` + primary + `"/><w:sz w:val="30"/><w:szCs w:val="30"/></w:rPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueBody"><w:name w:val="Blue Body"/><w:basedOn w:val="Normal"/><w:next w:val="BlueBody"/></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueBullet"><w:name w:val="Blue Bullet"/><w:basedOn w:val="BlueBody"/><w:pPr><w:ind w:left="360" w:hanging="240"/><w:spacing w:after="80"/></w:pPr></w:style>`)
	sb.WriteString(`<w:style w:type="paragraph" w:styleId="BlueCallout"><w:name w:val="Blue Callout"/><w:basedOn w:val="BlueBody"/><w:pPr><w:spacing w:before="60" w:after="60"/><w:shd w:val="clear" w:fill="` + calloutFill + `"/><w:pBdr><w:left w:val="single" w:sz="12" w:space="1" w:color="` + accent + `"/><w:top w:val="single" w:sz="4" w:space="1" w:color="` + border + `"/><w:right w:val="single" w:sz="4" w:space="1" w:color="` + border + `"/><w:bottom w:val="single" w:sz="4" w:space="1" w:color="` + border + `"/></w:pBdr><w:ind w:left="180" w:right="60"/></w:pPr></w:style>`)
	sb.WriteString(`</w:styles>`)
	return sb.String()
}

func officeDOCXDocumentXML(spec officeDocSpec) string {
	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	sb.WriteString(`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">`)
	sb.WriteString(`<w:body>`)

	title := strings.TrimSpace(spec.Title)
	if title != "" {
		sb.WriteString(officeDOCXParagraphXML("BlueTitle", title))
	}
	if subtitle := strings.TrimSpace(spec.Subtitle); subtitle != "" {
		sb.WriteString(officeDOCXParagraphXML("BlueSubtitle", subtitle))
	}
	meta := "Generated " + time.Now().Format("2006-01-02") + "  •  Theme " + spec.Theme.Name
	if hint := strings.TrimSpace(spec.StyleHint); hint != "" {
		meta += "  •  " + hint
	}
	sb.WriteString(officeDOCXParagraphXML("BlueMeta", meta))

	for _, paragraph := range splitOfficeParagraphs(spec.Summary) {
		sb.WriteString(officeDOCXParagraphXML("BlueCallout", paragraph))
	}
	for _, paragraph := range spec.Paragraphs {
		paragraph = strings.TrimSpace(paragraph)
		if paragraph == "" {
			continue
		}
		sb.WriteString(officeDOCXParagraphXML("BlueBody", paragraph))
	}

	for _, section := range spec.Sections {
		if heading := strings.TrimSpace(section.Heading); heading != "" {
			sb.WriteString(officeDOCXParagraphXML("BlueHeading1", heading))
		}
		for _, paragraph := range section.Paragraphs {
			paragraph = strings.TrimSpace(paragraph)
			if paragraph == "" {
				continue
			}
			sb.WriteString(officeDOCXParagraphXML("BlueBody", paragraph))
		}
		for _, bullet := range section.Bullets {
			bullet = strings.TrimSpace(bullet)
			if bullet == "" {
				continue
			}
			sb.WriteString(officeDOCXParagraphXML("BlueBullet", "• "+bullet))
		}
		if section.Table != nil {
			sb.WriteString(officeDOCXTableXML(section.Table, spec.Theme))
		}
	}

	if len(spec.Notes) > 0 {
		sb.WriteString(officeDOCXParagraphXML("BlueHeading1", "Notes"))
		for _, note := range spec.Notes {
			note = strings.TrimSpace(note)
			if note == "" {
				continue
			}
			sb.WriteString(officeDOCXParagraphXML("BlueBullet", "• "+note))
		}
	}

	sb.WriteString(officeDOCXSectionPropsXML())
	sb.WriteString(`</w:body></w:document>`)
	return sb.String()
}

func officeDOCXParagraphXML(style, text string) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return ""
	}
	var sb strings.Builder
	sb.WriteString(`<w:p>`)
	if style != "" {
		sb.WriteString(`<w:pPr><w:pStyle w:val="`)
		sb.WriteString(style)
		sb.WriteString(`"/></w:pPr>`)
	}
	sb.WriteString(officeDOCXTextRunsXML(text, "", "", false))
	sb.WriteString(`</w:p>`)
	return sb.String()
}

func officeDOCXTextRunsXML(text, color, font string, bold bool) string {
	normalized := strings.ReplaceAll(text, "\r\n", "\n")
	parts := strings.Split(normalized, "\n")
	var sb strings.Builder
	runProps := officeDOCXRunPropsXML(color, font, bold)
	for idx, part := range parts {
		sb.WriteString(`<w:r>`)
		if runProps != "" {
			sb.WriteString(`<w:rPr>`)
			sb.WriteString(runProps)
			sb.WriteString(`</w:rPr>`)
		}
		sb.WriteString(`<w:t xml:space="preserve">`)
		sb.WriteString(officeXMLText(part))
		sb.WriteString(`</w:t></w:r>`)
		if idx < len(parts)-1 {
			sb.WriteString(`<w:r><w:br/></w:r>`)
		}
	}
	return sb.String()
}

func officeDOCXRunPropsXML(color, font string, bold bool) string {
	var sb strings.Builder
	if font = strings.TrimSpace(font); font != "" {
		sb.WriteString(`<w:rFonts w:ascii="`)
		sb.WriteString(officeXMLText(font))
		sb.WriteString(`" w:hAnsi="`)
		sb.WriteString(officeXMLText(font))
		sb.WriteString(`" w:eastAsia="`)
		sb.WriteString(officeXMLText(font))
		sb.WriteString(`"/>`)
	}
	if bold {
		sb.WriteString(`<w:b/>`)
	}
	if color = strings.TrimSpace(color); color != "" {
		sb.WriteString(`<w:color w:val="`)
		sb.WriteString(officeWordHex(color))
		sb.WriteString(`"/>`)
	}
	return sb.String()
}

func officeDOCXTableXML(table *officeTableSpec, theme officeTheme) string {
	if table == nil {
		return ""
	}
	columnCount := len(table.Headers)
	for _, row := range table.Rows {
		if len(row) > columnCount {
			columnCount = len(row)
		}
	}
	if columnCount == 0 {
		return ""
	}

	headers := append([]string(nil), table.Headers...)
	for len(headers) < columnCount {
		headers = append(headers, fmt.Sprintf("Column %d", len(headers)+1))
	}
	widths := officeDOCXColumnWidths(table, headers, table.Rows)

	var sb strings.Builder
	sb.WriteString(`<w:tbl>`)
	sb.WriteString(`<w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders>`)
	for _, edge := range []string{"top", "left", "bottom", "right", "insideH", "insideV"} {
		sb.WriteString(`<w:` + edge + ` w:val="single" w:sz="6" w:space="0" w:color="` + officeWordHex(theme.Border) + `"/>`)
	}
	sb.WriteString(`</w:tblBorders><w:tblCellMar><w:top w:w="90" w:type="dxa"/><w:left w:w="120" w:type="dxa"/><w:bottom w:w="90" w:type="dxa"/><w:right w:w="120" w:type="dxa"/></w:tblCellMar></w:tblPr>`)
	sb.WriteString(`<w:tblGrid>`)
	for _, width := range widths {
		sb.WriteString(`<w:gridCol w:w="`)
		sb.WriteString(strconv.Itoa(width))
		sb.WriteString(`"/>`)
	}
	sb.WriteString(`</w:tblGrid>`)
	sb.WriteString(officeDOCXTableRowXML(table, headers, widths, theme.Primary, "FFFFFF", true))
	for idx, row := range table.Rows {
		fill := ""
		if idx%2 == 1 {
			fill = theme.SurfaceAlt
		}
		values := make([]string, columnCount)
		copy(values, row)
		sb.WriteString(officeDOCXTableRowXML(table, values, widths, fill, "", false))
	}
	sb.WriteString(`</w:tbl>`)
	return sb.String()
}

func officeDOCXTableRowXML(table *officeTableSpec, values []string, widths []int, fill, textColor string, bold bool) string {
	var sb strings.Builder
	sb.WriteString(`<w:tr>`)
	for idx, value := range values {
		width := 1800
		if idx < len(widths) {
			width = widths[idx]
		}
		sb.WriteString(officeDOCXTableCellXML(value, width, fill, textColor, bold, officeDOCXTableCellAlignment(table, idx)))
	}
	sb.WriteString(`</w:tr>`)
	return sb.String()
}

func officeDOCXTableCellXML(text string, width int, fill, textColor string, bold bool, alignment string) string {
	var sb strings.Builder
	sb.WriteString(`<w:tc><w:tcPr><w:tcW w:w="`)
	sb.WriteString(strconv.Itoa(width))
	sb.WriteString(`" w:type="dxa"/>`)
	if strings.TrimSpace(fill) != "" {
		sb.WriteString(`<w:shd w:val="clear" w:fill="`)
		sb.WriteString(officeWordHex(fill))
		sb.WriteString(`"/>`)
	}
	sb.WriteString(`<w:vAlign w:val="top"/></w:tcPr>`)
	sb.WriteString(`<w:p><w:pPr><w:spacing w:after="0" w:line="260" w:lineRule="auto"/>`)
	if wordAlignment := officeDOCXTableParagraphAlignment(alignment); wordAlignment != "" {
		sb.WriteString(`<w:jc w:val="`)
		sb.WriteString(wordAlignment)
		sb.WriteString(`"/>`)
	}
	sb.WriteString(`</w:pPr>`)
	sb.WriteString(officeDOCXTextRunsXML(strings.TrimSpace(text), textColor, "", bold))
	sb.WriteString(`</w:p></w:tc>`)
	return sb.String()
}

func officeDOCXTableCellAlignment(table *officeTableSpec, columnIndex int) string {
	if table == nil || columnIndex < 0 || columnIndex >= len(table.ColumnAlignments) {
		return ""
	}
	return table.ColumnAlignments[columnIndex]
}

func officeDOCXTableParagraphAlignment(alignment string) string {
	switch strings.ToLower(strings.TrimSpace(alignment)) {
	case "left":
		return "left"
	case "center":
		return "center"
	case "right":
		return "right"
	default:
		return ""
	}
}

func officeDOCXColumnWidths(table *officeTableSpec, headers []string, rows [][]string) []int {
	if widths := officeDOCXExplicitColumnWidths(table, len(headers)); len(widths) > 0 {
		return widths
	}
	weights := make([]int, len(headers))
	total := 0
	for idx, header := range headers {
		weight := officeMaxLineRunes(header) + 4
		for rowIdx := 0; rowIdx < len(rows) && rowIdx < 20; rowIdx++ {
			if idx >= len(rows[rowIdx]) {
				continue
			}
			if lineWeight := officeMaxLineRunes(rows[rowIdx][idx]) + 2; lineWeight > weight {
				weight = lineWeight
			}
		}
		if weight < 8 {
			weight = 8
		}
		weights[idx] = weight
		total += weight
	}
	if total == 0 {
		total = len(headers) * 8
	}
	widths := make([]int, len(headers))
	const tableWidth = 9000
	for idx, weight := range weights {
		width := tableWidth * weight / total
		if width < 1200 {
			width = 1200
		}
		widths[idx] = width
	}
	return widths
}

func officeDOCXExplicitColumnWidths(table *officeTableSpec, columnCount int) []int {
	if table == nil || columnCount <= 0 || len(table.ColumnWidths) == 0 {
		return nil
	}
	totalWeight := 0.0
	for idx := 0; idx < columnCount; idx++ {
		weight := 1.0
		if idx < len(table.ColumnWidths) && table.ColumnWidths[idx] > 0 {
			weight = table.ColumnWidths[idx]
		}
		totalWeight += weight
	}
	if totalWeight <= 0 {
		return nil
	}

	const tableWidth = 9000
	widths := make([]int, columnCount)
	remainingWidth := tableWidth
	remainingWeight := totalWeight
	for idx := range widths {
		weight := 1.0
		if idx < len(table.ColumnWidths) && table.ColumnWidths[idx] > 0 {
			weight = table.ColumnWidths[idx]
		}
		if idx == columnCount-1 || remainingWeight <= 0 {
			widths[idx] = remainingWidth
		} else {
			width := int(float64(tableWidth) * (weight / totalWeight))
			if width < 0 {
				width = 0
			}
			if width > remainingWidth {
				width = remainingWidth
			}
			widths[idx] = width
		}
		remainingWidth -= widths[idx]
		remainingWeight -= weight
	}
	return widths
}

func officeDOCXSectionPropsXML() string {
	return `<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1080" w:right="1020" w:bottom="1080" w:left="1020" w:header="480" w:footer="480" w:gutter="0"/><w:cols w:space="720"/></w:sectPr>`
}

func parseMarkdownishOfficeDoc(content string) officeDocSpec {
	spec := officeDocSpec{}
	normalized := strings.ReplaceAll(content, "\r\n", "\n")
	blocks := strings.Split(normalized, "\n\n")
	currentSection := -1

	appendTopParagraph := func(text string) {
		text = strings.TrimSpace(text)
		if text == "" {
			return
		}
		lower := strings.ToLower(text)
		if strings.HasPrefix(lower, "summary:") || strings.HasPrefix(lower, "摘要：") || strings.HasPrefix(lower, "摘要:") {
			text = strings.TrimSpace(strings.TrimPrefix(strings.TrimPrefix(strings.TrimPrefix(text, "Summary:"), "摘要:"), "摘要："))
			if text != "" {
				spec.Summary = text
			}
			return
		}
		if spec.Title != "" && spec.Subtitle == "" && spec.Summary == "" && len(spec.Paragraphs) == 0 && runeCount(text) <= 96 {
			spec.Subtitle = text
			return
		}
		if spec.Summary == "" {
			spec.Summary = text
			return
		}
		spec.Paragraphs = append(spec.Paragraphs, text)
	}

	appendSectionParagraph := func(text string) {
		text = strings.TrimSpace(text)
		if text == "" {
			return
		}
		if currentSection >= 0 && currentSection < len(spec.Sections) {
			spec.Sections[currentSection].Paragraphs = append(spec.Sections[currentSection].Paragraphs, text)
			return
		}
		appendTopParagraph(text)
	}

	startSection := func(heading string) {
		spec.Sections = append(spec.Sections, officeDocSection{Heading: strings.TrimSpace(heading)})
		currentSection = len(spec.Sections) - 1
	}

	for _, block := range blocks {
		lines := officeTrimmedLines(block)
		if len(lines) == 0 {
			continue
		}

		if heading, level, ok := officeMarkdownHeading(lines[0]); ok {
			if level == 1 && spec.Title == "" && currentSection < 0 && spec.Summary == "" && len(spec.Paragraphs) == 0 {
				spec.Title = heading
			} else {
				startSection(heading)
			}
			lines = lines[1:]
			if len(lines) == 0 {
				continue
			}
		}

		if officeAllBulletLines(lines) {
			bullets := officeMarkdownBullets(lines)
			if len(bullets) == 0 {
				continue
			}
			if currentSection >= 0 && currentSection < len(spec.Sections) {
				spec.Sections[currentSection].Bullets = append(spec.Sections[currentSection].Bullets, bullets...)
			} else {
				startSection("Highlights")
				spec.Sections[currentSection].Bullets = append(spec.Sections[currentSection].Bullets, bullets...)
			}
			continue
		}

		if table := officeParseMarkdownTable(lines); table != nil {
			if currentSection >= 0 && currentSection < len(spec.Sections) {
				spec.Sections[currentSection].Table = table
			} else {
				startSection("Table")
				spec.Sections[currentSection].Table = table
			}
			continue
		}

		paragraph := officeJoinTextFragments(lines)
		appendSectionParagraph(paragraph)
	}

	return spec
}

func officeTrimmedLines(block string) []string {
	rawLines := strings.Split(strings.ReplaceAll(block, "\r\n", "\n"), "\n")
	lines := make([]string, 0, len(rawLines))
	for _, line := range rawLines {
		if trimmed := strings.TrimSpace(line); trimmed != "" {
			lines = append(lines, trimmed)
		}
	}
	return lines
}

func officeMarkdownHeading(line string) (string, int, bool) {
	line = strings.TrimSpace(line)
	for level := 1; level <= 3; level++ {
		prefix := strings.Repeat("#", level) + " "
		if strings.HasPrefix(line, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(line, prefix)), level, true
		}
	}
	return "", 0, false
}

func officeAllBulletLines(lines []string) bool {
	if len(lines) == 0 {
		return false
	}
	for _, line := range lines {
		if officeStripMarkdownBullet(line) == "" {
			return false
		}
	}
	return true
}

func officeMarkdownBullets(lines []string) []string {
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		if bullet := officeStripMarkdownBullet(line); bullet != "" {
			out = append(out, bullet)
		}
	}
	return out
}

func officeStripMarkdownBullet(line string) string {
	line = strings.TrimSpace(line)
	switch {
	case strings.HasPrefix(line, "- "):
		return strings.TrimSpace(strings.TrimPrefix(line, "- "))
	case strings.HasPrefix(line, "* "):
		return strings.TrimSpace(strings.TrimPrefix(line, "* "))
	case strings.HasPrefix(line, "• "):
		return strings.TrimSpace(strings.TrimPrefix(line, "• "))
	}
	for idx := 0; idx < len(line); idx++ {
		if line[idx] < '0' || line[idx] > '9' {
			if idx > 0 && idx+1 < len(line) && line[idx] == '.' && line[idx+1] == ' ' {
				return strings.TrimSpace(line[idx+2:])
			}
			break
		}
	}
	return ""
}

func officeParseMarkdownTable(lines []string) *officeTableSpec {
	if len(lines) < 2 {
		return nil
	}
	for _, line := range lines {
		if !strings.Contains(line, "|") {
			return nil
		}
	}
	headers := officeMarkdownTableCells(lines[0])
	if len(headers) == 0 || !officeMarkdownTableDivider(lines[1], len(headers)) {
		return nil
	}
	rows := make([][]string, 0, len(lines)-2)
	for _, line := range lines[2:] {
		cells := officeMarkdownTableCells(line)
		if len(cells) == 0 {
			continue
		}
		for len(cells) < len(headers) {
			cells = append(cells, "")
		}
		rows = append(rows, cells)
	}
	return &officeTableSpec{Headers: headers, Rows: rows}
}

func officeMarkdownTableCells(line string) []string {
	line = strings.TrimSpace(line)
	line = strings.TrimPrefix(line, "|")
	line = strings.TrimSuffix(line, "|")
	parts := strings.Split(line, "|")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		out = append(out, strings.TrimSpace(part))
	}
	return out
}

func officeMarkdownTableDivider(line string, columns int) bool {
	cells := officeMarkdownTableCells(line)
	if len(cells) != columns {
		return false
	}
	for _, cell := range cells {
		cell = strings.TrimSpace(strings.Trim(cell, ":"))
		if cell == "" {
			return false
		}
		for _, r := range cell {
			if r != '-' {
				return false
			}
		}
	}
	return true
}
