/* eslint-disable */
// Code generated by web/scripts/sync-feature-intent-terms.mjs. DO NOT EDIT.

export interface FeatureIntentTerms {
  deepResearchExplicit: string[]
  deepResearchActions: string[]
  deepResearchTargets: string[]
  deepResearchNegations: string[]
  agentModeExplicit: string[]
  agentModeActions: string[]
  agentModeTargets: string[]
  agentModeNegations: string[]
  definitionPrefixes: string[]
}

export const featureIntentTerms: FeatureIntentTerms = {
  "deepResearchExplicit": [
    "deep research",
    "research mode",
    "research workflow",
    "research capability",
    "harness research",
    "深度搜索",
    "深度研究",
    "深入研究",
    "深度调研",
    "深入调研",
    "研究模式",
    "研究流程",
    "研究能力",
    "人物调研",
    "查阅观点",
    "按时期调研"
  ],
  "deepResearchActions": [
    "deep dive",
    "in-depth",
    "in depth",
    "comprehensive research",
    "research thoroughly",
    "详细调研",
    "全面调研",
    "深入分析",
    "全面分析",
    "逐一调研",
    "查阅",
    "梳理"
  ],
  "deepResearchTargets": [
    "资料",
    "来源",
    "引用",
    "证据",
    "sources",
    "citations",
    "evidence",
    "references",
    "观点",
    "文章",
    "不同时期"
  ],
  "deepResearchNegations": [
    "no deep research",
    "no research mode",
    "without deep research",
    "without research mode",
    "disable deep research",
    "disable research mode",
    "disable research",
    "不要深度搜索",
    "不用深度搜索",
    "关闭深度搜索",
    "不要研究模式",
    "不用研究模式",
    "关闭研究模式"
  ],
  "agentModeExplicit": [
    "agent mode",
    "agent loop",
    "agent loop mode",
    "agent mode loop",
    "智能体模式",
    "智能体循环",
    "循环智能体",
    "代理模式",
    "自动代理",
    "自主代理"
  ],
  "agentModeActions": [
    "autonomous",
    "plan and execute",
    "multi-step",
    "自动执行",
    "自主执行",
    "自己完成",
    "自动完成",
    "分步执行",
    "端到端执行"
  ],
  "agentModeTargets": [
    "task",
    "tasks",
    "workflow",
    "步骤",
    "任务",
    "流程",
    "命令"
  ],
  "agentModeNegations": [
    "no agent mode",
    "no agent loop",
    "without agent mode",
    "without agent loop",
    "disable agent mode",
    "disable agent loop",
    "不要 agent mode",
    "不要 agent loop",
    "不要智能体模式",
    "不要智能体循环",
    "关闭agent loop",
    "关闭agent mode",
    "关闭智能体模式",
    "不要自动执行"
  ],
  "definitionPrefixes": [
    "what is",
    "what's",
    "how to",
    "how do i",
    "explain",
    "tell me about",
    "什么是",
    "啥是",
    "怎么用",
    "如何使用",
    "介绍一下",
    "解释一下"
  ]
}
