#Requires -RunAsAdministrator
<#
.SYNOPSIS
    ZimaOS-Echo One-Click Installation Script for Windows
.DESCRIPTION
    Downloads and installs ZimaOS-Echo on Windows systems with full Windows Service support,
    including automatic recovery, Event Log integration, and proper service management.
.PARAMETER Version
    Version to install (default: latest)
.PARAMETER InstallDir
    Installation directory (default: C:\Program Files\ZimaOS-Echo)
.PARAMETER NoService
    Skip Windows service installation (run manually)
.PARAMETER Uninstall
    Uninstall ZimaOS-Echo
.EXAMPLE
    irm https://echo.zimaos.com/install.ps1 | iex
.EXAMPLE
    .\install.ps1 -Version v0.3.0
.EXAMPLE
    .\install.ps1 -Uninstall
#>

param(
    [string]$Version = "latest",
    [string]$InstallDir = "$env:ProgramFiles\ZimaOS-Echo",
    [switch]$NoService,
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$GitHubRepo = "zimaos/echo"
$BaseUrl = "https://github.com/$GitHubRepo/releases"
$ServiceName = "ZimaOS-Echo"
$EventLogSource = "ZimaOS-Echo"

function Write-Banner {
    Write-Host ""
    Write-Host "╔═══════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║         ZimaOS-Echo Installer             ║" -ForegroundColor Cyan
    Write-Host "║     NAS-Native Agent Runtime              ║" -ForegroundColor Cyan
    Write-Host "╚═══════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""
}

function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] " -ForegroundColor Green -NoNewline
    Write-Host $Message
}

function Write-Warn {
    param([string]$Message)
    Write-Host "[WARN] " -ForegroundColor Yellow -NoNewline
    Write-Host $Message
}

function Write-Err {
    param([string]$Message)
    Write-Host "[ERROR] " -ForegroundColor Red -NoNewline
    Write-Host $Message
}

function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-Architecture {
    $arch = [System.Environment]::GetEnvironmentVariable("PROCESSOR_ARCHITECTURE")
    switch ($arch) {
        "AMD64" { return "amd64" }
        "ARM64" { return "arm64" }
        default {
            throw "Unsupported architecture: $arch"
        }
    }
}

function Get-LatestVersion {
    if ($Version -eq "latest") {
        try {
            $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$GitHubRepo/releases/latest"
            $script:Version = $release.tag_name
        } catch {
            $script:Version = "v0.3.0"
            Write-Warn "Could not fetch latest version, using $Version"
        }
    }
    Write-Info "Installing version: $Version"
}

function Install-Binary {
    $arch = Get-Architecture
    $binaryName = "echo-windows-$arch.zip"
    $downloadUrl = "$BaseUrl/download/$Version/$binaryName"

    Write-Info "Downloading from: $downloadUrl"

    # Create directories
    $binDir = Join-Path $InstallDir "bin"
    $configDir = Join-Path $InstallDir "config"
    $dataDir = Join-Path $InstallDir "data"
    $logsDir = Join-Path $InstallDir "logs"

    New-Item -ItemType Directory -Force -Path $binDir, $configDir, $dataDir, $logsDir | Out-Null

    # Download and extract
    $tempFile = Join-Path $env:TEMP "zimaos-echo.zip"
    try {
        Invoke-WebRequest -Uri $downloadUrl -OutFile $tempFile
        Expand-Archive -Path $tempFile -DestinationPath $binDir -Force
    } finally {
        if (Test-Path $tempFile) {
            Remove-Item $tempFile -Force
        }
    }

    Write-Info "Installed to $InstallDir"
}

function New-DefaultConfig {
    $configPath = Join-Path $InstallDir "config\config.yaml"

    if (-not (Test-Path $configPath)) {
        Write-Info "Creating default configuration..."

        $dataDir = Join-Path $InstallDir "data"
        $logsDir = Join-Path $InstallDir "logs"

        $config = @"
# ZimaOS-Echo Configuration
# Generated by install.ps1

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

log:
  level: "info"
  format: "json"
  output: "stdout"
  # Also log to file for Windows Event Log integration
  file: "$($logsDir -replace '\\', '/')/echo.log"

worker:
  pool_size: 10
  max_queue_len: 100

# Resource limits
resources:
  max_memory_mb: 512
  max_cpu_percent: 50
  max_open_files: 65536
  max_goroutines: 10000

# Data directory
data:
  path: "$($dataDir -replace '\\', '/')"
"@
        Set-Content -Path $configPath -Value $config
    }
}

function Install-EventLogSource {
    Write-Info "Setting up Windows Event Log source..."

    try {
        # Check if source already exists
        if (-not [System.Diagnostics.EventLog]::SourceExists($EventLogSource)) {
            [System.Diagnostics.EventLog]::CreateEventSource($EventLogSource, "Application")
            Write-Info "Event Log source '$EventLogSource' created"
        } else {
            Write-Info "Event Log source '$EventLogSource' already exists"
        }
    } catch {
        Write-Warn "Could not create Event Log source: $_"
    }
}

function Remove-EventLogSource {
    Write-Info "Removing Windows Event Log source..."

    try {
        if ([System.Diagnostics.EventLog]::SourceExists($EventLogSource)) {
            [System.Diagnostics.EventLog]::DeleteEventSource($EventLogSource)
            Write-Info "Event Log source '$EventLogSource' removed"
        }
    } catch {
        Write-Warn "Could not remove Event Log source: $_"
    }
}

function Install-WindowsService {
    Write-Info "Setting up Windows service..."

    $binaryPath = Join-Path $InstallDir "bin\echo.exe"
    $configPath = Join-Path $InstallDir "config\config.yaml"

    # Check if binary exists
    if (-not (Test-Path $binaryPath)) {
        throw "Binary not found at $binaryPath"
    }

    # Check if service exists
    $service = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue

    if ($service) {
        Write-Info "Stopping existing service..."
        Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2

        # Delete existing service
        sc.exe delete $ServiceName | Out-Null
        Start-Sleep -Seconds 2
    }

    # Use the built-in service installer from the binary
    Write-Info "Installing service using built-in installer..."
    $installResult = & $binaryPath install 2>&1
    if ($LASTEXITCODE -ne 0) {
        # Fallback to sc.exe if built-in installer fails
        Write-Warn "Built-in installer failed, using sc.exe fallback..."

        $binPathEscaped = "`"$binaryPath`" --config `"$configPath`""
        sc.exe create $ServiceName binPath= $binPathEscaped start= auto DisplayName= "ZimaOS Echo" | Out-Null
        sc.exe description $ServiceName "ZimaOS Echo - NAS-Native Agent Runtime" | Out-Null

        # Configure recovery options: restart after 5s, 10s, 30s
        # Reset failure count after 24 hours (86400 seconds)
        sc.exe failure $ServiceName reset= 86400 actions= restart/5000/restart/10000/restart/30000 | Out-Null

        # Configure service to restart on crash
        sc.exe failureflag $ServiceName 1 | Out-Null
    }

    # Set service to delayed auto-start (starts after other auto-start services)
    sc.exe config $ServiceName start= delayed-auto | Out-Null

    # Configure service dependencies (network must be available)
    sc.exe config $ServiceName depend= Tcpip/Dnscache | Out-Null

    Write-Info "Starting service..."
    Start-Service -Name $ServiceName

    Start-Sleep -Seconds 3
    $service = Get-Service -Name $ServiceName
    if ($service.Status -eq "Running") {
        Write-Info "Service started successfully!"

        # Log to Event Log
        try {
            Write-EventLog -LogName Application -Source $EventLogSource -EventId 1000 -EntryType Information -Message "ZimaOS-Echo service installed and started successfully. Version: $Version"
        } catch {
            # Ignore Event Log errors
        }
    } else {
        Write-Warn "Service may not have started. Check Event Viewer for details."
        Write-Warn "Service status: $($service.Status)"
    }
}

function Uninstall-WindowsService {
    Write-Info "Removing Windows service..."

    $binaryPath = Join-Path $InstallDir "bin\echo.exe"

    # Try using built-in uninstaller first
    if (Test-Path $binaryPath) {
        Write-Info "Using built-in uninstaller..."
        & $binaryPath uninstall 2>&1 | Out-Null
    }

    # Ensure service is stopped and removed
    $service = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($service) {
        Write-Info "Stopping service..."
        Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2

        Write-Info "Deleting service..."
        sc.exe delete $ServiceName | Out-Null
        Start-Sleep -Seconds 2
    }

    Write-Info "Service removed"
}

function Add-FirewallRule {
    Write-Info "Adding firewall rule..."

    $ruleName = "ZimaOS-Echo"
    $existingRule = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue

    if (-not $existingRule) {
        New-NetFirewallRule -DisplayName $ruleName `
            -Description "Allow ZimaOS-Echo web interface" `
            -Direction Inbound `
            -Protocol TCP `
            -LocalPort 8080 `
            -Action Allow `
            -Profile Any | Out-Null
        Write-Info "Firewall rule added"
    } else {
        Write-Info "Firewall rule already exists"
    }
}

function Remove-FirewallRule {
    Write-Info "Removing firewall rule..."

    $ruleName = "ZimaOS-Echo"
    $existingRule = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue

    if ($existingRule) {
        Remove-NetFirewallRule -DisplayName $ruleName
        Write-Info "Firewall rule removed"
    }
}

function Add-ToPath {
    Write-Info "Adding to system PATH..."

    $binDir = Join-Path $InstallDir "bin"
    $currentPath = [Environment]::GetEnvironmentVariable("Path", "Machine")

    if ($currentPath -notlike "*$binDir*") {
        $newPath = "$currentPath;$binDir"
        [Environment]::SetEnvironmentVariable("Path", $newPath, "Machine")
        Write-Info "Added $binDir to system PATH"
        Write-Info "You may need to restart your terminal for PATH changes to take effect"
    } else {
        Write-Info "Already in system PATH"
    }
}

function Remove-FromPath {
    Write-Info "Removing from system PATH..."

    $binDir = Join-Path $InstallDir "bin"
    $currentPath = [Environment]::GetEnvironmentVariable("Path", "Machine")

    if ($currentPath -like "*$binDir*") {
        $newPath = ($currentPath -split ';' | Where-Object { $_ -ne $binDir }) -join ';'
        [Environment]::SetEnvironmentVariable("Path", $newPath, "Machine")
        Write-Info "Removed from system PATH"
    }
}

function Write-Success {
    $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notlike "*Loopback*" -and $_.PrefixOrigin -ne "WellKnown" } | Select-Object -First 1).IPAddress
    if (-not $ip) { $ip = "localhost" }

    Write-Host ""
    Write-Host "╔═══════════════════════════════════════════╗" -ForegroundColor Green
    Write-Host "║       Installation Complete!              ║" -ForegroundColor Green
    Write-Host "╚═══════════════════════════════════════════╝" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Dashboard: " -NoNewline
    Write-Host "http://${ip}:8080" -ForegroundColor Cyan
    Write-Host "  Health:    " -NoNewline
    Write-Host "http://${ip}:8080/health" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Service Commands:" -ForegroundColor Yellow
    Write-Host "    Get-Service ZimaOS-Echo              - Check status"
    Write-Host "    Restart-Service ZimaOS-Echo          - Restart service"
    Write-Host "    Stop-Service ZimaOS-Echo             - Stop service"
    Write-Host "    Start-Service ZimaOS-Echo            - Start service"
    Write-Host ""
    Write-Host "  CLI Commands:" -ForegroundColor Yellow
    Write-Host "    echo.exe status                      - Check service status"
    Write-Host "    echo.exe restart                     - Restart service"
    Write-Host "    echo.exe --help                      - Show all commands"
    Write-Host ""
    Write-Host "  View Logs:" -ForegroundColor Yellow
    Write-Host "    Get-EventLog -LogName Application -Source ZimaOS-Echo -Newest 20"
    Write-Host "    Get-WinEvent -FilterHashtable @{LogName='Application';ProviderName='ZimaOS-Echo'} -MaxEvents 20"
    Write-Host ""
    Write-Host "  Config: " -NoNewline
    Write-Host "$InstallDir\config\config.yaml" -ForegroundColor Cyan
    Write-Host "  Data:   " -NoNewline
    Write-Host "$InstallDir\data" -ForegroundColor Cyan
    Write-Host "  Logs:   " -NoNewline
    Write-Host "$InstallDir\logs" -ForegroundColor Cyan
    Write-Host ""
}

function Write-UninstallSuccess {
    Write-Host ""
    Write-Host "╔═══════════════════════════════════════════╗" -ForegroundColor Green
    Write-Host "║       Uninstallation Complete!            ║" -ForegroundColor Green
    Write-Host "╚═══════════════════════════════════════════╝" -ForegroundColor Green
    Write-Host ""
    Write-Host "  ZimaOS-Echo has been uninstalled."
    Write-Host ""
    Write-Host "  Note: Configuration and data files were preserved at:"
    Write-Host "    $InstallDir"
    Write-Host ""
    Write-Host "  To completely remove all data, run:"
    Write-Host "    Remove-Item -Recurse -Force '$InstallDir'"
    Write-Host ""
}

function Invoke-Install {
    Write-Banner

    if (-not (Test-Administrator)) {
        Write-Err "Please run as Administrator"
        Write-Host "  Right-click PowerShell and select 'Run as Administrator'"
        exit 1
    }

    Get-LatestVersion
    Install-Binary
    New-DefaultConfig
    Install-EventLogSource
    Add-ToPath

    if (-not $NoService) {
        Install-WindowsService
    } else {
        Write-Info "Skipping service installation (--NoService specified)"
        Write-Info "To run manually: echo.exe --config `"$InstallDir\config\config.yaml`""
    }

    Add-FirewallRule
    Write-Success
}

function Invoke-Uninstall {
    Write-Banner

    if (-not (Test-Administrator)) {
        Write-Err "Please run as Administrator"
        Write-Host "  Right-click PowerShell and select 'Run as Administrator'"
        exit 1
    }

    Write-Info "Uninstalling ZimaOS-Echo..."

    Uninstall-WindowsService
    Remove-FirewallRule
    Remove-EventLogSource
    Remove-FromPath

    # Remove binaries but keep config and data
    $binDir = Join-Path $InstallDir "bin"
    if (Test-Path $binDir) {
        Remove-Item -Recurse -Force $binDir
        Write-Info "Removed binaries"
    }

    Write-UninstallSuccess
}

# Main entry point
if ($Uninstall) {
    Invoke-Uninstall
} else {
    Invoke-Install
}
