/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const CHAT_STYLES: typeof import('./stores/settings').CHAT_STYLES
  const EffectScope: typeof import('vue').EffectScope
  const THEME_STYLES: typeof import('./stores/settings').THEME_STYLES
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const classifyMediaIntent: typeof import('./composables/useMediaIntent').classifyMediaIntent
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const fullscreenContent: typeof import('./composables/useFullscreen').fullscreenContent
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getLastModel: typeof import('./composables/useMediaGenerate').getLastModel
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isFullscreen: typeof import('./composables/useFullscreen').isFullscreen
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const offSSEEvent: typeof import('./composables/useEventStream').offSSEEvent
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onSSEEvent: typeof import('./composables/useEventStream').onSSEEvent
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const refreshTauriDetection: typeof import('./composables/useTauri').refreshTauriDetection
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const setPasteAreaExpanded: typeof import('./composables/useFormFillerWidget').setPasteAreaExpanded
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useA2UIWebSocket: typeof import('./composables/useA2UI').useA2UIWebSocket
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./stores/auth').useAuthStore
  const useAutoReplyStore: typeof import('./stores/autoreply').useAutoReplyStore
  const useChatShortcuts: typeof import('./composables/useKeyboardShortcuts').useChatShortcuts
  const useChatStore: typeof import('./stores/chat').useChatStore
  const useClipboard: typeof import('@vueuse/core').useClipboard
  const useCompanionStore: typeof import('./stores/companion').useCompanionStore
  const useCompanionStream: typeof import('./composables/useCompanionStream').useCompanionStream
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDark: typeof import('@vueuse/core').useDark
  const useDashboardStore: typeof import('./stores/dashboard').useDashboardStore
  const useDebounce: typeof import('@vueuse/core').useDebounce
  const useEventListener: typeof import('@vueuse/core').useEventListener
  const useEventStream: typeof import('./composables/useEventStream').useEventStream
  const useFormFillerWidget: typeof import('./composables/useFormFillerWidget').useFormFillerWidget
  const useFullscreen: typeof import('./composables/useFullscreen').useFullscreen
  const useGateway: typeof import('./composables/useGateway').useGateway
  const useGlobalShortcuts: typeof import('./composables/useKeyboardShortcuts').useGlobalShortcuts
  const useId: typeof import('vue').useId
  const useKeyboardShortcuts: typeof import('./composables/useKeyboardShortcuts').useKeyboardShortcuts
  const useLink: typeof import('vue-router').useLink
  const useLocalStorage: typeof import('@vueuse/core').useLocalStorage
  const useLocaleStore: typeof import('./stores/locale').useLocaleStore
  const useMediaGenerate: typeof import('./composables/useMediaGenerate').useMediaGenerate
  const useMediaTaskTracker: typeof import('./stores/mediaTaskTracker').useMediaTaskTracker
  const useMetricsStore: typeof import('./stores/metrics').useMetricsStore
  const useModel: typeof import('vue').useModel
  const useNetwork: typeof import('./composables/useNetwork').useNetwork
  const useNotificationStore: typeof import('./stores/notification').useNotificationStore
  const usePermissions: typeof import('./composables/usePermissions').usePermissions
  const usePersonalityStore: typeof import('./stores/personality').usePersonalityStore
  const usePluginStore: typeof import('./stores/plugin').usePluginStore
  const usePreviewStore: typeof import('./stores/preview').usePreviewStore
  const useProviderPoolStore: typeof import('./stores/providerPool').useProviderPoolStore
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSettingsStore: typeof import('./stores/settings').useSettingsStore
  const useSkillStore: typeof import('./stores/skill').useSkillStore
  const useSlots: typeof import('vue').useSlots
  const useStorage: typeof import('@vueuse/core').useStorage
  const useSystemStore: typeof import('./stores/system').useSystemStore
  const useTTSStore: typeof import('./stores/tts').useTTSStore
  const useTauri: typeof import('./composables/useTauri').useTauri
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTenantStore: typeof import('./stores/tenant').useTenantStore
  const useThemeStore: typeof import('./stores/theme').useThemeStore
  const useThrottle: typeof import('@vueuse/core').useThrottle
  const useToggle: typeof import('@vueuse/core').useToggle
  const useToolStore: typeof import('./stores/tool').useToolStore
  const useWebPush: typeof import('./composables/useWebPush').useWebPush
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { UseCompanionStreamOptions } from './composables/useCompanionStream'
  import('./composables/useCompanionStream')
  // @ts-ignore
  export type { FillHistoryEntry, WidgetPosition, WidgetState } from './composables/useFormFillerWidget'
  import('./composables/useFormFillerWidget')
  // @ts-ignore
  export type { FullscreenContent } from './composables/useFullscreen'
  import('./composables/useFullscreen')
  // @ts-ignore
  export type { KeyboardShortcut } from './composables/useKeyboardShortcuts'
  import('./composables/useKeyboardShortcuts')
  // @ts-ignore
  export type { NetworkInterface, NetworkAddresses, NetworkStatus } from './composables/useNetwork'
  import('./composables/useNetwork')
  // @ts-ignore
  export type { Platform } from './composables/useTauri'
  import('./composables/useTauri')
  // @ts-ignore
  export type { EventState, EventStateTransition, TrackedEvent } from './stores/companion'
  import('./stores/companion')
  // @ts-ignore
  export type { NotificationType, Notification } from './stores/notification'
  import('./stores/notification')
  // @ts-ignore
  export type { ChatModelInfo, ChatProviderInfo, ProviderModelOption, ThemeStyle, CloseBehavior } from './stores/settings'
  import('./stores/settings')
  // @ts-ignore
  export type { Theme } from './stores/theme'
  import('./stores/theme')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly THEME_STYLES: UnwrapRef<typeof import('./stores/settings')['THEME_STYLES']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly classifyMediaIntent: UnwrapRef<typeof import('./composables/useMediaIntent')['classifyMediaIntent']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly fullscreenContent: UnwrapRef<typeof import('./composables/useFullscreen')['fullscreenContent']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getLastModel: UnwrapRef<typeof import('./composables/useMediaGenerate')['getLastModel']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isFullscreen: UnwrapRef<typeof import('./composables/useFullscreen')['isFullscreen']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly offSSEEvent: UnwrapRef<typeof import('./composables/useEventStream')['offSSEEvent']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onSSEEvent: UnwrapRef<typeof import('./composables/useEventStream')['onSSEEvent']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly refreshTauriDetection: UnwrapRef<typeof import('./composables/useTauri')['refreshTauriDetection']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly setPasteAreaExpanded: UnwrapRef<typeof import('./composables/useFormFillerWidget')['setPasteAreaExpanded']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthStore: UnwrapRef<typeof import('./stores/auth')['useAuthStore']>
    readonly useAutoReplyStore: UnwrapRef<typeof import('./stores/autoreply')['useAutoReplyStore']>
    readonly useChatShortcuts: UnwrapRef<typeof import('./composables/useKeyboardShortcuts')['useChatShortcuts']>
    readonly useChatStore: UnwrapRef<typeof import('./stores/chat')['useChatStore']>
    readonly useClipboard: UnwrapRef<typeof import('@vueuse/core')['useClipboard']>
    readonly useCompanionStore: UnwrapRef<typeof import('./stores/companion')['useCompanionStore']>
    readonly useCompanionStream: UnwrapRef<typeof import('./composables/useCompanionStream')['useCompanionStream']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDark: UnwrapRef<typeof import('@vueuse/core')['useDark']>
    readonly useDashboardStore: UnwrapRef<typeof import('./stores/dashboard')['useDashboardStore']>
    readonly useDebounce: UnwrapRef<typeof import('@vueuse/core')['useDebounce']>
    readonly useEventListener: UnwrapRef<typeof import('@vueuse/core')['useEventListener']>
    readonly useEventStream: UnwrapRef<typeof import('./composables/useEventStream')['useEventStream']>
    readonly useFormFillerWidget: UnwrapRef<typeof import('./composables/useFormFillerWidget')['useFormFillerWidget']>
    readonly useFullscreen: UnwrapRef<typeof import('./composables/useFullscreen')['useFullscreen']>
    readonly useGateway: UnwrapRef<typeof import('./composables/useGateway')['useGateway']>
    readonly useGlobalShortcuts: UnwrapRef<typeof import('./composables/useKeyboardShortcuts')['useGlobalShortcuts']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useKeyboardShortcuts: UnwrapRef<typeof import('./composables/useKeyboardShortcuts')['useKeyboardShortcuts']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLocalStorage: UnwrapRef<typeof import('@vueuse/core')['useLocalStorage']>
    readonly useLocaleStore: UnwrapRef<typeof import('./stores/locale')['useLocaleStore']>
    readonly useMediaGenerate: UnwrapRef<typeof import('./composables/useMediaGenerate')['useMediaGenerate']>
    readonly useMediaTaskTracker: UnwrapRef<typeof import('./stores/mediaTaskTracker')['useMediaTaskTracker']>
    readonly useMetricsStore: UnwrapRef<typeof import('./stores/metrics')['useMetricsStore']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNetwork: UnwrapRef<typeof import('./composables/useNetwork')['useNetwork']>
    readonly useNotificationStore: UnwrapRef<typeof import('./stores/notification')['useNotificationStore']>
    readonly usePermissions: UnwrapRef<typeof import('./composables/usePermissions')['usePermissions']>
    readonly usePluginStore: UnwrapRef<typeof import('./stores/plugin')['usePluginStore']>
    readonly usePreviewStore: UnwrapRef<typeof import('./stores/preview')['usePreviewStore']>
    readonly useProviderPoolStore: UnwrapRef<typeof import('./stores/providerPool')['useProviderPoolStore']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSettingsStore: UnwrapRef<typeof import('./stores/settings')['useSettingsStore']>
    readonly useSkillStore: UnwrapRef<typeof import('./stores/skill')['useSkillStore']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useStorage: UnwrapRef<typeof import('@vueuse/core')['useStorage']>
    readonly useSystemStore: UnwrapRef<typeof import('./stores/system')['useSystemStore']>
    readonly useTTSStore: UnwrapRef<typeof import('./stores/tts')['useTTSStore']>
    readonly useTauri: UnwrapRef<typeof import('./composables/useTauri')['useTauri']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTenantStore: UnwrapRef<typeof import('./stores/tenant')['useTenantStore']>
    readonly useThemeStore: UnwrapRef<typeof import('./stores/theme')['useThemeStore']>
    readonly useThrottle: UnwrapRef<typeof import('@vueuse/core')['useThrottle']>
    readonly useToggle: UnwrapRef<typeof import('@vueuse/core')['useToggle']>
    readonly useToolStore: UnwrapRef<typeof import('./stores/tool')['useToolStore']>
    readonly useWebPush: UnwrapRef<typeof import('./composables/useWebPush')['useWebPush']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}